### ISSUE TITLE
 'NSLayoutAttribute' was obsoleted in Swift 4.2

### ISSUE THREAD

**Issue by farabi** [AAChartModel/AAChartKit-Swift#107]
Hello. 

Thank you for this library.
Unfortunately, not able to build the module. i have the following error :

/UIKit.NSLayoutAttribute:2:18: 'NSLayoutAttribute' was obsoleted in Swift 4.2
NSLayoutAttribute' has been renamed to 'NSLayoutConstraint.Attribute'

**Comment by SylvesterChima** [comment]
Am having same error here

**Comment by AAChartModel** [comment]
it was fixed.
