### ISSUE TITLE
Chart content view works in simulator but not in real device!

### ISSUE THREAD

**Issue by ahmetoztemiz** [AAChartModel/AAChartKit-Swift#109]

**Comment by ahmetoztemiz** [comment]
Chartpod created chart frame as correct size but my html content did not fit in frame and also, when i give different content size, it does not reflect in real device. In the simulator, we can see correct sizes but not in real devices.

<img width="656" alt="screen shot 2018-12-12 at 12 13 33" src="https://user-images.githubusercontent.com/23167859/49858952-5ccd8880-fe07-11e8-9744-63e28488eda3.png">

<img width="404" alt="screen shot 2018-12-12 at 12 12 52" src="https://user-images.githubusercontent.com/23167859/49858967-635c0000-fe07-11e8-99c8-a6ee76b70461.png">

**Comment by AAChartModel** [comment]
please post the code text rather than code image, thanks!

**Comment by ahmetoztemiz** [comment]
```
import UIKit
import AAInfographics

class ReportVC: BaseVC {

    
    private var aaChartModel: AAChartModel?
    private var aaChartView: AAChartView?
    private var chartType: AAChartType?
    
    var reportsData: [ReportsModel] = []
    let category = ReportsModel.categories()
    var chartDataList: [Int] = []
    var chartDataDict: [String: [Int]] = [:]
    var shoppingList: [String] = []
    
    var chartData: [[String: AnyObject]] = [[:]]
    var chartTitle: String = "" {
        didSet {
            chartData = [
                AASeriesElement()
                    .name(chartTitle)
                    .data(chartDataList)
                    .toDic()!]
            
            self.aaChartModel?
                .title(chartTitle)
                .categories(shoppingList)
                .series(chartData)
            
            self.aaChartView?.aa_refreshChartWholeContentWithChartModel(self.aaChartModel!)
        }
    }
    
    override func viewDidAppear(_ animated: Bool) {
        self.createAAChart(title: chartTitle, categories: shoppingList, data: chartData)
    }
    
    func createAAChart(title: String, categories: [String], data: [[String : AnyObject]]) {
        let chartViewWidth  = self.view.frame.size.width
        let chartViewHeight = self.view.frame.size.height
        let screenHeight = UIScreen.main.bounds.height
        
        aaChartView = AAChartView()
        aaChartView?.frame = CGRect(x: 0, y: 55, width: chartViewWidth, height: chartViewHeight)
        //aaChartView?.contentHeight = screenHeight
        //aaChartView?.scrollEnabled = false
        
        self.view.addSubview(aaChartView!)
        
        aaChartModel = AAChartModel()
            .chartType(.column)
            .animationType(.bounce)
            .title(title)
            //.subtitle("subtitle")
            .dataLabelEnabled(false)
            //.tooltipValueSuffix(" Kere")
            .categories(categories)
            .colorsTheme(["#39BCF0"])
            .series(data)
        
        aaChartView?.aa_drawChartWithChartModel(aaChartModel!)
    }   
}

```

**Comment by ahmetoztemiz** [comment]
Also, swift demo project have same problem which is published in this repository.

**Comment by AAChartModel** [comment]
Are you sure you did the same thing in the real device and simulator? Why  cannot  I reproduce your problem?

**Comment by AAChartModel** [comment]
I get the same graphics on the real machine and the simulator with AAChartKit-Swift demo

**Comment by ahmetoztemiz** [comment]
I am taking pod as shown below. Is it correct way to install it? And i do not know why is it happening because it is working correctly but after a while graphics changed from real device.
`pod 'AAInfographics', :git => "https://github.com/AAChartModel/AAChartKit-Swift.git"`

**Comment by ahmetoztemiz** [comment]
I put text field from storyBoard and i used dropDowns pod , do you think it is affect to the chart?

**Comment by ahmetoztemiz** [comment]
![ezgif-5-1bc3b1c4ad1d](https://user-images.githubusercontent.com/23167859/49866097-d79e9f80-fe17-11e8-9eb2-75e65e6e4e1a.gif)

**Comment by AAChartModel** [comment]
You can upload your demo into GitHub, and post the link, I  will download and test it to find out what is going on on earth.

**Comment by ahmetoztemiz** [comment]
https://github.com/ahmetoztemiz/aaChart-test

**Comment by ahmetoztemiz** [comment]
By the way i downloaded AAChartKit-Swift demo project and it have same issue.

**Comment by AAChartModel** [comment]
![untitled](https://user-images.githubusercontent.com/16357599/49881255-dd70a100-fe68-11e8-8fb0-0b9e4d7e9137.gif)
Still can not reproduce your problem.My iOS device is iPhone X with iOS 12.0.1.
And I've never had this problem with anyone else. Sorry, I do not know what is going on here. maybe you should migrate to other swift language charts  library😢😢😢

**Comment by AAChartModel** [comment]
Look at the commit  511330d ,I think the problem was fixed

**Comment by ahmetoztemiz** [comment]
> I faced the same problem as my friend. Forked and updated your project. If everything is OK, i can send you a pull request.
> 
> You can check the updated repo from [here](https://github.com/sonerokur/AAChartKit-Swift)

That's exactly what i want. Thanks a lot.

**Comment by pvmodin** [comment]
I'm experiencing the issue as described above. On simulator it fits just fine, but on device the chart goes out of bounds.

<img width="425" alt="Screen Shot 2020-06-03 at 11 40 07 PM" src="https://user-images.githubusercontent.com/18331871/83723474-9eea1b80-a5f3-11ea-802d-b62be45c4dc7.png">

^Sumulator^

<img width="425" alt="Screen Shot 2020-06-03 at 11 40 07 PM" src="https://user-images.githubusercontent.com/18331871/83723731-fab4a480-a5f3-11ea-8601-5c1380e2361f.jpeg">

^iPhone X 13.4.1^


I added this via:
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'

Did I do this right?
