### ISSUE TITLE
Make line graph Y-axis start at lowest value of series.

### ISSUE THREAD

**Issue by thijsheijden** [AAChartModel/AAChartKit-Swift#116]
Hey, I'm trying to make a stocks app, and when using this library I ran into something I couldn't figure out myself. Currently when plotting my chart it looks like this:
![simulator screen shot - iphone x - 2019-01-02 at 16 13 02](https://user-images.githubusercontent.com/26046598/50598097-fee20d00-0ea9-11e9-844f-1021c7edec04.png)

and I was just wondering wether its possible to remove all the area under the chart by making the y-axis start at the lowest series value and making the increments in the y-axis larger. Also I was wondering what happened to the gradient property as I can't find that anywhere? Thanks in advance!

**Comment by AAChartModel** [comment]
### Step 1:  Configure AAOptions
```swift
  let aaChartModel = AAChartModel()
            .chartType(.column)//图表类型
            .title("")//图表主标题
            .subtitle("")//图表副标题
            .borderRadius(5)
            .series([
                AASeriesElement()
                    .name("2020")
                    .data([1003.9, 1004.2, 1005.7, 1008.5, 1011.9, 1015.2,])
                    .color(AAGradientColor.sanguine)
                    .toDic()!
                ]
        )
        
        let aaOptions = AAOptionsConstructor.configureAAoptions(aaChartModel: aaChartModel)
        let aaYAxis = aaOptions["yAxis"] as! NSMutableDictionary
        aaYAxis["min"] = 1000
```

### Step 2:  Draw chart with AAOptions
```swift
        aaChartView.aa_drawChartWithChartOptions(aaOptions)
```

You will get 



![image](https://user-images.githubusercontent.com/16357599/50633999-26a7a280-0f88-11e9-836e-7c58376106f0.png)

**Comment by AAChartModel** [comment]
Key words 

```swift

aaYAxis["min"] = 1000 //set the min value of Y axis
```

**Comment by oyychn** [comment]
can i set xAxis granularity to 90 not 50?
I need to show max value(360) for PRPD charts.
