### ISSUE TITLE
X axis labels showing only pair values when one column is too great

### ISSUE THREAD

**Issue by RomuloVHSYS** [AAChartModel/AAChartKit-Swift#121]
Firstly, my code to chart:

My ChartView has the size: `CGSize(width: 308, height: 138)`

And the model: 
```swift
let series = [1000, 1500, 2000, 1500, 1000, 1500, 2000, 1500, 1000, 1500, 2000, 1500]
        let chartModelServices = AAChartModel()
            .chartType(.column)
            .animationType(.easeOutCirc)
            .dataLabelEnabled(false)
            .tooltipEnabled(true)
            .tooltipValueSuffix(" BRL")
            .title("")
            .categories(self.twelveMonthSequence)
            .series([
                AASeriesElement()
                    .name("OS Faturadas")
                    .data(series)
                    .toDic()!
                ])
            .colorsTheme(["#08FFAA"])
            .yAxisGridLineWidth(0.0)
            .xAxisGridLineWidth(0.0)
            .backgroundColor("rgba(0,0,0,0)")
            .axisColor("#ffffff")
            .legendEnabled(false)
```

You can replicate this only on small screens like iPhone SE or smaller.

All occurs normally when the series difference are small:

![image](https://user-images.githubusercontent.com/44377984/51343415-866c7600-1a7d-11e9-8046-fedfe61d0868.png)

But when i change one serie to a great amount, something like hundred billions, half of categories disappear, only the pairs one appear:

change the series to `let series = [1000, 1500, 2000, 1500, 1000, 1500, 2000, 1500, 1000, 1500, 2000, 100000000000]`

![image](https://user-images.githubusercontent.com/44377984/51344715-65595480-1a80-11e9-8316-b73487eb5ea9.png)

Is that common? Or it's a bug?

If is expected that the chart work like this, there is a way of don't do that?

**Comment by AAChartModel** [comment]
I think it is common result rather than a bug. the great serie you setted is too big to show the other 
small series value.

Just picture a scene , you can find a person shadow in the Great Wall map but in a 
bigger scale map ,for example, in  world map,you can not even find the Great Wall, much less a person shadow.
It is all about the data value scale

**Comment by AAChartModel** [comment]
The HighCharts data value scale come from the greatest value in chart series data by default

**Comment by RomuloVHSYS** [comment]
I understand that, but there is a way to at least don't hide half of the labels? 

That's look a little weird, i have users reporting this like it's a bug

**Comment by RomuloVHSYS** [comment]
@AAChartModel Do you have any solution for this?

**Comment by AAChartModel** [comment]
### Step 1: configure AAOptions

```swift
       let aaChartModel = AAChartModel()
            .chartType(.column)//图表类型
            .title("")//图表主标题
            .subtitle("")//图表副标题
            .colorsTheme(["#ffc069","#fe117c","#06caf4","#7dffc0"])//设置主体颜色数组
            .categories(["Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])
            .dataLabelEnabled(false)
            .legendEnabled(false)
            .series([
                AASeriesElement()
                    .name("2020")
                    .data([1000, 1500, 2000, 1500, 1000, 1500, 2000, 1500, 1000, 1500, 2000, 100000000000])
                    .toDic()!
                ]
        )
        
        let aaOptions = AAOptionsConstructor.configureAAoptions(aaChartModel: aaChartModel)
        
  
```

### Step 2: configure AAOptions X axis labels autoRotation

```swift
  let aaXAxisLabels =  ["autoRotation": [-10, -20, -30, -40, -50, -60, -70, -80, -90]]

        let aaXAxis = aaOptions["xAxis"] as! NSMutableDictionary
        
        aaXAxis["labels"] = aaXAxisLabels
```

### Step 3: draw chart with AAOptions 

```swift
        aaChartView.aa_drawChartWithChartOptions(aaOptions)
```


You will get 
![image](https://user-images.githubusercontent.com/16357599/51508847-f5591e80-1e31-11e9-826d-b2e5d60c2a82.png)

**Comment by AAChartModel** [comment]
Refer to  the link:

https://api.highcharts.com/highcharts/xAxis.labels.autoRotation

**Comment by RomuloVHSYS** [comment]
That's exactly what i want!
Thanks a lot.
