### ISSUE TITLE
X axis small bottom separator (vertical) line not show 

### ISSUE THREAD

**Issue by Hardiktspaceo** [AAChartModel/AAChartKit-Swift#139]
X axis small separator line not show 
>> when we pass **.categories manually** in AAChartModel at that time the small separator **NOT display**, but when we create mode **without categories** it will show that separator line. and in **pervious version this is working fine in when we pass .categories manually**. please find below screenshot
![OLD ONE](https://user-images.githubusercontent.com/25246691/57363862-97adcf80-719f-11e9-81b9-e23d813ebcd3.PNG)
![NewOne](https://user-images.githubusercontent.com/25246691/57364035-ef4c3b00-719f-11e9-92b1-fdfe813cbe4f.png)

**Comment by AAChartModel** [comment]
I think maybe it is a bug caused by Highcharts v7.1.1, or the default X axis style was changed in latest version Highcharts(v7.1.1)

**Comment by Hardiktspaceo** [comment]
@AAChartModel Thank you so much.. issue solve by this 7fc6179 commit related changes.

**Comment by AAChartModel** [comment]
🙂
