### ISSUE TITLE
Contiguity Chart

### ISSUE THREAD

**Issue by qcasxy** [AAChartModel/AAChartKit-Swift#140]
像下面这样的图是否能有简便的实现方法？
![img](https://qvdesign.files.wordpress.com/2012/03/defrag-chart-main.png)
具体而言这看上去像是个堆叠条形图，但是它每一条数据被分成任意多个块（条形堆叠图每一条的块数是固定的）。另外每条数据上块的颜色顺序也不相同（堆叠图上每条数据的块颜色顺序是固定的）。

**Comment by AAChartModel** [comment]
你这图形效果从哪里截图得来的? 这个貌似不是 Highcharts 默认能够支持的图表种类啊

**Comment by qcasxy** [comment]
图片是网上找的（https://qvdesign.wordpress.com/2012/03/29/qlikview-contiguity-chart-aka-that-chart-from-the-windows-disk-defragmenter/）
我需要实现一个跟上面这张图类似的图表，用于展示某台生产设备，指定月份中每一天的实时开机状态。
事实上我原本是用的[Charts](https://github.com/danielgindi/Charts)这个库实现的，但可惜的是当我的数据量变大时（大概每天会有几千条数据，极限状态是每天最多有8640条数据需要显示）Charts这个库为了绘制图表就会几乎占满CPU，而使程序变得非常的卡顿。所以我现在考虑使用WKWebview加载Echarts或Highcharts来实现，希望能有所改善。
我最近查看了Echarts和Highcharts的演示案例，确实没有发现符合我要求的图表。因为我对前端东西不是很了解，所以想问下这样的效果能否实现。

**Comment by AAChartModel** [comment]
Vega-Lite  可能是你的解药

https://vega.github.io/vega-lite/examples/tick_strip.html

**Comment by AAChartModel** [comment]
https://gramener.github.io/visual-vocabulary-vega/#/Distribution/

![image](https://user-images.githubusercontent.com/16357599/57458089-5272c600-72a3-11e9-8be6-30ba3c00e638.png)

**Comment by AAChartModel** [comment]
[Charts](https://github.com/danielgindi/Charts) 虽然是原生的,但毕竟没有默认的这种 `barcode plot` 条码图,你用它来实现需求还是有点太硬核了. 看 **vega** 的介绍,其中有一个重要的应用就是科研领域的数据可视化,此种应用场景下数据量一般都比较庞大,你的峰值数据量是**8640条数据**应该不会有太大问题.
