### ISSUE TITLE
如何修改选中区域, 灰色区域的宽度

### ISSUE THREAD

**Issue by Kingzhijie** [AAChartModel/AAChartKit-Swift#142]
修改了X轴的名称后, 选中的线就变成一个灰色长方形了, 可以修改吗

![屏幕快照 2019-05-21 下午1 46 43](https://user-images.githubusercontent.com/13587739/58071388-13ac0c80-7bcf-11e9-809e-c25ec7e12ee4.png)

![屏幕快照 2019-05-21 下午1 43 12](https://user-images.githubusercontent.com/13587739/58071184-633e0880-7bce-11e9-844e-8a06863fbdad.png)
 
可以修改成一条线吗

**Comment by Kingzhijie** [comment]
修改了X轴的名称后,  选中的线就变成一个长方形了, 可以修改吗
![屏幕快照 2019-05-21 下午1 46 43](https://user-images.githubusercontent.com/13587739/58071388-13ac0c80-7bcf-11e9-809e-c25ec7e12ee4.png)

**Comment by AAChartModel** [comment]
修改AAChartModel的`crosshair`(十字准星线🧶的宽度即可)

**Comment by AAChartModel** [comment]
```objc
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, xAxisCrosshairWidth) //设置 x 轴准星线的宽度
AAPropStatementAndPropSetFuncStatement(copy,   AAChartModel, NSString *, xAxisCrosshairColor) //设置 x 轴准星线的颜色
AAPropStatementAndPropSetFuncStatement(assign, AAChartModel, AALineDashStyleType,   xAxisCrosshairDashStyleType) //设置 x 轴准星线的线条样式类型
```

**Comment by AAChartModel** [comment]
准星线的线条样式类型可选值
```objc
typedef NSString *AALineDashStyleType;

AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeSolid;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeShortDash;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeShortDot;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeShortDashDot;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeShortDashDotDot;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeDot;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeDash;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeLongDash;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeDashDot;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeLongDashDot;
AACHARTKIT_EXTERN AALineDashStyleType const AALineDashStyleTypeLongDashDotDot;
```

**Comment by Kingzhijie** [comment]
> ```objc
>  //设置 x 轴准星线的宽度
> AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, xAxisCrosshairWidth)
> //设置 x 轴准星线的颜色
> AAPropStatementAndPropSetFuncStatement(copy,   AAChartModel, NSString *, xAxisCrosshairColor)
> //设置 x 轴准星线的线条样式类型 
> AAPropStatementAndPropSetFuncStatement(assign, AAChartModel, AALineDashStyleType,   xAxisCrosshairDashStyleType) 
> ```

swift版本的也贴一下, 可以吗,  我在swift版本的demo中没有找到, 该方法, 谢谢

**Comment by AAChartModel** [comment]
swift版本的确实还没有相关的接口,不过你可以这样配置AAOptions来完成设置

1. 配置AAOptions实例对象
```swift
        let aaChartModel = AAChartModel()
            .chartType(.line)//图表类型
            .series([
                AASeriesElement()
                    .name("2020")
                    .color(AAGradientColor.deepSea!)
                    .data([
                        [12464064, 21.5],
                        [12464928, 22.1],
                        [12465792,   23],
                        [12466656, 23.8],
                        [12467520, 21.4],
                        [12468384, 21.3],
                        [12469248, 18.3],
                        [12470112, 15.4],
                        [12470976, 16.4],
                        [12471840, 17.7],
                        [12472704, 17.5],
                        [12473568, 17.6],
                        [12474432, 17.7],
                        [12475296, 16.8],
                        [12476160, 17.7],
                        [12477024, 16.3],
                        [12477888, 17.8],
                        [12478752, 18.1],
                        [12479616, 17.2],
                        [12480480, 14.4],
                        [12481344, 13.7],
                        [12482208, 15.7],
                        [12483072, 14.6],
                        [12483936, 15.3],
                        [12484800, 15.3],
                        [12485664, 15.8],
                        [12486528, 15.2],
                        [12487392, 14.8],
                        [12488256, 14.4],
                        [12489120,   15],
                        [12489984, 13.6]
                        ])
                    .toDic()!
                ]
        )
        
        let aaOptions = AAOptionsConstructor.configureAAoptions(aaChartModel: aaChartModel)
        let aaXAxis = aaOptions["xAxis"] as! NSMutableDictionary
        let aaCrosshair = [
            "width":1,
            "color":AAColor.red!,
            "dashStyle":AALineDashSyleType.longDashDot.rawValue,
            ] as [String: Any]
        aaXAxis["crosshair"] = aaCrosshair
```

2. 绘制图形
```swift
        aaChartView.aa_drawChartWithChartOptions(aaOptions)

```

最终效果

![image](https://user-images.githubusercontent.com/16357599/58074295-84efbd80-7bd7-11e9-9f1d-f92e2ecc5966.png)

**Comment by Kingzhijie** [comment]
> swift版本的确实还没有相关的接口,不过你可以这样配置AAOptions来完成设置
> 
> 1. 配置AAOptions实例对象
> 
> ```swift
>         let aaChartModel = AAChartModel()
>             .chartType(.line)//图表类型
>             .series([
>                 AASeriesElement()
>                     .name("2020")
>                     .color(AAGradientColor.deepSea!)
>                     .data([
>                         [12464064, 21.5],
>                         [12464928, 22.1],
>                         [12465792,   23],
>                         [12466656, 23.8],
>                         [12467520, 21.4],
>                         [12468384, 21.3],
>                         [12469248, 18.3],
>                         [12470112, 15.4],
>                         [12470976, 16.4],
>                         [12471840, 17.7],
>                         [12472704, 17.5],
>                         [12473568, 17.6],
>                         [12474432, 17.7],
>                         [12475296, 16.8],
>                         [12476160, 17.7],
>                         [12477024, 16.3],
>                         [12477888, 17.8],
>                         [12478752, 18.1],
>                         [12479616, 17.2],
>                         [12480480, 14.4],
>                         [12481344, 13.7],
>                         [12482208, 15.7],
>                         [12483072, 14.6],
>                         [12483936, 15.3],
>                         [12484800, 15.3],
>                         [12485664, 15.8],
>                         [12486528, 15.2],
>                         [12487392, 14.8],
>                         [12488256, 14.4],
>                         [12489120,   15],
>                         [12489984, 13.6]
>                         ])
>                     .toDic()!
>                 ]
>         )
>         
>         let aaOptions = AAOptionsConstructor.configureAAoptions(aaChartModel: aaChartModel)
>         let aaXAxis = aaOptions["xAxis"] as! NSMutableDictionary
>         let aaCrosshair = [
>             "width":1,
>             "color":AAColor.red!,
>             "dashStyle":AALineDashSyleType.longDashDot.rawValue,
>             ] as [String: Any]
>         aaXAxis["crosshair"] = aaCrosshair
> ```
> 
> 1. 绘制图形
> 
> ```swift
>         aaChartView.aa_drawChartWithChartOptions(aaOptions)
> ```
> 
> 最终效果
> 
> ![image](https://user-images.githubusercontent.com/16357599/58074295-84efbd80-7bd7-11e9-9f1d-f92e2ecc5966.png)
可以了, 万分感谢

想在再问一个问题,  X轴 的周间距, 是否可以自己控制, 这样底部的显示的就没有这么紧凑
![屏幕快照 2019-05-21 下午4 06 21](https://user-images.githubusercontent.com/13587739/58079025-aace8f80-7be2-11e9-82d7-7a4917c23aef.png)

**Comment by AAChartModel** [comment]
让底部不要过于紧凑,可以使用这个属性 `tickinterval`,设置底部间隔文字间隔几个再显示 

在线示例:  https://jshare.com.cn/github/highcharts/highcharts/tree/master/samples/highcharts/xaxis/tickinterval-5/

但是直接调整间距,我在官网的文档中似乎并没有找到相应的内容.

**Comment by AAChartModel** [comment]
官网关于X轴的所有属性,参见API文档  https://api.highcharts.com.cn/highcharts#xAxis

**Comment by Kingzhijie** [comment]
问题已解决, 超级感谢
