### ISSUE TITLE
Is there a way to set alpha value of colours

### ISSUE THREAD

**Issue by stealdre** [AAChartModel/AAChartKit-Swift#148]
Hi,

I was wondering if there is any way to set the transparency (alpha) of the colours. I'm trying to set a gradient starting from white with alpha=0.5 and ending with no colour (alpha = 0). I can't manage to do this with the hex code system of your library.
Help appreciated. Thanks.

**Comment by AAChartModel** [comment]
hex color transparency （透明度十六进制表示法）
```java
100% — FF
95% — F2
90% — E6
85% — D9
80% — CC
75% — BF
70% — B3
65% — A6
60% — 99
55% — 8C
50% — 80
45% — 73
40% — 66
35% — 59
30% — 4D
25% — 40
20% — 33
15% — 26
10% — 1A
5% — 0D
0% — 00 
 
```
       For example：`#00000080` means 0.5 opacity black color

**Comment by AAChartModel** [comment]
**The Second Way: **

* replace hex color string with rgba string 

  @"rgba(0,0,0,0.5)" is equal to `#00000080`

**Comment by AAChartModel** [comment]
is it useful?

**Comment by isaranjha** [comment]
Please add UIColor support
