### ISSUE TITLE
'tickPositions' 

### ISSUE THREAD

**Issue by oyychn** [AAChartModel/AAChartKit-Swift#159]
how to use this parameter to customize x/yAxis？
[@(0: **0,** @(25: **10**, @(50: **100**, @(75:  **1000**, (100: **10000**] 
it's not a correct format.

**Comment by AAChartModel** [comment]
Sorry, my mistake, it should be 
```swift
[0, 25, 50, 75 , 100]
```
rather than
```objc
[@(0: 0, @(25: 10, @(50: 100, @(75: 1000, (100: 10000]

```

**Comment by oyychn** [comment]
Sorry, if i want to @0:0, @25%of YAxis:10, @50% of YAxis: 100, @75%:1000, @100%:10000, how can I use this parameter?

If U speak Chinese, please see below:
我想在Y轴的0位设0，四分之一处设10，一半的位置设100，75%设1000，最大值设1000，简单来说就是10^n方

Regards


发自我的 iPhone

**Comment by AAChartModel** [comment]
Can you post a design draft picture?

**Comment by oyychn** [comment]
Thank you. 

Sorry I can not post a screenshot now. I am not in office. 
I just want to set Y-Axis interval followed this sequence: 10, 100, 1000, 10000.... 10^n.

Because I have few data like : [1, 235], [2, 1200], [3, 5000]...[20, 357], [21, 50]...
If I use normal y-Axis, I can see few data like [20, 50].

Sorry for my poor English:)

发自我的 iPhone

**Comment by oyychn** [comment]
Hi AnAn


Please see below screenshot:









At 2019-08-29 18:31:41, "An An" <notifications@github.com> wrote:


Can you post a design draft picture?

**Comment by AAChartModel** [comment]
???

**Comment by oyychn** [comment]
hi ,


I have raised an issue about ‘tickPositions’, yesterday.
Follow your previous reply, you want to see my draft design.
I need to set Y-Axis coordinate like that screenshot, it not an evenly-distributed coordinate.
I want to seek your assistance.







在 2019-08-30 09:26:47，"An An" <notifications@github.com> 写道：


???

**Comment by AAChartModel** [comment]
> Hi AnAn Please see below screenshot: At 2019-08-29 18:31:41, "An An" <notifications@github.com> wrote: Can you post a design draft picture? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I mean there is no any design draft picture.

**Comment by oyychn** [comment]
Hi 


Please see attached screenshot. I want to make one similar charts.






At 2019-08-30 10:08:40, "An An" <notifications@github.com> wrote:


Hi AnAn Please see below screenshot: At 2019-08-29 18:31:41, "An An" notifications@github.com wrote: Can you post a design draft picture? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I mean there is no any design draft picture.
