### ISSUE TITLE
How can I remove separator between chart and xAxis legends

### ISSUE THREAD

**Issue by viral-synoverge** [AAChartModel/AAChartKit-Swift#164]
I want to remove separator between xAxis and Column chart. I've tried with 

```swift
let aaAxis = AAXAxis()
		.tickLength(0)
		.plotLines([aaPlotLine])
```
		
but it removes extra tick between two legends, I do not want whole separator. 

Please guide. 
![chart](https://user-images.githubusercontent.com/20597104/64674551-b514e200-d48e-11e9-8780-0f4ed8fca79f.png)

**Comment by AAChartModel** [comment]
this is the X axis line.

```swift
let aaAxis = AAXAxis()
.lineWidth(0)// set the line width be 0, the X axis line will disappear
```

**Comment by viral-synoverge** [comment]
that works, but it removes legends, and puts 0,2,4,6 see the screenshot attached
<img width="545" alt="Screenshot 2019-09-11 at 2 55 27 PM" src="https://user-images.githubusercontent.com/20597104/64685232-43479300-d4a4-11e9-8932-52c2e17b865f.png">

code I've written is 

aaChartView!.scrollEnabled = false//禁止图表内容滚动
		aaChartView!.isClearBackgroundColor = true
//		aaChartView!.delegate = self as? AAChartViewDelegate
//		var dataDict = productDetail!.ProductParam!["Daily_Treat"]!.Days
//
		let arrValues:[Int] = [100,120,80,30,40,60,20]//Array(dataDict!.values)
		let arrKeys:[String] = ["mon","tue","wed","thur","fri","sat","sun"]//Array(dataDict!.keys)
		aaChartModel = AAChartModel()
			.chartType(chartType!)//图形类型
			.colorsTheme(["#FAA32F","#ef476f","#ffd066","#04d69f","#25547c",])//主题颜色数组
			.categories(arrKeys)//
			.xAxisLabelsEnabled(true)
			.yAxisVisible(false)
			.xAxisLabelsEnabled(true)
			.xAxisVisible(true)
			.title("")
			.subtitle("")
			.dataLabelsEnabled(true)
			.tooltipValueSuffix("")
			.animationType(.bounce)
			.backgroundColor("#ffffff")//若要使图表背景色为透明色,可将 backgroundColor 设置为 "rgba(0,0,0,0)" 或 "rgba(0,0,0,0)". 同时
			.touchEventEnabled(true)
			.borderRadius(10)
			.series([
				AASeriesElement()
					.name("Total Water Consumed (Ltrs)")
					.data(arrValues)//
					.dataLabels(AADataLabels()
						.allowOverlap(true)
						.borderRadius(20)
				),])
		
		let aaLegend = AALegend()
			.itemStyle(AAItemStyle()
				.color(AAColor.black)//字体颜色
				.fontSize("12px")//字体大小
				.fontWeight(.thin)//字体为细体字
		)
		aaChartOptions = AAOptionsConstructor.configureAAOptions(aaChartModel: aaChartModel!)
		
		let aaPlotLine = AAPlotLinesElement()
		.width(0)
		
		let aaAxis = AAXAxis()
		.tickLength(0)
		.lineWidth(0)
		.plotLines([aaPlotLine])
		
		aaChartOptions?.xAxis(aaAxis)
		aaChartOptions?.legend(aaLegend)
		aaChartView!.aa_drawChartWithChartOptions(aaChartOptions!)

**Comment by AAChartModel** [comment]
## configure AAOptions instance object 

```swift
    private func setUpOptions() -> AAOptions {
        let arrValues:[Int] = [100,120,80,30,40,60,20]//Array(dataDict!.values)
        let arrKeys:[String] = ["mon","tue","wed","thur","fri","sat","sun"]//Array(dataDict!.keys)
        aaChartModel = AAChartModel()
            .chartType(.column)//图形类型
            .colorsTheme(["#FAA32F","#ef476f","#ffd066","#04d69f","#25547c",])//主题颜色数组
            .categories(arrKeys)//
            .xAxisLabelsEnabled(true)
            .yAxisVisible(false)
            .xAxisLabelsEnabled(true)
            .xAxisVisible(true)
            .title("")
            .subtitle("")
            .dataLabelsEnabled(true)
            .tooltipValueSuffix("")
            .animationType(.bounce)
            .backgroundColor("#ffffff")//若要使图表背景色为透明色,可将 backgroundColor 设置为 "rgba(0,0,0,0)" 或 "rgba(0,0,0,0)". 同时
            .touchEventEnabled(true)
            .borderRadius(10)
            .series([
                AASeriesElement()
                    .name("Total Water Consumed (Ltrs)")
                    .data(arrValues)//
                    .dataLabels(AADataLabels()
                        .allowOverlap(true)
                        .borderRadius(20)
                ),])

       let aaChartOptions = AAOptionsConstructor.configureAAOptions(aaChartModel: aaChartModel!)
        
        aaChartOptions.xAxis?
            .tickLength(0)
            .lineWidth(0)

        return aaChartOptions
    }
```

you will get a picture like this 
![image](https://user-images.githubusercontent.com/16357599/64687926-f83a7980-d4bd-11e9-8bee-f6e86d952912.png)

**Comment by AAChartModel** [comment]
```swift
            let aaXAxis = AAXAxis()
                .labels(aaXAxisLabels)
                .reversed(aaChartModel.xAxisReversed)
                .gridLineWidth(aaChartModel.xAxisGridLineWidth) //x轴网格线宽度
                .categories(aaChartModel.categories)
                .visible(aaChartModel.xAxisVisible) //x轴是否可见
                .tickInterval(aaChartModel.xAxisTickInterval) //x轴坐标点间隔数
            
            let aaYAxisLabelsEnabled = aaChartModel.yAxisLabelsEnabled
            let aaYAxisLabels = AALabels()
                .enabled(aaChartModel.yAxisLabelsEnabled)
            if aaYAxisLabelsEnabled == true {
                aaYAxisLabels.style(
                    AAStyle()
                    .color(aaChartModel.axesTextColor)
                )
            }
```

AAXAxis instance object was initialized in `AAOptionsConstructor.swift`, you do not need to created it again.

if you create a new AAXAxis instance object like this

```swift
let aaAxis = AAXAxis()
    .tickLength(0)
    .lineWidth(0)
    .plotLines([aaPlotLine])

aaChartOptions?.xAxis(aaAxis)
```

the old AAXAxis instance object properties value will never be worked because of being covered.
