### ISSUE TITLE
set xAxis type to 'datetime' swift

### ISSUE THREAD

**Issue by jamesot** [AAChartModel/AAChartKit-Swift#165]
How can i set the type of xaxis to datetime in aaoptions? I can't seem to find an option for that.

**Comment by rosteve** [comment]
@AAChartModel is this possible?

**Comment by marymakau5** [comment]
I am also looking for the same thing...Something similar to HigCharts'
type: 'datetime',
dateTimeLabelFormats: {
     day: '%H:%M'
}

**Comment by yonat** [comment]
@AAChartModel I would love to  have this too.

**Comment by AAChartModel** [comment]
Update AAChartKit-Swift to the latest content as README said,
then you can configure X axis dateTimeLabelFormats as follow:

```swift
        aaOptions.xAxis?
            .type("dateTime")
            .dateTimeLabelFormats(
                AADateTimeLabelFormats()
                    .day("%H:%M"))
```

just like the JS version Highcharts 

```js
type: 'datetime',
dateTimeLabelFormats: {
day: '%H:%M'
}
```

**Comment by yonat** [comment]
Thanks. Note that `type("datetime")` needs to be in all lowercase.
