### ISSUE TITLE
DataLabels set image and text

### ISSUE THREAD

**Issue by DuyIoT** [AAChartModel/AAChartKit-Swift#173]
I want datalabels to custom the image and text

**Comment by AAChartModel** [comment]
Refer to https://github.com/AAChartModel/AAChartKit/issues/747

**Comment by AAChartModel** [comment]
>  @AAChartModel Sorry.
I have List data(ex: [[1,2,3], [2,3,4], [4,5,6]]
I want to get the 3rd value to display on the label?
Is this.points[2]??

Do you want to get a buble chart?

**Comment by AAChartModel** [comment]
Please post a design draft of chart

**Comment by DuyIoT** [comment]
Pie chart.
I set data AASeriesElement is list [1,2,3], [2,3,4], [4,5,6]].
Now, I want to get the 3rd value to display on the datalabel. 
ex: 3 4 6

**Comment by DuyIoT** [comment]
Ex: data = [["A", 2, "Hello"], ["B", 5, "Thanks"]]
aaChartModel = AAChartModel()
            .title("")
            .subtitle("")
            .chartType(AAChartType.pie)
            .backgroundColor(chartBgColor)
            .dataLabelsEnabled(true)
            .xAxisVisible(false)
            .yAxisVisible(false)
            .legendEnabled(false)
            .colorsTheme(colorThems)
            .series(
                [
                    AASeriesElement()
                    .name("Số Note")
                    .innerSize("80%")
                    .allowPointSelect(false)
                    .data(data)
                    .dataLabels(AADataLabels()
                        .useHTML(true)
                        .format("<img src=https://link" + this.points[2]+ "width=20 height=20>" + "<span style=color:#000000;font-size:15px>AAA</span>")),
                ]
            )
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
------
this.points[2] i want it is Hello or Thanks

**Comment by DuyIoT** [comment]
@AAChartModel Can you help me?

**Comment by DuyIoT** [comment]
Hi. It seems AADataElement helped me to do that

**Comment by DiscoverPioneer** [comment]
@DuyIoT can you show how you accomplished this?

**Comment by DuyIoT** [comment]
@DiscoverPioneer You can using AADataElement
example:
let dataElement = AADataElement()
                .y(number)
                .dataLabels(AADataLabels()
                .useHTML(true)
                .format("<img src=https://www.highcharts.com/samples/graphics/sun.png width=15 height=15>" + "<span style=color:#000000;font-size:13px>" + "\(numberB)" + "</span>"))
}
