### ISSUE TITLE
AADataElement initializer is inaccessible due to 'internal' protection level using CocoaPods

### ISSUE THREAD

**Issue by dvera128** [AAChartModel/AAChartKit-Swift#177]
Hello,

I'm using your library with CocoaPods and when I want to use AADataElement, Xcode saids:

AADataElement initializer is inaccessible due to 'internal' protection level

AADataElement class needs

`public  override init() {
    }`

in order to be accessible using CocoaPods

Please help me with this issue.
Thanks!

**Comment by AAChartModel** [comment]
It was fixed in this commit https://github.com/AAChartModel/AAChartKit-Swift/commit/596ff55562acd95f170a358138ddf69ca5eeaaf5

```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
```

 please execute the command line `pod update` to the latest version of AAChartKit-Swift
