### ISSUE TITLE
大佬，aa_onlyRefreshTheChartDataWithChartModelSeries能关掉动画效果吗？

### ISSUE THREAD

**Issue by Flabuy** [AAChartModel/AAChartKit-Swift#182]
大佬，你做的这个软件非常好、非常精致，小弟十分佩服，愿意拜倒在大佬的牛仔裤下！我是用swift的，最近碰到一个问题：我在做心电图监测，使用aa_onlyRefreshTheChartDataWithChartModelSeries刷新数据，会有动画效果，甲方不满意；现在只能使用aa_refreshChartWholeContentWithChartModel，刷新整个数据模型。甲方主要用很老的ipad，目前一秒刷新5次，GPU已经到了极限。所以，我想问一下，aa_onlyRefreshTheChartDataWithChartModelSeries能关掉动画效果吗？或者有没有其他的方案？期待大佬的回复！！！

**Comment by AAChartModel** [comment]
现已为 AAChartView新增了此方法

```swift
    /// Function of only refresh the chart data after the chart has been rendered
    ///
    /// - Parameter chartModel: chart model series  array
    /// - Parameter animation: enable animation effect or not
    public func aa_onlyRefreshTheChartDataWithChartModelSeries(_ chartModelSeries: [AASeriesElement], animation: Bool) {
        aa_onlyRefreshTheChartDataWithChartOptionsSeries(chartModelSeries, animation: animation)
    }
```
如下调用

```swift
        aa_onlyRefreshTheChartDataWithChartModelSeries(chartModelSeries, animation: false)
```

即可关闭刷新图表数据时的动画效果

**Comment by AAChartModel** [comment]
## PS:  
虽然关闭刷新图表数据时的动画效果,一定程度上能够提高性能. 但是仍然不太确定关闭动画效果能够解决像你这种高频刷新场景的问题

**Comment by Flabuy** [comment]
非常感谢大佬，这个对管理端数据展示，帮助非常大了。不过像心电图展示，客户要求非常高，我还是得自己用原生的方式重写了。
非常感谢！！！

**Comment by AAChartModel** [comment]
嗯,这样采用原生自绘的方式挺好,AAChartKit 确实不太适合高频刷新的使用场景
