### ISSUE TITLE
如何显示图例，但是图例不支持点击事件

### ISSUE THREAD

**Issue by deepindo** [AAChartModel/AAChartKit-Swift#183]
作者你好，如题

我是在swift中使用的，设置legendEnabled=true，显示图例；
但是不希望这些图例可以点击，设置touchEventEnabled=false不生效

另外allowPointSelect=false，希望表格中的每一项不可以点击，也不生效

盼回复，谢谢！

**Comment by AAChartModel** [comment]
在 AAChartKit 中 禁用图例点击事件

```objc
aaOptions.plotOptions.series.events = @{@"legendItemClick":@"false"};
```

在 AAChartKit-Swift 中与之类似

```swift
aaOptions.plotOptions.series.events = ["legendItemClick":false]
```

**Comment by AAChartModel** [comment]
参见  https://github.com/AAChartModel/AAChartKit/issues/570

**Comment by deepindo** [comment]
let model = dailySpineChartModel()
        //dailySpineChart?.aa_drawChartWithChartModel(model)
        let option = AAOptionsConstructor.configureChartOptions(model)
        option.plotOptions?.series?.events = ["legendItemClick": false]
        dailySpineChart?.aa_drawChartWithChartOptions(option)


    func dailySpineChartModel() -> AAChartModel {
        
        let model = AAChartModel()
            .chartType(.spline)
            .backgroundColor(AAColor.white)
            .colorsTheme(["#FFAE91"])
            .title("日收益金额")
            .yAxisVisible(true)
            .yAxisTitle("单位(元)")
            .yAxisLabelsEnabled(true)
            .tooltipValueSuffix("元")
            .legendEnabled(true)
            .dataLabelsEnabled(true)
            .touchEventEnabled(false)
            .categories(dailySpineCategories)
            .series([
                AASeriesElement()
                    .name("日收益金额")
                    .allowPointSelect(false)
                    .data(dailySpineSeries)
            ])
        
        return model
    }


如上，还是支持点击

**Comment by deepindo** [comment]
少机率还会触发以下报错：

☠️☠️💀☠️☠️WARNING!!!!!!!!!!!!!!!!!!!! FBI WARNING !!!!!!!!!!!!!!!!!!!! WARNING☠️☠️💀☠️☠️
==========================================================================================
------------------------------------------------------------------------------------------
code = 4;
domain = WKErrorDomain;
userInfo =     {
NSLocalizedDescription = "A JavaScript exception occurred";
WKJavaScriptExceptionColumnNumber = 21;
WKJavaScriptExceptionLineNumber = 1;
WKJavaScriptExceptionMessage = ReferenceError: Can't find variable: loadTheHighChartView;
WKJavaScriptExceptionSourceURL = file:///var/containers/Bundle/Application/3A7F7CF8-E2AE-4BB2-956B-1C291CD7056F/%E5%95%86%E7%8E%96.app/Frameworks/AAInfographics.framework/AAJSFiles.bundle/AAChartView.html;
------------------------------------------------------------------------------------------
==========================================================================================
☠️☠️💀☠️☠️WARNING!!!!!!!!!!!!!!!!!!!! FBI WARNING !!!!!!!!!!!!!!!!!!!! WARNING☠️☠️💀☠️☠️

**Comment by Nikita33** [comment]
Hi 
 Using the help of your code I am still not able to disable the clicks on the legend

**Comment by AAChartModel** [comment]
```swift
     //禁用图例点击事件
        aaOptions.plotOptions?.series?.events = AAEvents()
            .legendItemClick(#"""
                        function() {
                          return false;
                        }
            """#)
        
```

**Comment by AAChartModel** [comment]
参见 #239
