### ISSUE TITLE
how to set a custom font to text labels/legends/axis-legends/axis-names ?

### ISSUE THREAD

**Issue by siddharthkavthekar** [AAChartModel/AAChartKit-Swift#191]
Need a property disclosed for custom font for text labels/legends/axis-legends/axis-names!

**Comment by AAChartModel** [comment]
refer to the similar issue of Objective-C version AAChartKit

https://github.com/AAChartModel/AAChartKit/issues/526

**Comment by AAChartModel** [comment]
## The same issue in AAChartKit-Swift
how do i add an option like a customized legend to be a feature on the chart model #163


<img width="385" alt="截屏2020-02-20下午10 38 02" src="https://user-images.githubusercontent.com/16357599/74944878-acf3a200-5431-11ea-9f0e-1d7470aba121.png">

**Comment by AAChartModel** [comment]
The key code is 

```swift
aaOptions.legend!
        .itemMarginTop(20)
        .symbolRadius(10)//图标圆角
        .symbolHeight(20)//标志高度
        .symbolWidth(20)//图标宽度
        .align(.right)
        .layout(.vertical)
        .verticalAlign(.top)
        .itemStyle(AAItemStyle()
            .color(AAColor.red)
            .fontSize(20)
            .fontWeight(.bold))
```
