### ISSUE TITLE
iOS9.3系统上无法显示图表

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit-Swift#193]
大佬，我用的是最新的AAChartKit版本，为啥在iOS9.3系统上无法显示图表呢？，iOS13没问题

**Comment by AAChartModel** [comment]
控制台可有什么报错之类的信息吗?

**Comment by Maxcucurbit** [comment]
> 控制台可有什么报错之类的信息吗?

9.3点机器在别人手里，拿到手机我看一下

**Comment by Maxcucurbit** [comment]
@

> 控制台可有什么报错之类的信息吗?

大佬，报错信息来了

☠️☠️💀☠️☠️WARNING!!!!!!!!!!!!!!!!!!!! FBI WARNING !!!!!!!!!!!!!!!!!!!! WARNING☠️☠️💀☠️☠️
==========================================================================================
------------------------------------------------------------------------------------------
code = 4;
domain = WKErrorDomain;
userInfo =     {
NSLocalizedDescription = "A JavaScript exception occurred";
WKJavaScriptExceptionColumnNumber = ;
WKJavaScriptExceptionLineNumber = ;
WKJavaScriptExceptionMessage = ;
WKJavaScriptExceptionSourceURL = ;
------------------------------------------------------------------------------------------
==========================================================================================
☠️☠️💀☠️☠️WARNING!!!!!!!!!!!!!!!!!!!! FBI WARNING !!!!!!!!!!!!!!!!!!!! WARNING☠️☠️💀☠️☠️

**Comment by AAChartModel** [comment]
你可以试试 Objective-C 语言版本的 AAChartKit 是否能够在 iOS 9.3 上运行,如果可以的话,有可能是 AAChartKit 所依赖HighCharts版本不同导致的, Swift 版本上的 HighCharts 版本是最新的 8.0.4,所以有可能有 bug

**Comment by Maxcucurbit** [comment]
> 你可以试试 Objective-C 语言版本的 AAChartKit 是否能够在 iOS 9.3 上运行.
> 
> 如果Objective-C 语言版本的 AAChartKit可以正常显示的话,那么则有可能是 AAChartKit 所依赖HighCharts版本不同导致的此问题,.
> 
> Swift 语言版本的AAChartKit所依赖的 HighCharts 版本是最新的 8.0.4, 所以有可能有 bug

OC版本的Demo确实可以在iOS9.3上正常显示，大佬可否更新一下Swift版本来解决这个问题呢
![31586316868_ pic](https://user-images.githubusercontent.com/11735014/78741807-ec982e00-798c-11ea-91a9-34a93c57afd1.jpg)

**Comment by AAChartModel** [comment]
你把

```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
```

改成

```ruby
pod 'AAInfographics', 
```
重新`pod install`安装一下试试.


这样一来的话,就是用的是较旧版本的 AAChartKit-Swift. 两者的区别就是所依赖的版本,第二种方法所依赖的版本更旧一点,应该就没有这个新版的 highCharts 的 bug 了.

**Comment by AAChartModel** [comment]
问题有可能就是在这次合并中引入的 https://github.com/AAChartModel/AAChartKit-Swift/pull/192

**Comment by Maxcucurbit** [comment]
> 你把
> 
> ```ruby
> pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
> ```
> 
> 改成
> 
> ```ruby
> pod 'AAInfographics', 
> ```
> 
> 重新`pod install`安装一下试试.
> 
> 这样一来的话,就是用的是较旧版本的 AAChartKit-Swift. 两者的区别就是所依赖的版本,第二种方法所依赖的版本更旧一点,应该就没有这个新版的 highCharts 的 bug 了.

用旧版本确实可以了，但是还请大佬更新下最新的版本，新版本用起来效率更高
