### ISSUE TITLE
你好,请问Y轴的俩条线之间的间距大小可以调整吗？

### ISSUE THREAD

**Issue by wubangshun** [AAChartModel/AAChartKit-Swift#195]
找不到可以调整俩条线之间间距的大小属性
![1585216981669](https://user-images.githubusercontent.com/11895372/77634859-a2767c00-6f8c-11ea-8ada-73bb63b0be34.jpg)

**Comment by AAChartModel** [comment]
可以通过调整 AAYAxis 的 `tickPositions`属性来间接调整网格线之间的间距.

具体使用说明,参见 https://api.highcharts.com.cn/highcharts#yAxis.tickPositions
