### ISSUE TITLE
设置 gridLineDashStyle(.dash) 没有效果

### ISSUE THREAD

**Issue by mg459046365** [AAChartModel/AAChartKit-Swift#200]
aaOptions.yAxis?.labels(aaYAxisLabels).tickWidth(0).lineWidth(0).tickPositions([0, 8, 16, 24, 32, 40]).gridLineWidth(1).gridLineDashStyle(.dash).gridLineColor(AAColor.rgbaColor(0, 0, 0, 0.08))
没有效果，还是直线而不是虚线

**Comment by AAChartModel** [comment]
此问题已在此次提交 https://github.com/AAChartModel/AAChartKit-Swift/commit/175eab0a66f6124eb437a01dc79a4669b326c4e4 中解决, 使用

```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
```

更新 `AAChartKit-Swift` 至最新代码即可
