### ISSUE TITLE
可以考虑支持饼状图啊，这个也很常见

### ISSUE THREAD

**Issue by caitaicheng** [AAChartModel/AAChartKit-Swift#202]

**Comment by AAChartModel** [comment]
支持的啊老铁,参见 README 文档中的这幅图片

![](https://raw.githubusercontent.com/AAChartModel/loadHtmlCssJsDemo-master/master/AAInfographics/PieChart.png)

饼图,扇形图,圆环图其实都是AAChartKit-Swift 中的  `AAChartType.pie` 类型
