### ISSUE TITLE
y轴网格分割线改成虚线

### ISSUE THREAD

**Issue by ismilesky** [AAChartModel/AAChartKit-Swift#206]
大佬，问一下，怎么将y轴网格分割线改成虚线，需要从哪设置

**Comment by AAChartModel** [comment]
## 配置 AAOptions

```swift
    private func customAxesGridLineStyle() -> AAOptions  {
        let aaChartModel = AAChartModel()
            .chartType(.line)//图表类型
            .title("custom Axes Grid Line Style")//图表主标题
            .markerSymbolStyle(.borderBlank)
            .categories(["Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])
            .markerRadius(8)
            .series([
                AASeriesElement()
                    .name("2020")
                    .lineWidth(5.5)
                    .color(AAGradientColor.sanguine)
                    .data([7.0, 6.9, 2.5, 14.5, 18.2, 21.5, 5.2, 26.5, 23.3, 45.3, 13.9, 9.6])
                
                ])
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
    
        aaOptions.yAxis?
            .opposite(true)
            .gridLineDashStyle(.shortDashDot)
            .gridLineWidth(3)
            .gridLineColor(AAColor.lightGray)
        
        aaOptions.xAxis?
        .gridLineDashStyle(.shortDashDotDot)
        .gridLineWidth(3)
        .gridLineColor(AAColor.gray)
        
        return aaOptions
    }
```

## 绘图结果

### 横屏效果
![image](https://user-images.githubusercontent.com/16357599/81377450-14b7b000-9138-11ea-9595-e0ba68ea9175.png)

### 竖屏效果
![image](https://user-images.githubusercontent.com/16357599/81377476-1ed9ae80-9138-11ea-8f62-017dc9b9fefb.png)

**Comment by AAChartModel** [comment]
`gridLineDashStyle `支持 11 种虚线类型效果

```swift
public enum AAChartLineDashStyleType: String {
    case solid
    case shortDash
    case shortDot
    case shortDashDot
    case shortDashDotDot
    case dot
    case dash
    case longDash
    case dashDot
    case longDashDot
    case longDashDotDot
}
```

以下是其中几种类型的示例效果图
![image](https://user-images.githubusercontent.com/16357599/81377843-dc64a180-9138-11ea-9c8b-8c34bdcecbdb.png)

**Comment by ismilesky** [comment]
好的，谢谢大佬。 知道怎么用了。

**Comment by kiarashvosough1999** [comment]
Hello
how can I make x axis grid lines to be orthogonal to month lables?

**Comment by AAChartModel** [comment]
> Hello how can I make x axis grid lines to be orthogonal to month lables?

Refer to the same issue of Objective-C version AAChartKit

* https://github.com/AAChartModel/AAChartKit/issues/301


You can find the same property (`pointPlacement`) and property setter function in AASeriesElement file of AAChartKit-Swift

```swift

 public class AASeriesElement: AAObject {

...
...
    public var pointPlacement: Any?
...
...

    @discardableResult
    public func pointPlacement(_ prop: Any) -> AASeriesElement {
        pointPlacement = prop
        return self
    }
...
...
}
```

**Comment by zanyfly** [comment]
@AAChartModel  How can I use the result of    `private func customAxesGridLineStyle() -> AAOptions ` to change  the grid line color
I used it below, but it doesn't work
       ` aaChartView.aa_updateChart(options: aaOptions, redraw: false)`
