### ISSUE TITLE
雷达图设置categories后图形反转

### ISSUE THREAD

**Issue by lumianie** [AAChartModel/AAChartKit-Swift#213]
视觉稿如图
![image](https://user-images.githubusercontent.com/15768042/83486233-5ccdb680-a4db-11ea-9a2a-ecf0dd6333d5.png)
只需要三个坐标轴，添加categories后雷达图形发生反转，如图
![IMG_F95505399DAF-1](https://user-images.githubusercontent.com/15768042/83486317-8850a100-a4db-11ea-8395-3ac61cd8fe1a.jpeg)

**Comment by AAChartModel** [comment]
请粘贴一下你的 AAOptions 或者 AAChartModel 配置代码(不要截图)

**Comment by lumianie** [comment]
你好
`lazy var chartModel = { () -> AAChartModel in
        return AAChartModel()
            .title("")
            .colorsTheme(["#5BCCC8"])
            .chartType(.area)
            .dataLabelsEnabled(false)
            .xAxisVisible(true)
            .yAxisVisible(true)
            .yAxisLabelsEnabled(false)
            .polar(true)
            .markerRadius(8)
            .markerSymbol(.circle)
            .markerSymbolStyle(.borderBlank)
            .legendEnabled(false)
            .touchEventEnabled(false)
            .categories(["", "", ""])
            .series(
                [AASeriesElement()
                    .data([86, 90, 65])
                    .fillColor(gradientColorDic)]
            )
    }()`
`let operation = AAOptionsConstructor.configureChartOptions(chartModel)
        operation.yAxis?.tickPositions = [0, 25, 50, 75, 100]
        operation.yAxis?.gridLineColor = "#DDDDDD"
        operation.yAxis?.gridLineWidth = 1.0
        operation.yAxis?.gridLineDashStyle(.dash)
        operation.xAxis?.lineColor = "#5BCCC8"
        operation.xAxis?.lineWidth = 0
        chartView.aa_drawChartWithChartOptions(operation)`

**Comment by lumianie** [comment]
@AAChartModel

**Comment by AAChartModel** [comment]
配置 AAOptions

```swift
  private func customRadarChartStyle() -> AAOptions {
        let aaChartModel = AAChartModel()
            .title("")
            .colorsTheme(["#5BCCC8"])
            .chartType(.area)
            .dataLabelsEnabled(false)
            .xAxisVisible(true)
            .yAxisVisible(true)
            .yAxisLabelsEnabled(false)
            .polar(true)
            .markerRadius(8)
            .markerSymbol(.circle)
            .markerSymbolStyle(.borderBlank)
            .legendEnabled(false)
            .touchEventEnabled(false)
            .categories(["智力感", "距离感", "成熟感"])
            .series([
                AASeriesElement()
                    .data([86, 90, 65])
                    .pointPlacement("on")
            ])
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
        
        aaOptions.yAxis?
            .tickPositions([0, 25, 50, 75, 100])
            .gridLineColor("#DDDDDD")
            .gridLineWidth(1.0)
            .gridLineDashStyle(.dash)
        
        aaOptions.xAxis?
            .lineColor("#5BCCC8")
            .lineWidth(0.5)
        
        return aaOptions
    }
```

## 图表结果图
![image](https://user-images.githubusercontent.com/16357599/83491055-b33ef300-a4e3-11ea-81e6-566cdbe09aba.png)

**Comment by AAChartModel** [comment]
参考 Objective-C 版本 AAChartKit 相同问题 https://github.com/AAChartModel/AAChartKit/issues/301

综上, 解决此问题的关键语句是 

```swift
.pointPlacement("on")
```

**Comment by AAChartModel** [comment]
补充说明:

使用

```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
```

更新 AAChartKit-Swift 至最新内容方可使用 `pointPlacement ` 属性.

**Comment by AAChartModel** [comment]
`pointPlacement`官方文档参考链接地址: https://api.highcharts.com.cn/highcharts#plotOptions.area.pointPlacement

**Comment by lumianie** [comment]
> `pointPlacement`官方文档参考链接地址: https://api.highcharts.com.cn/highcharts#plotOptions.area.pointPlacement

你好，请问如何调整实现三角形的三个点对应三根等分线？或者说等分圆形，不需要连线？

**Comment by AAChartModel** [comment]
配置 AAOptions

```swift
 private func customRadarChartStyle() -> AAOptions {
        let aaChartModel = AAChartModel()
            .title("")
            .colorsTheme(["#5BCCC8"])
            .chartType(.area)
            .dataLabelsEnabled(false)
            .xAxisVisible(true)
            .yAxisVisible(true)
            .yAxisLabelsEnabled(false)
            .polar(true)
            .markerRadius(8)
            .markerSymbol(.circle)
            .markerSymbolStyle(.borderBlank)
            .legendEnabled(false)
            .touchEventEnabled(false)
            .series([
                AASeriesElement()
                    .data([86, 90, 65])
            ])
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
        
        let categories = ["智力感", "距离感", "成熟感"]
        let categoryJSArrStr = javaScriptArrayStringWithSwiftArray(categories)

        let xAxisLabelsFormatter = """
        function () {
        return \(categoryJSArrStr)[this.value];
        }
        """
        
        aaOptions.yAxis?
            .tickPositions([0, 25, 50, 75, 100])
            .gridLineColor("#DDDDDD")
            .gridLineWidth(2.0)
            .gridLineDashStyle(.dash)
        
        aaOptions.xAxis?
            .lineColor("#5BCCC8")
            .lineWidth(5)
            .gridLineColor(AAColor.red)
            .gridLineWidth(3)
            .gridLineDashStyle(.longDashDotDot)
            .tickPositions([0,1,2,0])
        
        aaOptions.xAxis?.labels?
            
        .formatter(xAxisLabelsFormatter)
        
        return aaOptions
    }
    
    //Convert Swift array to be JavaScript array
    private func javaScriptArrayStringWithSwiftArray(_ swiftArray: [Any]) -> String {
        var originalJsArrStr = ""
        for element in swiftArray {
            originalJsArrStr = originalJsArrStr + "'\(element)',"
        }
        
        let finalJSArrStr = "[\(originalJsArrStr)]"
        return finalJSArrStr
    }
```

## 图形结果
![image](https://user-images.githubusercontent.com/16357599/83504456-1dad5e80-a4f7-11ea-89fa-179d236f7573.png)

**Comment by AAChartModel** [comment]
补充说明:

使用

```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
```

更新 AAChartKit-Swift 至最新内容方可使用X轴的 `tickPositions ` 属性.
