### ISSUE TITLE
How to implement chart race with bar chart

### ISSUE THREAD

**Issue by tringkishorekumar** [AAChartModel/AAChartKit-Swift#215]
I would like to implement chart race where data change timeline.  Just like this below
https://www.youtube.com/watch?v=TWSm_5RU7cQ

**Comment by AAChartModel** [comment]
Support data sorting chart with animation effect now.  

![image](https://user-images.githubusercontent.com/16357599/85923645-66babd80-b8bf-11ea-9fa8-fc38de1814cc.png)

**Comment by AAChartModel** [comment]
```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'

```

update AAChartKit-Swift to the latest cocoapods content .

you can see the  AAChartKit-Swift demo code in `DataSortingWithAnimationChartVC` to get more usage details
