### ISSUE TITLE
Personalize thick interval for Y axis

### ISSUE THREAD

**Issue by mrvallejo** [AAChartModel/AAChartKit-Swift#219]
This is one of the limitations that I have found in this excellent library. The Y axis steps change according to the size of the plot and I would like to maintain always the same Y axis steps. I have found possible with Int numbers but not with decimals. Could it be possible to assign limits and steps to always maintain the same scale?

This is the best approach I found but not possible for decimals.

```swift
 let aaYAxis = AAYAxis()
            .min(-0.1)
            .max(1.1)
            .tickInterval(0.1) // Not possible, only for Int numbers
            .labels(AALabels()
                .format("{value:.1f}")
)
```

Thanks!

**Comment by AAChartModel** [comment]
```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
```

Update AAChartKit-Swift to the latest content

**Comment by mrvallejo** [comment]
Thanks!
