### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by shenxiang11** [AAChartModel/AAChartKit-Swift#222]
```
The platform of the target `xxx` (macOS 10.10) is not compatible with `AAInfographics (4.0.0)`, which does not support `macOS`.
```

**Comment by AAChartModel** [comment]
<img width="338" alt="截屏2020-06-29 下午4 40 13" src="https://user-images.githubusercontent.com/16357599/85992240-2a09d600-ba27-11ea-8ed4-8de80b4eea00.png">


AAChartKit-Swift 支持通过 catalyst 在 macOS 中运行.
