### ISSUE TITLE
'AAStates', 'AASelect', 'AAHover', 'AAHalo' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by nereita9** [AAChartModel/AAChartKit-Swift#224]
Hello,

I'm using your library with CocoaPods and when I want to use AAStates (same with AASelect, AAHover or AAHalo) Xcode saids:

"AAStates initializer is inaccessible due to 'internal' protection level"

AAStates, AASelect, AAHover and AAHalo classes needs

public override init() { }

in order to be accessible using CocoaPods
Thanks!

**Comment by AAChartModel** [comment]
It was fixed now.  

pod run 
```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'

```

to get the latest content of AAChartKit-Swift and then your problem will be resolved.🙂
