### ISSUE TITLE
如何将Y轴移到左边 如何固定y轴坐标

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit-Swift#225]
Y轴左边现在会根据数据自动变化，能否固定

**Comment by AAChartModel** [comment]
> 如何将Y轴移到左边

    public var opposite: Bool? // Whether to display the coordinate axis on the opposite surface. By default, the x axis is displayed below the chart, the y axis is on the left, the coordinate axis is displayed on the opposite surface, and the x axis is displayed on the top. The axis is displayed on the right (that is, the coordinate axis is displayed on the opposite side). This configuration is generally used for multi-axis display, and in Highstock, the y-axis is displayed on the opposite side by default. The default is: false.

**Comment by AAChartModel** [comment]
> 如何固定y轴坐标

```swift
    public var tickPositions: [Any]? // Custom Y-axis coordinates (eg: [0, 25, 50, 75, 100])

```
