### ISSUE TITLE
目前有没有办法建立两根Y轴一根左边一根右边

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit-Swift#226]
没有相关配置的话 如果改写代码应该从哪儿入手。

**Comment by lzz212** [comment]
以及 如何将说明颜色的那个东西换个位置
就是  一个色条  Tokyo/℃ 那个

**Comment by AAChartModel** [comment]
# 重复问题,参见以下相关 issue

Support double layers && even more layers pie chart 支持双重甚至更多重扇形图样式
#211 by AAChartModel was closed on May 24

Support Double Y Axes And Column Line Mixed Chart(双Y轴柱形曲线混合图)
#174 by AAChartModel was closed on Nov 2, 2019

Support double Y axes chart (支持双 Y 轴图表)
#170 by AAChartModel was closed on Oct 22, 2019

Support double X axes chart (支持双 X 轴图表)
#169 by AAChartModel was closed on Oct 10, 2019

**Comment by AAChartModel** [comment]
AAChartKit-Swift 甚至支持三重 Y 轴图表, 参见相关 issue https://github.com/AAChartModel/AAChartKit-Swift/issues/172
