### ISSUE TITLE
数据为0时线不紧贴X轴而是在中间

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit-Swift#229]
我使用的设置了.yAxisTickInterval(10) 没有设置Y轴的max和min，这样可以让其自适应坐标。
但是这样的话如果数据是0时，线就会漂浮在整个line chart中间 不是贴近x轴

请问如何优化

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/961
