### ISSUE TITLE
scrollPositionX 設定後，卻總是顯示在最末端

### ISSUE THREAD

**Issue by lucentpeng** [AAChartModel/AAChartKit-Swift#234]
您好～
我參考 ScrollableChartVC.swift
啟動了Scroll功能，但由於資料量較龐大，
我希望能Scroll到底時，更新資料，去模擬接著Scroll的效果
所以大概Scroll到第3頁時，我要更新資料為3，4，5頁
但是一旦aa_refreshChartWholeContentWithChartOptions 或 aa_drawChartWithChartOptions之後
新的資料雖然有顯示，但永遠顯示在最末頁，
即使我設了scrollPositionX(1), 也總是scroll 到X的最末端。
我用ScrollableChartVC 去實驗，想scroll 到X軸其他位置，似乎也無法達成
請問若要拿到目前的 scrollPosition 以及指定 scrollPosition 要如何達成？ 

非常感謝。Orz

**Comment by AAChartModel** [comment]
## 配置 AAOptions

```objc
    AAChartModel *aaChartModel =  AAChartModel.new
    .chartTypeSet([self configureChartType])//图表类型随机
    .xAxisVisibleSet(true)
    .yAxisTitleSet(@"摄氏度")
    .stackingSet(AAChartStackingTypeNormal)
    .scrollablePlotAreaSet(
        AAScrollablePlotArea.new
        .minWidthSet(@6000)
        .scrollPositionXSet(@0))
    .colorsThemeSet(@[
        gradientColorDic1,
        gradientColorDic2,
        AAGradientColor.sanguineColor,
        AAGradientColor.wroughtIronColor
    ])
    .seriesSet([self configureSeries])
    ;
```

## 图表效果

<img width="100%" alt="截屏2020-08-11 下午5 22 18" src="https://user-images.githubusercontent.com/16357599/89880779-37ee7180-dbf7-11ea-9d85-ba6522a5aca1.png">

**Comment by AAChartModel** [comment]
参见在线文档 https://api.highcharts.com.cn/en/highcharts/chart.scrollablePlotArea.scrollPositionX.html

也就是说 scrollPositionX 的取值范围在 0 到 1 之间
