### ISSUE TITLE
如何修改图例的位置和图标

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit-Swift#237]
<img width="231" alt="图例1" src="https://user-images.githubusercontent.com/12130673/90085524-caebf080-dd4a-11ea-941f-40d96096c998.png">

你好 我们项目要求的图例是这样的
但是我使用项目中的图例是在图标下方的一根横线，
<img width="514" alt="图例2" src="https://user-images.githubusercontent.com/12130673/90085616-fa9af880-dd4a-11ea-8d12-2c9d839ddaca.png">

我的配置是这样的
```swift
    let aaChartModel = AAChartModel()
    .chartType(.line)
    .colorsTheme(["#1e90ff"])//Colors theme
    .axesTextColor(AAColor.black)
    .title("")
    .dataLabelsEnabled(false)
    .tooltipValueSuffix("%")
    .animationType(.bounce)
    .backgroundColor("#FFFFFF")
    .touchEventEnabled(false)
    .markerRadius(0)
    .xAxisTickInterval(segmentedControl.selectedSegmentIndex == dayTabIndex ? 3 : 4)
    .categories(segmentedControl.selectedSegmentIndex == dayTabIndex ? dayTabCategories : monthTabCategories)
    .series([
             AASeriesElement()
             .name("百分比/%")
             .data(showData[bettryEnergyKey]!)
             ])
    .yAxisTickInterval(10)
    .yAxisOpposite(true)
```
不知道改怎么设置调整。

另外我们要求的tool如下
<img width="687" alt="tool2" src="https://user-images.githubusercontent.com/12130673/90085716-3d5cd080-dd4b-11ea-9655-3f973cd7b929.png">

请问这个好实现么

**Comment by AAChartModel** [comment]
> 另外我们要求的tool如下
> <img width="687" alt="tool2" src="https://user-images.githubusercontent.com/12130673/90085716-3d5cd080-dd4b-11ea-9655-3f973cd7b929.png">

> 请问这个好实现么


参考: https://github.com/AAChartModel/AAChartKit/issues/970

**Comment by AAChartModel** [comment]
> 如何修改图例的位置和图标 

参见: https://github.com/AAChartModel/AAChartKit/issues/828

**Comment by lzz212** [comment]
> > 另外我们要求的tool如下
> > <img alt="tool2" width="687" src="https://user-images.githubusercontent.com/12130673/90085716-3d5cd080-dd4b-11ea-9655-3f973cd7b929.png">
> 
> > 请问这个好实现么
> 
> ### 参考:
> **[AAChartModel/AAChartKit#970](https://github.com/AAChartModel/AAChartKit/issues/970)**
> 
> 我的这个`Objective-C`语言版本的 AAChartKit 中的示例仍旧不是完整示例,请等待本人至周末加上此示例.

嗯  我相同的formatter放到了swift里就不行了，连图标都绘制不出来了。

**Comment by AAChartModel** [comment]
> 嗯 我相同的formatter放到了swift里就不行了，连图标都绘制不出来了。



参见 Swift 语言版本的示例

https://github.com/AAChartModel/AAChartKit-Swift/issues/239
