### ISSUE TITLE
AALegend展示异常

### ISSUE THREAD

**Issue by andy123234** [AAChartModel/AAChartKit-Swift#241]
设置Legend字体颜色为白色后，点击Legend除了选中的白色和未选中的灰色，时不时文字会出现黑色状态。之前使用OC版本未发现此问题
<img width="134" alt="截屏2020-08-21 上午10 34 43" src="https://user-images.githubusercontent.com/15189830/90846088-0bc2b580-e39a-11ea-94b4-f603224e7308.png">
<img width="139" alt="截屏2020-08-21 上午10 34 52" src="https://user-images.githubusercontent.com/15189830/90846091-0e250f80-e39a-11ea-88f0-a006152c5186.png">
<img width="136" alt="截屏2020-08-21 上午10 35 01" src="https://user-images.githubusercontent.com/15189830/90846096-0feed300-e39a-11ea-85be-0280aef93e33.png">

**Comment by AAChartModel** [comment]
这个估计是 Highcharts 的一个 bug, 可以考虑禁用图例的点击事件来规避此问题

```swift
     //禁用图例点击事件
        aaOptions.plotOptions?.series?.events = AAEvents()
            .legendItemClick(#"""
                        function() {
                          return false;
                        }
            """#)
```
