### ISSUE TITLE
Bubble Chart Bug

### ISSUE THREAD

**Issue by cminero10** [AAChartModel/AAChartKit-Swift#242]
Hello,

I found that when the range of bubble sizes is to dense, the bubbles does not render properly (size 50 and 51 but significant size gap):

![image](https://user-images.githubusercontent.com/28816567/90864929-d17ff680-e34e-11ea-952e-6bf7b4cf6723.png)

![image](https://user-images.githubusercontent.com/28816567/90864957-e066a900-e34e-11ea-8996-14fba6a1ce8d.png)

I thought was my problem but I found out that in the demo app happens the same.

Could you shed any light on this? Thanks in advance!

**Comment by AAChartModel** [comment]
Can you post your bubble chart data ?

**Comment by AAChartModel** [comment]
## Configure AAOptions

```swift
    private func adjustBubbleChartMinAndMax() -> AAOptions {
        let aaChartModel = AAChartModel()
            .chartType(.bubble)
            .title("AACHARTKIT BUBBLES")
            .subtitle("JUST FOR FUN")
            .yAxisTitle("℃")
            .yAxisGridLineWidth(0)
            .colorsTheme(["#0c9674","#7dffc0","#d11b5f","#facd32","#ffffa0","#EA007B"])
            .series([
                AASeriesElement()
                    .name("BubbleOne")
                    .data([
                        [97, 36, 50],
                        [94, 74, 50],
                        [68, 76, 50],
                        [64, 87, 50],
                        [68, 27, 49],
                        [74, 99, 51],
                        [71, 93, 55],
                        [51, 69, 60],
                        [38, 23, 50],
                        [57, 86, 50],
                        [33, 24, 51]
                    ])
                ]
        )
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
        
        aaOptions.plotOptions?
            .bubble(AABubble()
                .minSize(0)
                .maxSize(100)
                .zMin(0)
                .zMax(100))
        
        return aaOptions
    }
```

## The Final Bubble Chart
![image](https://user-images.githubusercontent.com/16357599/91010996-14bfbb00-e616-11ea-8336-d2d79508e3fc.png)

**Comment by AAChartModel** [comment]
Refer to Created By: Torstein Hønsi, Source: https://github.com/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/bubble-zmin-zmax/

**Comment by AAChartModel** [comment]
Refer to online API doc:
maxSize && minSize
* https://api.highcharts.com/highcharts/plotOptions.bubble.maxSize
* https://api.highcharts.com/highcharts/plotOptions.bubble.minSize

zMax && zMin
* https://api.highcharts.com/highcharts/plotOptions.bubble.zMax
* https://api.highcharts.com/highcharts/plotOptions.bubble.zMin

**Comment by AAChartModel** [comment]
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/bubble-zmin-zmax/

**Comment by AAChartModel** [comment]
```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'

```

Update the AAChartKit-Swift to the latest content and then you can use the code as follow 

```swift
        aaOptions.plotOptions?
            .bubble(AABubble()
                .minSize(0)
                .maxSize(100)
                .zMin(0)
                .zMax(100))
```

**Comment by cminero10** [comment]
Thank you very much!!
