### ISSUE TITLE
点击数据点产生的那条线怎么配置？

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit-Swift#248]
我感觉设置了category以后就不会出现一条线，而是一根柱子一样的东西，如何进行配置

**Comment by AAChartModel** [comment]
AACrosshair  准星线

**Comment by lzz212** [comment]
谢谢

想问下准星线接触折线时的那个圆点可以配置么
<img width="94" alt="星准" src="https://user-images.githubusercontent.com/12130673/92221889-bbd30b00-eed0-11ea-8cb7-8c7369b6d021.png">

**Comment by AAChartModel** [comment]
可以,这个是 AAMarker
