### ISSUE TITLE
请问下toolTip浮动提示框如何配置位置

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit-Swift#250]
想要修改为这个toolTip在准星线上方一定距离

**Comment by AAChartModel** [comment]
参见相同问题 https://github.com/AAChartModel/AAChartKit/issues/966

**Comment by AAChartModel** [comment]
![](https://user-images.githubusercontent.com/16357599/89763108-69e2d380-db24-11ea-8564-f5b6e5c533de.png)

想要实现如上的效果, Swift 版本的配置代码如下

```swift
 private func customTooltipPostionerFunction() -> AAOptions {
        let categories = [
            "孤岛危机",
            "使命召唤",
            "荣誉勋章",
            "狙击精英",
            "神秘海域",
            "最后生还者",
            "巫师3狂猎",
            "对马之魂",
            "死亡搁浅",
            "地狱边境",
            "闪客",
            "忍者之印"
        ]
        
        let aaChartModel = AAChartModel()
            .chartType(.column)
            .yAxisTitle("")
            .yAxisGridLineWidth(0)
            .categories(categories)
            .series([
                AASeriesElement()
                    .name("单机大作")
                    .color(AAColor.red)
                    .data([0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5])])
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
        
        aaOptions.tooltip?
            .shadow(false)
            .positioner("""
            function (labelWidth, labelHeight, point) {
                return {
                 x : point.plotX,
                 y : 20
                };
            }
            """)
        
        return aaOptions
    }
    
```

**Comment by AAChartModel** [comment]
AAChartKit-Swift 的 demo 中有此示例,详细内容见 demo

**Comment by AAChartModel** [comment]
想要完全固定 AATooltip 的位置,如下设置 `positioner`即可


```swift
        aaOptions.tooltip?
            .positioner("""
            function (labelWidth, labelHeight, point) {
                return {
                 x : 50,
                 y : 50
                };
            }
            """)
```

**Comment by lzz212** [comment]
好的 我去试试   谢谢

**Comment by lzz212** [comment]
`let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
            let aaCrosshair = AACrosshair()
                .dashStyle(.solid)
                .color("#CCCCCC")
                .width(2)
            aaOptions.xAxis?.crosshair(aaCrosshair)
            aaOptions.tooltip?
                .shadow(false)
                .positioner("""
                function (labelWidth, labelHeight, point) {
                    return {
                     x : point.plotX,
                     y : 20
                    };
                }
                """)`
你好我是这么设置的，想要有一根准星线，有一个toolTip，且toolTip在准星线上。
按照出现的效果是，tooltip一直在左上角，准星线不出现。

**Comment by lzz212** [comment]
let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
            let aaCrosshair = AACrosshair()
                .dashStyle(.solid)
                .color("#CCCCCC")
                .width(2)
            aaOptions.xAxis?.crosshair(aaCrosshair)
            aaOptions.tooltip?
                .shadow(false)
                .positioner("""
                function (labelWidth, labelHeight, point) {
                    return {
                     x : point.plotX,
                     y : 20
                    };
                }
                """)

**Comment by lzz212** [comment]
demo里的是可以的   可能是哪儿没有更新么？

**Comment by lzz212** [comment]
好了  应该是我没更新导致的

**Comment by lzz212** [comment]
![IMG_1064](https://user-images.githubusercontent.com/12130673/92340063-8d7d4780-f0eb-11ea-8507-e954ba902b37.PNG)
你好  还有这个问题。。。 我想要这个toolTip在这个表格外出现 应该怎么设置

**Comment by AAChartModel** [comment]
试试把
1. Y轴的最大值`max`设置的大一点例如设置为 150,  
2. 然后把 Y轴的`tickPositions`数组中的元素的最大值设置的小一点,例如 `[0, 25, 50, 75, 100]`(元素最大值为100),
3. 这时候再把tooltip 的 position 设置的高一点应该就可以了
