### ISSUE TITLE
touch事件结束有没有回调

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit-Swift#251]
大佬

请问一下如果要touch事件结束的回调要如何完成。

我看现在点击图标会显示准星线，产生一个moveMessage的回调
点击chartView以外的区域 准星线会消失，但是没有产生回调

我再准星线消失的时候需要处理一些东西的话要怎么做

**Comment by AAChartModel** [comment]
* https://github.com/AAChartModel/AAChartKit-Swift/issues/356
