### ISSUE TITLE
toolTip右侧遮挡

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit-Swift#254]
你好  我的toolTip右侧有点遮挡 应该如何处理
![IMG_6282](https://user-images.githubusercontent.com/12130673/92551151-e7b70d80-f28f-11ea-8a0c-3a0bf99d13d1.PNG)

aaOptions.tooltip?
                .shadow(false)
                .positioner("""
                function (labelWidth, labelHeight, point) {
                    return {
                     x : point.plotX,
                     y : 0
                    };
                }
                """)
这个是这样的，应该是这个plotX的问题吧   那如何进行调整比较好呢

**Comment by AAChartModel** [comment]
可以在 JavaScript 的函数里面做一些简单的条件判断,假设 data 中有十个元素, 等到用户点击最后一个元素的时候,改变 X轴的坐标值,例如

```js
function (labelWidth, labelHeight, point) {
    var xPosition = point.plotX;
    if (xPosition >= 10) {
        xPosition = 9;
    }
    
    return {
        x : xPosition,
        y : 0
    };
}
```

**Comment by lzz212** [comment]
data的个数不确定的话要如何处理

**Comment by AAChartModel** [comment]
那就根据 data 数组的个数,动态拼接 JavaScript 函数,代码示例如下


```js

private func customTooltipPostionerFunction() -> AAOptions {
        let categories = [
            "孤岛危机",
            "使命召唤",
            "荣誉勋章",
            "狙击精英",
            "神秘海域",
            "最后生还者",
            "巫师3狂猎",
            "对马之魂",
            "死亡搁浅",
            "地狱边境",
            "闪客",
            "忍者之印"
        ]
        
        let dataArr = [0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
        
        let aaChartModel = AAChartModel()
            .chartType(.column)
            .yAxisTitle("")
            .yAxisGridLineWidth(0)
            .categories(categories)
            .series([
                AASeriesElement()
                    .name("单机大作")
                    .color(AAColor.red)
                    .data(dataArr)])
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
        
        
        
        aaOptions.tooltip?
            .shadow(false)
            .positioner("""
            function (labelWidth, labelHeight, point) {
                var xPosition = point.plotX;
                if (xPosition >= \(dataArr.count)) {
                    xPosition = \(dataArr.count - 1);
                }
                
                return {
                    x : xPosition,
                    y : 0
                };
            }
            """)
        
        return aaOptions
    }
```

**Comment by lzz212** [comment]
感觉这样设了  在移动没几个点    这个toolTip就不会左右移动了

这个point.plotX是代表   x轴的点数还是x轴坐标呀， 我看api里没有写

**Comment by AAChartModel** [comment]
抱歉我搞错了, `plotX`貌似是坐标点

selected point series element name: 单机大作
👌👌👌WARNING!!!!!!!!!!!!!!!!!!!! Touch Event Message !!!!!!!!!!!!!!!!!!!! WARNING👌👌👌
|| ==========================================================================================
|| ------------------------------------------------------------------------------------------
|| user finger moved over!!!,get the move over event message: {
|| category = Optional("对马之魂")
|| index = Optional(7)
|| name = Optional("单机大作")
|| offset = Optional(["plotY": 68.49454545454546, "plotX": 223.75])
|| x = Optional(7.0)
|| y = Optional(24.1)
|| }
|| ------------------------------------------------------------------------------------------
|| ==========================================================================================

**Comment by AAChartModel** [comment]
所以我上面的👆的示例代码有问题,不过我现在比较忙,晚上回去再帮你弄吧,或者你自己也可以试试

**Comment by lzz212** [comment]
改好了

let cellWidth = UIScreen.main.bounds.width - 32

            aaOptions.tooltip?
                .shadow(false)
                .positioner("""
                function (labelWidth, labelHeight, point) {
                    var xPosition = point.plotX;
                    if (xPosition >= \(cellWidth - 150)) {
                        xPosition = \(cellWidth - 150)
                    }
                    return {
                     x : xPosition,
                     y : 0
                    };
                }
                """)

类似这样就好了

**Comment by AAChartModel** [comment]
## 🚀🚀🚀
