### ISSUE TITLE
可以设置y轴的坐标吗

### ISSUE THREAD

**Issue by ws1227** [AAChartModel/AAChartKit-Swift#256]
在oc版本里有yAxisTickPositions
在swift版本没找到

**Comment by AAChartModel** [comment]
AAChartModel 本质上还是只是一种配置图表内容的快捷简便的方式,真正能够完整配置图表内容的,AAChartKit-Swift 内部还是得要依靠 AAOptions, 所以如下配置,即可实现修改图表的 Y 轴的 tickPositions

```objc
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)

        aaOptions.yAxis.tickPositions
```

**Comment by ws1227** [comment]
多谢已经实现了

**Comment by ws1227** [comment]
对了 问下网格的宽度能固定吗

**Comment by AAChartModel** [comment]
你是所**网格线**的宽度,还是只**网格本身**的宽度? 如果你说的是**网格线**的宽度那很简单.  如果你说的是**网格本身**的宽度,那是不支持的.

**Comment by ws1227** [comment]
就是两条网格线之间的间距  不是线的宽度

**Comment by AAChartModel** [comment]
Highcharts 的网格线的相关文档在这里, https://api.highcharts.com.cn/highcharts#xAxis.gridLineColor

在这众多的网格线相关的API, 我暂未找到能够直接设置网格线的接口.

**Comment by AAChartModel** [comment]
其中原因,我猜测是因为 Highcharts 图表的网格是和 X 轴和 Y 轴的值的刻度深度绑定的, 所有无法自由设置网格宽度

**Comment by ws1227** [comment]
好的多谢
