### ISSUE TITLE
如何让折线图的点显示文本而不是数据

### ISSUE THREAD

**Issue by Cookie726** [AAChartModel/AAChartKit-Swift#260]
如何让这里面的点显示label而不是数值

<img width="266" alt="image" src="https://user-images.githubusercontent.com/49552033/95292826-da983900-08a4-11eb-98f0-a24b56a7c115.png">

这是我的数据样例

<img width="324" alt="image" src="https://user-images.githubusercontent.com/49552033/95292913-03b8c980-08a5-11eb-8059-2296f37b9bed.png">

也就是折线图中的点显示的是"测试1"、“测试2”、“这些”

**Comment by AAChartModel** [comment]
原 JavaScript 中配置 Highcharts 的 options 对象

```js
Highcharts.chart('container', {
	xAxis: {
		categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	},
	plotOptions: {
		series: {
			dataLabels: {
				enabled: true,
				format: '{point.name}'
			}
		}
	},
	series: [{
		data: [["测试 1", 100],["测试 2", 130],["测试 3", 120],]
	}]
});
```


<img width="100%" alt="截屏2020-10-07 下午6 56 23" src="https://user-images.githubusercontent.com/16357599/95322272-d1bc5d00-08ce-11eb-842e-c7a542572ab0.png">

**Comment by AAChartModel** [comment]
Highcharts 在线编辑器:   https://jshare.com.cn/github/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-datalabels-format/

将上述代码粘贴至此编辑器中,可运行查看效果

**Comment by AAChartModel** [comment]
参考 DataLabels 的属性

* format:  https://api.highcharts.com.cn/highcharts#plotOptions.line.dataLabels.format

* formatter: https://api.highcharts.com.cn/highcharts#plotOptions.line.dataLabels.formatter

**Comment by AAChartModel** [comment]
在 AAChartKit-Swift 则是如下配置:

### 配置 AAOptions

```swift
    private func customLineChartDataLabelsFormat() -> AAOptions {
        let aaChartModel = AAChartModel()
            .dataLabelsEnabled(true)
            .series([
                AASeriesElement()
                    .data([
                        ["测试 1", 100],
                        ["测试 2", 130],
                        ["测试 3", 120],
                    ])
            ])
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
        aaOptions.plotOptions?.series?.dataLabels?
            .format("{point.name}")
        
        return aaOptions
    }
```

## 绘图结果

![image](https://user-images.githubusercontent.com/16357599/95324096-c61e6580-08d1-11eb-96b9-18557dcc2469.png)

**Comment by AAChartModel** [comment]
### 更简洁的配置方法


## 配置 AAOptions

```swift
    private func customLineChartDataLabelsFormat2() -> AAOptions {
        let aaChartModel = AAChartModel()
            .dataLabelsEnabled(true)
            .categories(["测试 1", "测试 2", "测试 3", ])
            .series([
                AASeriesElement()
                    .data([100, 130, 120])
            ])
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
        aaOptions.plotOptions?.series?.dataLabels?
            .format("{x}")
        
        return aaOptions
    }
```
## 图表结果

![](https://user-images.githubusercontent.com/16357599/95324096-c61e6580-08d1-11eb-96b9-18557dcc2469.png)
