### ISSUE TITLE
View Gets Destroyed 

### ISSUE THREAD

**Issue by grisvladko** [AAChartModel/AAChartKit-Swift#266]
Hey, i started using this library and at first step couldn't make it happen, the issue is that i add the chart to a view, and that view is added to a collectionViewCell. i initialize exactly as on the example, but then it writes the the view was destroyed, and shows some ghosts atound, although im not afraid of the ghosts i am very much trying to understand where did i go wrong, here is my code . the view does show in the end after a few seconds but it just looks weird

```
let chartView = AAChartView(frame: self.frame)
        chartView.contentHeight = self.frame.height
        chartView.translatesAutoresizingMaskIntoConstraints = false
        self.addSubview(chartView)
        pinView(chartView, to: self)
  
        
        let chartModel = AAChartModel()
            .chartType(.column)
            .animationType(.bounce)
            .title("title")
            .dataLabelsEnabled(false)
            .tooltipValueSuffix("USD")
            .categories(["gg","das","ggg","ddd"])
            .colorsTheme(["#fe117c","#ffc069"])
            .series([
            AASeriesElement()
                .name("Boom")
                .data([7.0,1.0,3.4]),
            AASeriesElement()
                .name("MEOW")
                .data([5.4,5.5,4.2,1.2])
        ])
        
        
        chartView.aa_drawChartWithChartModel(chartModel)
```

**Comment by AAChartModel** [comment]
AAChartView is inherited from WKWebView, it is a little slow on the simulator, You can test it on the real iOS device.
