### ISSUE TITLE
yAxis Categories Problem

### ISSUE THREAD

**Issue by mkeshnoda** [AAChartModel/AAChartKit-Swift#267]
```
let yAxis = AAYAxis()
yAxis.visible = true
yAxis.gridLineDashStyle = "shortDash"
yAxis.gridLineColor = "#8F98C1"
yAxis.categories = ["%0", "%25", "%50", "%75", "%90"]
yAxis.offset = 5
 aaOption?.yAxis = yAxis
```

`yAxis.categories = ["%0", "%25", "%50", "%75", "%90"]`
My Categories are **_%0, %25, %50, %75, %90_** but what i get is: 
![Screen Shot 2020-11-01 at 22 23 44](https://user-images.githubusercontent.com/25078625/97812241-1ef2db00-1c91-11eb-87d2-0a48f177417c.png)

Any ideas on how to fix it?

**Comment by AAChartModel** [comment]
aaOptions.yAxis.labels.format = @"{value} %";//Add units to the y axis
