### ISSUE TITLE
Invalid redeclaration of 'BundlePathLoader'

### ISSUE THREAD

**Issue by Dacover** [AAChartModel/AAChartKit-Swift#278]
PackageBundlePathLoader、ProjectBundlePathLoader里有同一个class BundlePathLoader

**Comment by Dacover** [comment]
![image](https://user-images.githubusercontent.com/16042302/102565827-3428a980-4119-11eb-9a13-07d9fbd8895a.png)

**Comment by AAChartModel** [comment]
你先通过制定 AAChartKit-Swift 的 pods 版本为 5.0.3 试试吧

**Comment by alex851209** [comment]
@AAChartModel 
遇到同樣問題，原本使用都沒問題，今天下pod update就開不起來了

**Comment by CodeOceanJava** [comment]
同样遇到该问题。

**Comment by woodjobber** [comment]
遇到同样的问题，希望尽快解决，版本5.0.3缺少一些属性。Bundle.moudle。其中moudle找不到。

**Comment by woodjobber** [comment]
临时解决方式：移出 PackageBundlePathLoader.swift。估计作者是考虑SPM情况

**Comment by AAChartModel** [comment]
现在再使用 pod

```ruby
  pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'

```

导入最新的 AAInfographics 内容已经可以了.

**Comment by AAChartModel** [comment]
在此次提交 https://github.com/AAChartModel/AAChartKit-Swift/commit/d251286524277c064a6481acf67f05db0708237c 中,问题已被解决.

主要起作用的代码

```ruby
    s.exclude_files = 'AAInfographics/**/PackageBundlePathLoader.swift'  #在 pods 导入时忽略PackageBundlePathLoader.swift文件
```
