### ISSUE TITLE
x轴y轴的字体大小能自己设置吗？

### ISSUE THREAD

**Issue by ssbaochiweixiao** [AAChartModel/AAChartKit-Swift#285]
x轴y轴的字体大小能自己设置吗？

**Comment by ssbaochiweixiao** [comment]
AAHighchartsLib.js中的下边的11px改成24px  x轴y轴文字变大，请问在外边的属性中有直接定义的吗？


month:{main:"%b '%y"},year:{main:"%Y"}},endOnTick:!1,labels:{enabled:!0,indentation:10,x:0,style:{color:"#666666",cursor:"default",fontSize:"24px"}},maxPadding:.01,minorTickLength:2,minorTickPosition:"outside",minPadding:.01,showEmpty:!0,startOfWeek:1,startOnTick:!1,tickLength:10,tickPixelInterval:100,tickmarkPlacement:"between",tickPosition:"outside",title:{align:"middle",style:{color:"#666666"}},type:"linear",minorGridLineColor:"#f2f2f2",minorGridLineWidth:1,minorTickColor:"#999999",lineColor:"#ccd6eb",
lineWidth:1,gridLineColor:"#e6e6e6",tickColor:"#ccd6eb"},defaultYAxisOptions:{endOnTick:!0,maxPadding:.05,minPadding:.05,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8},startOnTick:!0,title:{rotation:270,text:"Values"},stackLabels:{allowOverlap:!1,enabled:!1,crop:!0,overflow:"justify",formatter:function(){var a=this.axis.chart.numberFormatter;return a(this.total,-1)},style:{color:"#000000",fontSize:"11px",fontWeight:"bold",textOutline:"1px contrast"}},gridLineWidth:1,lineWidth:0},defaultLeftAxisOptions:{labels:{x:-15},

**Comment by AAChartModel** [comment]
修改 X 轴字体 颜色, 大小, 粗细

```swift
        aaOptions.xAxis?.labels?.style?
            .color(AAColor.red)
            .fontSize(18)
            .fontWeight(.bold)
```

修改 Y 轴同理
