### ISSUE TITLE
How to close the console log?

### ISSUE THREAD

**Issue by pfcstyle** [AAChartModel/AAChartKit-Swift#288]
Is there a flag to control the log whether open?

```
-----------🖨🖨🖨 console log AAOptions JSON information of AAChartView 🖨🖨🖨-----------:
{
  "legend" : {
    "itemStyle" : {

    },
    "enabled" : false
  },
...
}
```
The log is very useful when we meet some problems, but it's a little annoying when normal. It's too long.

Thanks for any answers

**Comment by AAChartModel** [comment]
```swift
        #if DEBUG
        let modelJsonDic = aaOptions.toDic()!
        let data = try? JSONSerialization.data(withJSONObject: modelJsonDic, options: .prettyPrinted)
        if data != nil {
            let prettyPrintedModelJson = String(data: data!, encoding: String.Encoding.utf8)
            print("""
                -----------🖨🖨🖨 console log AAOptions JSON information of AAChartView 🖨🖨🖨-----------:
                \(prettyPrintedModelJson!)
                """)
        }
        #endif
```

You can Comment out this code in AAChartView class file

**Comment by mehulparmar4ever** [comment]
Hello @AAChartModel @HappyIosDeveloper ,

Any updates?

> You can Comment Out this code in AAChartView class file
We are using Swift Package Manager, Unable to edit file.

**Comment by DanYoung-1** [comment]
There should have a property on AAChartView that can toggle off annoying logs.

**Comment by parmar-mehul** [comment]
We have to wait until @AAChartModel make this changes to the package.
