### ISSUE TITLE
准心线的高度怎样控制

### ISSUE THREAD

**Issue by GRITWJY** [AAChartModel/AAChartKit-Swift#296]
你好，我想让准星线只显示x轴到数据数据点的部分，上面剩余部分不显示，可以实现吗？
![图片](https://user-images.githubusercontent.com/56510542/114386565-f8cc5200-9bc3-11eb-8329-1961a53ee3eb.png)

**Comment by AAChartModel** [comment]
准星线的自定义属性有限, 不支持对其高度的设置.

准星线所有属性, 参考 https://api.highcharts.com/highcharts/xAxis.crosshair

**Comment by GRITWJY** [comment]
好的，谢谢啦
