### ISSUE TITLE
Different axes colors

### ISSUE THREAD

**Issue by Ruuuuddyyy** [AAChartModel/AAChartKit-Swift#298]
<img width="440" alt="Screenshot 2021-05-06 at 12 55 09" src="https://user-images.githubusercontent.com/25419057/117279424-5f165e80-ae6a-11eb-9da3-0c9992ab299e.png">

1.I need add 2 different colors for Y and X axes like in screenshot.
2. Add 2 different colors for background like in screenshot (white and blue colors alternating by lines)

**Comment by AAChartModel** [comment]
```swift
        aaOptions.yAxis?
            .gridLineWidth(30)
            .gridLineColor(AAColor.rgbaColor(68, 170, 213, 0.2))
            .labels?.style(AAStyle(color: "DodgerBlue"))
```

**Comment by AAChartModel** [comment]
> 1.I need add 2 different colors for Y and X axes like in screenshot.

```swift
.labels?.style(AAStyle(color: "DodgerBlue"))
```

**Comment by AAChartModel** [comment]
> 2. Add 2 different colors for background like in screenshot (white and blue colors alternating by lines)

```swift
.gridLineWidth(30)
.gridLineColor(AAColor.rgbaColor(68, 170, 213, 0.2))
```

**Comment by Ruuuuddyyy** [comment]
> ```swift
>         aaOptions.yAxis?
>             .gridLineWidth(30)
>             .gridLineColor(AAColor.rgbaColor(68, 170, 213, 0.2))
>             .labels?.style(AAStyle(color: "DodgerBlue"))
> ```

Please, tell me how to apply AAOptions to model

**Comment by AAChartModel** [comment]
1. Convert AAChartModel to AAOptions 

```swift
        let aaOptions = aaChartModel.aa_toAAOptions()

```

2. then 

```swift
        aaOptions.yAxis?
            .gridLineWidth(30)
            .gridLineColor(AAColor.rgbaColor(68, 170, 213, 0.2))
            .labels?.style(AAStyle(color: "DodgerBlue"))
```

3. finally 
```swift
            self.aaChartView?.aa_drawChartWithChartOptions(aaOptions)
```

More details you can see it in the AAChartKit-Swift Demo.

**Comment by Ruuuuddyyy** [comment]
Thank you very much, and last question. Сan i make a gradient  "shadow" below the line in screen?
