### ISSUE TITLE
On Legend selection chart shows faded. 

### ISSUE THREAD

**Issue by sanjay226** [AAChartModel/AAChartKit-Swift#300]
### Please see attached screenshot.  Please help.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-12 at 10 37 26](https://user-images.githubusercontent.com/57610946/117921798-fec26980-b30e-11eb-9433-0b568ca4e818.png)

### Some time I de-select first legend and re-select, then other chart shows faded. Please see screenshot.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-12 at 10 49 15](https://user-images.githubusercontent.com/57610946/117922804-a55b3a00-b310-11eb-846f-664dfd4db8fb.png)

**Comment by AAChartModel** [comment]
I think it is a bug of Highcharts , you can disable the `Inactive` effect to avoid the problem.

```objc

        aaOptions.plotOptions?.series?
            .states(AAStates()
                .inactive(AAInactive()
                    .enabled(false))) // 🔑 the key property
```

**Comment by AAChartModel** [comment]
Refer to https://github.com/AAChartModel/AAChartKit/issues/949

**Comment by sanjay226** [comment]
> I think it is a bug of Highcharts , you can disable the `Inactive` effect to avoid the problem.
> 
> ```swift
>         aaOptions.plotOptions?.series?
>             .states(AAStates()
>                 .inactive(AAInactive()
>                     .enabled(false))) // 🔑 the key property
> ```

This works. Thank you 👍
