### ISSUE TITLE
线条hover上去会变粗

### ISSUE THREAD

**Issue by q1019736727** [AAChartModel/AAChartKit-Swift#301]
我参照OC的解决方法，但是swift版本没有lineWidthPlus这个属性，该怎样设置hover上去不会加粗线条

**Comment by q1019736727** [comment]
现在我把AAHighchartsLib.js里面lineWidthPlus改为0就不会出现该问题，请问是否还有更好的解决方法

**Comment by q1019736727** [comment]
> ```swift
> .states(AAStates()
>          .hover(AAHover()
>               .enabled(false) //禁用 hover 效果
>                     ))
> ```

**Comment by q1019736727** [comment]
> ```swift
> .states(AAStates()
>          .hover(AAHover()
>               .enabled(false) //禁用 hover 效果
>                     ))
> ```

这样设置选中时候的小点不会出现，我需要选中的小点

**Comment by AAChartModel** [comment]
已在此次提交 https://github.com/AAChartModel/AAChartKit-Swift/commit/5afd3f4caedd275dddde440adbe12bb4b34372f7 中为 AAHover 新增属性 lineWidth 和 lineWidthPlus , 如 README 文档中所说, 更新 AAChartKit-Swift  至最新内容即可使用新增的关键属性 ` lineWidthPlus` .
