### ISSUE TITLE
饼图怎么将图例标题直接显示在图上呢？

### ISSUE THREAD

**Issue by ShuoHuang** [AAChartModel/AAChartKit-Swift#307]
没办法，UI设计就是要这样的效果，我尝试了很久都没搞出来。
我设置了AADataLabels的inside为true，但是没有生效。

**Comment by AAChartModel** [comment]
你给的不是有效链接

**Comment by ShuoHuang** [comment]
> 你给的不是有效链接

[https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fku.90sjimg.com%2Felement_origin_min_pic%2F17%2F03%2F28%2Fbd5a8c20939c7ffa077d128be8d5b1d9.jpg%21%2Ffwfh%2F804x517%2Fquality%2F90%2Funsharp%2Ftrue%2Fcompress%2Ftrue&refer=http%3A%2F%2Fku.90sjimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1625735053&t=064e3593c1597a49079dfc00f2449dc0](url)

**Comment by ShuoHuang** [comment]
> 你给的不是有效链接
类似这种
![1623143082353](https://user-images.githubusercontent.com/12667958/121158243-cade5380-c87c-11eb-937e-03a024cd196e.jpg)

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/1192

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/345

**Comment by ShuoHuang** [comment]
> AAChartModel/AAChartKit#345

不好意思，之前没搜到，谢谢

**Comment by AAChartModel** [comment]
> 参考 [AAChartModel/AAChartKit#1192](https://github.com/AAChartModel/AAChartKit/issues/1192)

这样设计有个问题, 数据如果太拥挤了, 就没有办法将所有 AADataLabels 显示完全

**Comment by ShuoHuang** [comment]
> > 参考 [AAChartModel/AAChartKit#1192](https://github.com/AAChartModel/AAChartKit/issues/1192)
> 
> 这样设计有个问题, 数据如果太拥挤了, 就没有办法将所有 AADataLabels 显示完全

嗯嗯，从我们的数据来看，应该没问题，因为不是很多，并且数据差异不是很大，所以这个问题应该不大
