### ISSUE TITLE
关于坐标值数据过大显示问题

### ISSUE THREAD

**Issue by zmc969213509** [AAChartModel/AAChartKit-Swift#309]
当坐标值数据之间存在很大差距时，小数据几乎无法肉眼可见，请问一下是否可以设置对数坐标呢，让每一条数据肉眼都可见
目前情况如下图所示
![问题描述](https://user-images.githubusercontent.com/28091554/123388143-0d1cca00-d5cb-11eb-9b29-dd2ee75c0610.jpg)
![问题描述1](https://user-images.githubusercontent.com/28091554/123388150-0e4df700-d5cb-11eb-9ba6-e917e5c726a6.jpg)

**Comment by AAChartModel** [comment]
参考相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/1295
