### ISSUE TITLE
How to show y-axis on the right side of chart?

### ISSUE THREAD

**Issue by isaranjha** [AAChartModel/AAChartKit-Swift#317]
How can I show the y-axis on the right side of the chart?

**Comment by geekstars** [comment]
Hope to help you

let aaOptions = aaChartModel.aa_toAAOptions()
aaOptions.yAxis?.opposite(true)

aaChartView.aa_drawChartWithChartOptions(aaOptions)

**Comment by geekstars** [comment]
Duplicate of #95
