### ISSUE TITLE
多图表联动滑动问题

### ISSUE THREAD

**Issue by people990** [AAChartModel/AAChartKit-Swift#318]
在实现对 AAChartView 事件代理的监听
```swift
    func aaChartView(_ aaChartView: AAChartView, moveOverEventMessage: AAMoveOverEventMessageModel)
```
 中的 `plotX/plotY` 及 `moveOverEventMessage.x/moveOverEventMessage.y` 都不是 `AAChartView.scrollView.contentOffset`；请问如何获取到滑动的`AAChartView.scrollView.contentOffset`，方便其他图表一起滑动？谢谢。

**Comment by AAChartModel** [comment]
```swift

selected point series element name: Berlin
🔥🔥🔥WARNING!!!!!!!!!!!!!!!!!!!! Touch Event Message !!!!!!!!!!!!!!!!!!!! WARNING🔥🔥🔥
==========================================================================================
------------------------------------------------------------------------------------------
user finger moved over!!!,get the move over event message: {
category = Optional("Aug")
index = Optional(7)
name = Optional("Berlin")
offset = Optional(["plotX": 609.375, "plotY": 191.18])
x = Optional(7.0)
y = Optional(17.9)
}
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

由 demo 中的用户点击事件示例中的 console 输出可知

```swift
public class AAMoveOverEventMessageModel: NSObject {
    public var name: String?
    public var x: Float?
    public var y: Float?
    public var category: String?
    public var offset: [String: Any]?
    public var index: Int?
}
```

AAMoveOverEventMessageModel 的 offset 属性内容为

```swift
["plotX": 609.375, "plotY": 191.18]
```
这样的包含图表 X 轴和 Y 轴偏移量的字典.

所以AAMoveOverEventMessageModel 的 offset 属性应该能够满足你的获取滑动 `AAChartView.scrollView.contentOffset`的需求

**Comment by people990** [comment]
如果 plotX/plotY是AAChartView.scrollView.contentOffset，那么不滑动视图，获取到的plotX/plotY应该是固定不变的，但是每次点击触发回调plotX/plotY都有变化；我需要获取页面中第一个AAChartView.scrollView.contentOffset，来实现第二个AAChartView也跟着一起滑动；如果直接打印 po heartAAChartView.scrollView.contentOffset获取到的是(0.0, 0.5)；麻烦再确定一下，谢谢！

**Comment by people990** [comment]
为何我每次在    
func aaChartView(_ aaChartView: AAChartView, moveOverEventMessage: AAMoveOverEventMessageModel)
获取到的滑动的scrollView.contentOffset都是固定不变的；在页面中实现UIScrollViewDelegate进入页面触发，滑动页面不触发；

**Comment by AAChartModel** [comment]
https://github.com/highcharts/highcharts-ios/issues/108

你要的这种获取 contentOffset 应该是不支持的

**Comment by AAChartModel** [comment]
> 为何我每次在
> 
> ```swift
> func aaChartView(_ aaChartView: AAChartView, moveOverEventMessage: AAMoveOverEventMessageModel)
> ```
> 
> 获取到的滑动的scrollView.contentOffset都是固定不变的；在页面中实现UIScrollViewDelegate进入页面触发，滑动页面不触发；

你应该理解错了这个方法的含义了, 这个方法获取到的 `offset` 指的:
**是禁止图表本身的滑动功能时, 手指在图表上左右滑动时, 手指触摸的点相对于图表本身的位移.**

**Comment by people990** [comment]
要更换第三方了。。。希望后期能支持这个功能，谢谢！
