### ISSUE TITLE
Y 轴如何添加后缀？

### ISSUE THREAD

**Issue by AlleniCode** [AAChartModel/AAChartKit-Swift#330]
图表上的数据都是百分比，传入的值是乘了100的，比如 80.8% -> 80.8；悬浮窗上已经添加了后缀“%”，现在想要在 Y 轴上也加上后缀，这是现在的效果：

<img width="312" alt="QQ20211021-183347@2x" src="https://user-images.githubusercontent.com/8855341/138261463-954b607c-b91f-4048-96cc-ba0354e42504.png">

**Comment by VisionColion** [comment]
aaOptions.yAxis?.labels?.format = "{value} $"//给y轴添加单位 
按照这个改了 没生效
