### ISSUE TITLE
您好，X轴的title能不能设置在轴线右侧

### ISSUE THREAD

**Issue by keleboys** [AAChartModel/AAChartKit-Swift#339]
就像图例一样：![截屏2022-01-20 上午11 07 49](https://user-images.githubusercontent.com/18566643/150265128-d5cc12f9-ff6c-4647-b80a-5642066c14db.png)

**Comment by AAChartModel** [comment]
```swift
public class AASubtitle: AAObject {
    public var text: String?
    public var style: AAStyle?
    public var align: String?
    public var verticalAlign: String?
    public var x: Float?
    public var y: Float?
    public var userHTML: Bool?
```

通过 `align`  可以设置副标题居右显示, x 值和 y 值, 可以在此基础上进一步设置位置.

参考文档:

* https://api.highcharts.com/highcharts/subtitle
