### ISSUE TITLE
如何设置默认选中某一个项，而不需要点击

### ISSUE THREAD

**Issue by kevin-zheng12** [AAChartModel/AAChartKit-Swift#345]
如何设置默认选中某一个项，而不需要点击

**Comment by codeceo-net** [comment]
跟 113 一样的问题

**Comment by Ficky-Michy** [comment]
请问这个解决了吗？
@kevin-zheng12 @codeceo-net

**Comment by AAChartModel** [comment]
## 配置 AAOptions

```swift
private func setCrosshairAndTooltipToTheDefaultPositionAfterLoadingChart() -> AAOptions {
        let aaChartModel = AAChartModel()
            .chartType(.areaspline)//图形类型
            .markerSymbolStyle(.borderBlank)//折线连接点样式为外边缘空白
            .dataLabelsEnabled(false)
            .colorsTheme(["#04d69f","#1e90ff","#ef476f","#ffd066",])
            .stacking(.normal)
            .markerRadius(0)
            .series([
                AASeriesElement()
                    .name("Tokyo Hot")
                    .lineWidth(5.0)
                    .fillOpacity(0.4)
                    .data([0.45, 0.43, 0.50, 0.55, 0.58, 0.62, 0.83, 0.39, 0.56, 0.67, 0.50, 0.34, 0.50, 0.67, 0.58, 0.29, 0.46, 0.23, 0.47, 0.46, 0.38, 0.56, 0.48, 0.36])
                ,
                AASeriesElement()
                    .name("Berlin Hot")
                    .lineWidth(5.0)
                    .fillOpacity(0.4)
                    .data([0.38, 0.31, 0.32, 0.32, 0.64, 0.66, 0.86, 0.47, 0.52, 0.75, 0.52, 0.56, 0.54, 0.60, 0.46, 0.63, 0.54, 0.51, 0.58, 0.64, 0.60, 0.45, 0.36, 0.67])
                ,
                AASeriesElement()
                    .name("New York Hot")
                    .lineWidth(5.0)
                    .fillOpacity(0.4)
                    .data([0.46, 0.32, 0.53, 0.58, 0.86, 0.68, 0.85, 0.73, 0.69, 0.71, 0.91, 0.74, 0.60, 0.50, 0.39, 0.67, 0.55, 0.49, 0.65, 0.45, 0.64, 0.47, 0.63, 0.64])
                ,
                AASeriesElement()
                    .name("London Hot")
                    .lineWidth(5.0)
                    .fillOpacity(0.4)
                    .data([0.60, 0.51, 0.52, 0.53, 0.64, 0.84, 0.65, 0.68, 0.63, 0.47, 0.72, 0.60, 0.65, 0.74, 0.66, 0.65, 0.71, 0.59, 0.65, 0.77, 0.52, 0.53, 0.58, 0.53])
                ,
            ])
        
        let aaOptions = aaChartModel.aa_toAAOptions()
        
        aaOptions.tooltip?
            .style(AAStyle(color: AAColor.white))
            .backgroundColor("#050505")
            .borderColor("#050505")
        
        aaOptions.xAxis?.crosshair(
            AACrosshair()
                .color(AAColor.darkGray)
                .dashStyle(.longDashDotDot)
                .width(2)
        )
        
        //默认选中的位置索引
        let defaultSelectedIndex = 5
        
        //https://api.highcharts.com/highcharts/chart.events.load
        //https://www.highcharts.com/forum/viewtopic.php?t=36508
        aaOptions.chart?.events(
            AAChartEvents()
                .load("""
        function() {
            let points = [],
                chart = this,
                series = chart.series,
                length = series.length;
                        
            for (let i = 0; i < length; i++) {
              let pointElement = series[i].data[\(defaultSelectedIndex)];
              points.push(pointElement);
            }
            chart.xAxis[0].drawCrosshair(null, points[0]);
            chart.tooltip.refresh(points);
          }
"""))
        
        return aaOptions
    }
```

## 最终图表
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-06 at 17 03 28](https://user-images.githubusercontent.com/16357599/172131081-6a468915-b115-463b-8a26-6d7177c03408.png)

**Comment by AAChartModel** [comment]
现已为 AAChartEvents 新增 load 属性. 更新 AAChartKit-Swift 至最新内容即可.

* #359

**Comment by AAChartModel** [comment]
**Demo** 中已添加此示例, 下载运行查看即可.

**Comment by Ficky-Michy** [comment]
> 

有bug，在AAChartModel中设置这个参数会有问题：
`  .scrollablePlotArea(
                        AAScrollablePlotArea()
                                .minWidth(600)
                                .scrollPositionX(1))
`
，如果defaultSelectedIndex选择的是数据后面几个位置的话，crosshair会显示正常，但是tooltip会显示不了。

**Comment by 47God003** [comment]
你好 大神
我研究 柱状图  默认选中这个功能好久  总是效果不理想

**Comment by 47God003** [comment]
let aaOptions = aaChartModel.aa_toAAOptions()
        
        aaOptions.xAxis?.crosshair(
            AACrosshair()
                .color("F9D247")
                .width(20)
        )
        
        //默认选中的位置索引
        let defaultSelectedIndex = data.count - 1
        
        aaOptions.chart?.events(
                    AAChartEvents()
                        .load("""
                function() {
                    let points = [],
                        chart = this,
                        series = chart.series,
                        length = series.length;
                                
                    for (let i = 0; i < length; i++) {
                      let pointElement = series[i].data[\(defaultSelectedIndex)];
                      points.push(pointElement);
                    }
                    chart.xAxis[0].drawCrosshair(null, points[0]);
                    chart.tooltip.refresh(points);
                  }
        """))
        
        aaChartView.aa_drawChartWithChartOptions(aaOptions)

**Comment by 47God003** [comment]
let aaOptions = aaChartModel.aa_toAAOptions()
        
        aaOptions.xAxis?.crosshair(
            AACrosshair()
                .color("#F9D247")
                .width(20)
        )
        
        //默认选中的位置索引
        let defaultSelectedIndex = data.count - 1
        
        aaOptions.chart?.events(
                    AAChartEvents()
                        .load("""
                function() {
                    let points = [],
                        chart = this,
                        series = chart.series,
                        length = series.length;
                                
                    for (let i = 0; i < length; i++) {
                      let pointElement = series[i].data[\(defaultSelectedIndex)];
                      points.push(pointElement);
                    }
                    chart.xAxis[0].drawCrosshair(null, points[0]);
                    chart.tooltip.refresh(points);
                  }
        """))
        
        aaChartView.aa_drawChartWithChartOptions(aaOptions)

**Comment by 47God003** [comment]
![image](https://user-images.githubusercontent.com/99459096/191517024-f19eb7b9-87b6-4d1b-bc2b-21b762f3484a.png)

**Comment by 47God003** [comment]
大神 能否指出 我的问题

**Comment by AAChartModel** [comment]
> 你好 大神 我研究 柱状图 默认选中这个功能好久 总是效果不理想

效果不理想指的是什么? 是无法实现图中的效果吗? 这个示例已添加到 demo 中, 下载运行查看测试即可.

**Comment by 47God003** [comment]
.tooltipEnabled(false)

当关闭 悬浮框提示

默认选中的效果就 失效

**Comment by 47God003** [comment]
private func setCrosshairAndTooltipToTheDefaultPositionAfterLoadingChart() -> AAOptions {
        let aaChartModel = AAChartModel()
            .chartType(.column)//图形类型
            .markerSymbolStyle(.borderBlank)//折线连接点样式为外边缘空白
            .dataLabelsEnabled(false)
            .colorsTheme(["#ffd066",])
            .stacking(.normal)
            .markerRadius(0)
        
            .tooltipEnabled(false)//是否显示浮动提示框(默认显示)
        
            .series([
                AASeriesElement()
                    .name("Tokyo Hot")
                    .lineWidth(5.0)
                    .fillOpacity(0.4)
                    .data([0.45, 0.43, 0.50, 0.55, 0.58, 0.62, 0.83, 0.39, 0.56, 0.67, 0.50, 0.34, 0.50, 0.67, 0.58, 0.29, 0.46, 0.23, 0.47, 0.46, 0.38, 0.56, 0.48, 0.36])
                ,
            ])
        
        let aaOptions = aaChartModel.aa_toAAOptions()
        
        aaOptions.tooltip?
            .style(AAStyle(color: AAColor.white))
            .backgroundColor("#050505")
            .borderColor("#050505")
        
        aaOptions.xAxis?.crosshair(
            AACrosshair()
                .color(AAColor.darkGray)
                .dashStyle(.longDashDotDot)
                .width(2)
        )
        
        //默认选中的位置索引
        let defaultSelectedIndex = 5
        
        //https://api.highcharts.com/highcharts/chart.events.load
        //https://www.highcharts.com/forum/viewtopic.php?t=36508
        aaOptions.chart?.events(
            AAChartEvents()
                .load("""
        function() {
            let points = [],
                chart = this,
                series = chart.series,
                length = series.length;
                        
            for (let i = 0; i < length; i++) {
              let pointElement = series[i].data[\(defaultSelectedIndex)];
              points.push(pointElement);
            }
            chart.xAxis[0].drawCrosshair(null, points[0]);
            chart.tooltip.refresh(points);
          }
"""))
        
        return aaOptions
    }

**Comment by AAChartModel** [comment]
> .tooltipEnabled(false)
> 
> 当关闭 悬浮框提示
> 
> 默认选中的效果就 失效

这是肯定的啊, 你都已经禁用浮动提示框了, 那这个默认选中的效果肯定就失灵了啊

**Comment by AAChartModel** [comment]
> .tooltipEnabled(false)
> 
> 当关闭 悬浮框提示
> 
> 默认选中的效果就 失效

这是肯定的啊, 你都已经禁用浮动提示框了, 那这个默认选中的效果肯定就失灵了啊

**Comment by AAChartModel** [comment]
> .tooltipEnabled(false)
> 
> 当关闭 悬浮框提示
> 
> 默认选中的效果就 失效

这是肯定的啊, 你都已经禁用浮动提示框了, 那这个默认选中的效果肯定就失灵了啊

**Comment by 47God003** [comment]
能有啥办法  隐藏掉提示框 提示框嘛  比如 设置alpha  背景颜色 全透明  之类的

**Comment by 47God003** [comment]
对了 对了  感谢大神的回复

**Comment by AAChartModel** [comment]
> 能有啥办法 隐藏掉提示框 提示框嘛 比如 设置alpha 背景颜色 全透明 之类的

下面的这种方式更好, 这是 Highcharts 内置的方法, 
```swift
   let aaOptions = aaChartModel.aa_toAAOptions()
        aaOptions.tooltip?.formatter("""
            function () {
                return false;
                    }
            """)
```

设置alpha 背景颜色 全透明 之类的方式不推荐. 用内置的方法更好

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/365

**Comment by AAChartModel** [comment]
参考在线文档: 
* https://api.highcharts.com/highcharts/tooltip.formatter

**Comment by 47God003** [comment]
感谢大神~~~

**Comment by szweee** [comment]
> 在麻烦一下大神
> 
> 我发现
> 
> 默认选中的柱子 无法取消选中状态
> 
> 需要重新点击 默认选中的柱子 才可以取消
> 
> 
> 
> <img width="346" alt="image" src="https://user-images.githubusercontent.com/99459096/191740760-56ce32b6-e619-437d-acfc-903b3daad548.png">
> 
> 
> 
>     private func setCrosshairAndTooltipToTheDefaultPositionAfterLoadingChart() -> AAOptions {
> 
>         let aaChartModel = AAChartModel()
> 
>             .chartType(.column)//图形类型
> 
>             .markerSymbolStyle(.borderBlank)//折线连接点样式为外边缘空白
> 
>             .dataLabelsEnabled(false)
> 
>             .colorsTheme(["#ffd066",])
> 
>             .stacking(.normal)
> 
>             .markerRadius(0)
> 
>         
> 
> //            .tooltipEnabled(false)//是否显示浮动提示框(默认显示)
> 
>         
> 
>             .series([
> 
>                 AASeriesElement()
> 
>                     .name("Tokyo Hot")
> 
>                     .lineWidth(5.0)
> 
>                     .fillOpacity(0.4)
> 
>                     .data([0.45, 0.43, 0.50, 0.55, 0.58, 0.62, 0.83, 0.39, 0.56, 0.67, 0.50, 0.34, 0.50, 0.67, 0.58, 0.29, 0.46, 0.23, 0.47, 0.46, 0.38, 0.56, 0.48, 0.36])
> 
>                 ,
> 
>             ])
> 
>         
> 
>         let aaOptions = aaChartModel.aa_toAAOptions()
> 
>         
> 
>         aaOptions.tooltip?.formatter("""
> 
>                     function () {
> 
>                         return false;
> 
>                             }
> 
>                     """)
> 
>         
> 
>         aaOptions.xAxis?.crosshair(
> 
>             AACrosshair()
> 
>                 .color(AAColor.darkGray)
> 
>                 .dashStyle(.longDashDotDot)
> 
>                 .width(2)
> 
>         )
> 
>         
> 
>         //默认选中的位置索引
> 
>         let defaultSelectedIndex = 5
> 
>         
> 
>         //https://api.highcharts.com/highcharts/chart.events.load
> 
>         //https://www.highcharts.com/forum/viewtopic.php?t=36508
> 
>         aaOptions.chart?.events(
> 
>             AAChartEvents()
> 
>                 .load("""
> 
>         function() {
> 
>             let points = [],
> 
>                 chart = this,
> 
>                 series = chart.series,
> 
>                 length = series.length;
> 
>                         
> 
>             for (let i = 0; i < length; i++) {
> 
>               let pointElement = series[i].data[\(defaultSelectedIndex)];
> 
>               points.push(pointElement);
> 
>             }
> 
>             chart.xAxis[0].drawCrosshair(null, points[0]);
> 
>             chart.tooltip.refresh(points);
> 
>           }
> 
> """))
> 
>         
> 
>         return aaOptions
> 
>     }

**Comment by szweee** [comment]
> 在麻烦一下大神
> 
> 我发现
> 
> 默认选中的柱子 无法取消选中状态
> 
> 需要重新点击 默认选中的柱子 才可以取消
> 
> 
> 
> <img width="346" alt="image" src="https://user-images.githubusercontent.com/99459096/191740760-56ce32b6-e619-437d-acfc-903b3daad548.png">
> 
> 
> 
>     private func setCrosshairAndTooltipToTheDefaultPositionAfterLoadingChart() -> AAOptions {
> 
>         let aaChartModel = AAChartModel()
> 
>             .chartType(.column)//图形类型
> 
>             .markerSymbolStyle(.borderBlank)//折线连接点样式为外边缘空白
> 
>             .dataLabelsEnabled(false)
> 
>             .colorsTheme(["#ffd066",])
> 
>             .stacking(.normal)
> 
>             .markerRadius(0)
> 
>         
> 
> //            .tooltipEnabled(false)//是否显示浮动提示框(默认显示)
> 
>         
> 
>             .series([
> 
>                 AASeriesElement()
> 
>                     .name("Tokyo Hot")
> 
>                     .lineWidth(5.0)
> 
>                     .fillOpacity(0.4)
> 
>                     .data([0.45, 0.43, 0.50, 0.55, 0.58, 0.62, 0.83, 0.39, 0.56, 0.67, 0.50, 0.34, 0.50, 0.67, 0.58, 0.29, 0.46, 0.23, 0.47, 0.46, 0.38, 0.56, 0.48, 0.36])
> 
>                 ,
> 
>             ])
> 
>         
> 
>         let aaOptions = aaChartModel.aa_toAAOptions()
> 
>         
> 
>         aaOptions.tooltip?.formatter("""
> 
>                     function () {
> 
>                         return false;
> 
>                             }
> 
>                     """)
> 
>         
> 
>         aaOptions.xAxis?.crosshair(
> 
>             AACrosshair()
> 
>                 .color(AAColor.darkGray)
> 
>                 .dashStyle(.longDashDotDot)
> 
>                 .width(2)
> 
>         )
> 
>         
> 
>         //默认选中的位置索引
> 
>         let defaultSelectedIndex = 5
> 
>         
> 
>         //https://api.highcharts.com/highcharts/chart.events.load
> 
>         //https://www.highcharts.com/forum/viewtopic.php?t=36508
> 
>         aaOptions.chart?.events(
> 
>             AAChartEvents()
> 
>                 .load("""
> 
>         function() {
> 
>             let points = [],
> 
>                 chart = this,
> 
>                 series = chart.series,
> 
>                 length = series.length;
> 
>                         
> 
>             for (let i = 0; i < length; i++) {
> 
>               let pointElement = series[i].data[\(defaultSelectedIndex)];
> 
>               points.push(pointElement);
> 
>             }
> 
>             chart.xAxis[0].drawCrosshair(null, points[0]);
> 
>             chart.tooltip.refresh(points);
> 
>           }
> 
> """))
> 
>         
> 
>         return aaOptions
> 
>     }

这个问题解决了吗
