### ISSUE TITLE
隐藏 X 轴的刻度线

### ISSUE THREAD

**Issue by gaoruiqing187** [AAChartModel/AAChartKit-Swift#351]
X轴的下方会有一排竖线，怎么去掉？我按照demo里数据少的时候的居左设置，还是有一些空隙

**Comment by AAChartModel** [comment]
> X轴的下方会有一排竖线，怎么去掉？

参考 Objective-C 版本的 AAChartKit 相同问题

* https://github.com/AAChartModel/AAChartKit/issues/825
