### ISSUE TITLE
最新版本categories设置不生效

### ISSUE THREAD

**Issue by leinan100** [AAChartModel/AAChartKit-Swift#352]
你的demo里面也都不显示了

**Comment by AAChartModel** [comment]
> 1.4.0版本

[AAChartKit-Swift](https://github.com/AAChartModel/AAChartKit-Swift)  没有这个版本号吧?

**Comment by leinan100** [comment]
> > 1.4.0版本
> 
> [AAChartKit-Swift](https://github.com/AAChartModel/AAChartKit-Swift) 没有这个版本号吧?

版本号说错了，就是最新版的X轴设置不生效了

**Comment by AAChartModel** [comment]
问题已修复, 更新 AAChartKit-Swift 至最新内容即可.
