### ISSUE TITLE
这个图应该参考哪个例子？

### ISSUE THREAD

**Issue by AlleniCode** [AAChartModel/AAChartKit-Swift#353]
https://coinmarketcap.com/zh/currencies/ethereum/

<img width="959" alt="image" src="https://user-images.githubusercontent.com/8855341/166620813-55a1d60c-e08a-47e6-a978-8f45de11fd54.png">

我想绘制一个这样的图，应该参考哪个例子啊？谢谢！

**Comment by AAChartModel** [comment]
这个不支持. 你的示例图表有底部导航缩略视图, 这个功能是 Highstock.js 的功能. 而 [AAChartKit-Swift](https://github.com/AAChartModel/AAChartKit-Swift) 封装的是 Highcharts.js .

如果不需要底部导航缩略视图的功能的话,  参考折线区域填充图就可以了.

**Comment by AlleniCode** [comment]
好的，谢谢！
