### ISSUE TITLE
如何更新 `AAChartKit-Swift` 至最新内容?

### ISSUE THREAD

**Issue by AAChartModel** [AAChartModel/AAChartKit-Swift#359]

**Comment by mehulparmar4ever** [comment]
Hello @AAChartModel ,

You should also mention about Swift Package Manager (SPM)
As I don't see if you released new version (**`7.4.0`**) with Tag in SPM

Here is my comment
https://github.com/AAChartModel/AAChartKit-Swift/issues/433#issuecomment-1732960242
