### ISSUE TITLE
请问一下，在写JS的时候，那些this.point和this.x这种有没有文档？？？

### ISSUE THREAD

**Issue by Ficky-Michy** [AAChartModel/AAChartKit-Swift#361]
请问一下，在写JS的时候，那些this.point和this.x这种有没有文档？？？
我需要在这个图中的Language market share 位置处显示 swift 这个 字段 ，[https://github.com/Ficky-Michy/pic/blob/main/WX20220601-012948%402x.png](url) ，  [https://github.com/Ficky-Michy/pic/blob/main/WX20220601-013037%402x.png](url) ， [https://github.com/Ficky-Michy/pic/blob/main/WX20220601-013146%402x.png](url) ，

 但是一直取值失败，我想问问，有没有文档可以查到应该取什么值。

**Comment by AAChartModel** [comment]
另:

GitHub 的 issue 区支持直接拖拽上传图片, 不用上传到仓库中再添加图片链接.  

另外你的 issue 的图片链接格式没有一个是对的.
