### ISSUE TITLE
 请问当几条数据的value都是0的时候，为啥你的图表会从中间位置开始显示一条横向的数据呢？而不是从0位置开始显示

### ISSUE THREAD

**Issue by liujieyuu** [AAChartModel/AAChartKit-Swift#366]
请问当几条数据的value都是0的时候，为啥你的图表会从中间位置开始显示一条横向的数据呢？而不是从0位置开始显示

**Comment by AAChartModel** [comment]
参考相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/773

**Comment by AAChartModel** [comment]
> 请问当几条数据的value都是0的时候，为啥你的图表会从中间位置开始显示一条横向的数据呢？

依赖的 Highcharts 的默认效果就是这样

**Comment by liujieyuu** [comment]
能否自定义起始位置呢？

**Comment by liujieyuu** [comment]
> > 请问当几条数据的value都是0的时候，为啥你的图表会从中间位置开始显示一条横向的数据呢？
> 
> 依赖的 Highcharts 的默认效果就是这样
能否自定义起始位置呢？
