### ISSUE TITLE
请教一下柱状图如何通过外部按钮来控制哪个 bar 当前是选中状态，而不需要手动点击

### ISSUE THREAD

**Issue by HongyuanLi-Wyze** [AAChartModel/AAChartKit-Swift#367]
需要实现的效果是点击 bar 可以切换选中，点击图标外的按钮也可以切换当前选中的 bar，谢谢

**Comment by Maxcucurbit** [comment]
我也有这个需求

**Comment by AAChartModel** [comment]
参考

在线文档:

* https://api.highcharts.com/class-reference/Highcharts.Point.html#select

在线示例:

* https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/point-select/

**Comment by AAChartModel** [comment]
中文版 (访问速度更快) 参考

在线文档:

* https://api.highcharts.com.cn/class-reference/Highcharts.Point.html#select

在线示例:

* https://jshare.com.cn/github/highcharts/highcharts/tree/master/samples/highcharts/members/point-select

**Comment by AAChartModel** [comment]
以上示例虽是折线图📈, 但是柱状图📊与此同理.

**Comment by Maxcucurbit** [comment]
有没有swift的代码例子？
