### ISSUE TITLE
当页面滚动时，希望隐藏折线图的十字线和高亮点。

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#369]
我只找到了配置十字线和高亮点的入口，但是隐藏十字线和高亮点的没有找到。
如何才能做到随时隐藏十字线和高亮点呢
![image](https://user-images.githubusercontent.com/12290214/178630184-8e0a39dc-b0cf-43b8-85e7-bb74cfc70761.png)

**Comment by AAChartModel** [comment]
参考 Objective-C 版本的相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/909

**Comment by AAChartModel** [comment]
Swift 语言版本的写法如下:

```swift
    // https://github.com/AAChartModel/AAChartKit/issues/1318
    // Refer to https://api.highcharts.com.cn/highcharts#plotOptions.spline.marker.states.hover.enabled
    private func disableSplineChartMarkerHoverEffect() -> AAChartModel {
        AAChartModel()
            .chartType(.spline)
            .title("Disable Spline Chart Marker Hover Effect")
            .categories([
                "一月", "二月", "三月", "四月", "五月", "六月",
                "七月", "八月", "九月", "十月", "十一月", "十二月"
            ])
            .markerRadius(0)//marker点半径为0个像素
            .yAxisLineWidth(0)
            .yAxisGridLineWidth(0)
            .legendEnabled(false)
            .series([
                AASeriesElement()
                    .name("Tokyo Hot")
                    .lineWidth(5.0)
                    .color(AARgba(220, 20, 60, 1))//猩红色, alpha 透明度 1
                    .marker(AAMarker()
                        .states(AAMarkerStates()
                            .hover(AAMarkerHover()
                                .enabled(false))))
                    .data([7.0, 6.9, 2.5, 14.5, 18.2, 21.5, 5.2, 26.5, 23.3, 45.3, 13.9, 9.6])
            ])
    }
```

**Comment by lhpkxywm** [comment]
> Swift 语言版本的写法如下:
> 
> ```swift
>     // https://github.com/AAChartModel/AAChartKit/issues/1318
>     // Refer to https://api.highcharts.com.cn/highcharts#plotOptions.spline.marker.states.hover.enabled
>     private func disableSplineChartMarkerHoverEffect() -> AAChartModel {
>         AAChartModel()
>             .chartType(.spline)
>             .title("Disable Spline Chart Marker Hover Effect")
>             .categories([
>                 "一月", "二月", "三月", "四月", "五月", "六月",
>                 "七月", "八月", "九月", "十月", "十一月", "十二月"
>             ])
>             .markerRadius(0)//marker点半径为0个像素
>             .yAxisLineWidth(0)
>             .yAxisGridLineWidth(0)
>             .legendEnabled(false)
>             .series([
>                 AASeriesElement()
>                     .name("Tokyo Hot")
>                     .lineWidth(5.0)
>                     .color(AARgba(220, 20, 60, 1))//猩红色, alpha 透明度 1
>                     .marker(AAMarker()
>                         .states(AAMarkerStates()
>                             .hover(AAMarkerHover()
>                                 .enabled(false))))
>                     .data([7.0, 6.9, 2.5, 14.5, 18.2, 21.5, 5.2, 26.5, 23.3, 45.3, 13.9, 9.6])
>             ])
>     }
> ```
> 
> ![](https://user-images.githubusercontent.com/16357599/85395829-52a35300-b583-11ea-862b-9303b034da14.png)

我是折线图已经显示，然后需要隐藏十字线，不是一开始就要隐藏。这样写不行吧
