### ISSUE TITLE
大佬，有没有办法实现这种自定义选中线？

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit-Swift#372]
![1658116335236](https://user-images.githubusercontent.com/11735014/179442867-69876a47-0d87-498d-adea-4bfd9fc3aa1f.jpg)
我之前的思路是，利用库的moveOverEventMessage代理回调来获取X的坐标，然后再根据图表的高度和位置来确定Y坐标，再动态的去调整这个自定义的选中线图片来产生一种联动的效果，不知道有没有更好的办法来实现这种效果？库里面的选中线是否支持自定义呢？

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/1369

**Comment by AAChartModel** [comment]
* https://github.com/AAChartModel/AAChartKit/issues/1369

此方法的使用示例代码, 参考此次提交的内容:
* https://github.com/AAChartModel/AAChartKit-Swift-Pro/commit/4214c18c532f959d210f6f20544cd59010f0eec9

此提交内容, 在 AAChartKit-Swift-Pro 的 demo 中可以找到. demo 链接如下:
* https://github.com/AAChartModel/AAChartKit-Swift-Pro

**Comment by chenhongxin2015** [comment]
这个问题解决了吗？

**Comment by jerry178063** [comment]
> 这个问题解决了吗？

根据点击坐标 自己画
