### ISSUE TITLE
雙X軸功能

### ISSUE THREAD

**Issue by CLWuAIP** [AAChartModel/AAChartKit-Swift#376]
請教~

在AASeriesElement.swift裡面只有開啟双y軸設定功能，可否幫忙在Git project上加入双x軸? 以便我Package Dependencies時，不必手動加關於x軸。
========================
**public var xAxis: Int?** // add
public var yAxis: Int?

**@discardableResult // add
public func xAxis(_ prop: Int) -> AASeriesElement {
        xAxis = prop
        return self
 }**

@discardableResult
public func yAxis(_ prop: Int) -> AASeriesElement {
        yAxis = prop
        return self
 }

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit-Swift/issues/169

**Comment by CLWuAIP** [comment]
抱歉，問題沒描述清楚。
我想要的是double x-axis的"刻度"是各自獨立的，所以才需要加以上的code。

感謝回應~

**Comment by AAChartModel** [comment]
已在此次提交中添加
* https://github.com/AAChartModel/AAChartKit-Swift/commit/d4bc24b73f46a1a2df4bfff733a08decdcc54310

更新 `AAChartKit-Swift `至**最新内容**即可使用.

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/359
