### ISSUE TITLE
急救：折线图，Y轴，设置最大值max，最小值min和间隔interval后，图表显示不完全

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#377]
代码和效果图如下图
![image](https://user-images.githubusercontent.com/12290214/183049590-200b7912-8f98-4f2d-8c97-d308c8294a7c.png)
![image](https://user-images.githubusercontent.com/12290214/183050047-7a52cfaa-d84c-41fd-8ba3-aaa02104c258.png)

正常情况，折线图最大值设置了4.55，Y轴上面应该还有一个刻度8.60，但奇怪的是没有绘制出来
已经困扰很多天了，oc的版本我也问了，但是没有回应

**Comment by jb522185660** [comment]
您好，解决了吗？

**Comment by lhpkxywm** [comment]
> 您好，解决了吗？

没解决，采用其它方式实现最终效果了。
