### ISSUE TITLE
折线图填充色失效

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#378]
![image](https://user-images.githubusercontent.com/12290214/183430883-73dd159b-a1b8-464e-9e22-2fb5a09fd448.png)
照着demo写的，之前一直好用，更新到7.2之后没有效果了，咋回事儿呢

**Comment by AAChartModel** [comment]
```swift
        chartType              = .line
```

折线图本来就没有填充效果, 你需要将图表类型设置为 area , 这个才是折线区域填充图.
