### ISSUE TITLE
填充效果不希望以0作为分界线

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#379]
而是从折线一直向下填充到最下面
如下图绘制的斜线部分
![image](https://user-images.githubusercontent.com/12290214/183553536-40219aa5-ba98-45ec-abb1-cf9cf1f8d8a9.png)

**Comment by AAChartModel** [comment]
参考在线文档:
* https://api.highcharts.com/highcharts/series.area.threshold

**Comment by AAChartModel** [comment]
打开在线编辑器:
* https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/area-threshold/

如下配置 options

```js
Highcharts.chart('container', {
    chart: {
        type: 'area'
    },

    title: {
        text: 'Threshold is set to 100'
    },

    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },
    series: [{
        threshold: -300,
        color:'red',
        fillColor:'rgba(255,0,0,0.3)',
        data: [-29.9, -71.5, -106.4, -129.2, -144.0, -176.0, -135.6, -148.5, -216.4,- 194.1, 9-5.6, -54.4]
    }]
});
```

可得图表:
<img width="673" alt="截屏2022-08-09 下午1 46 32" src="https://user-images.githubusercontent.com/16357599/183573827-36d71945-06d4-4015-8e54-7f449d791ce1.png">

**Comment by AAChartModel** [comment]
对应在在 AAChartKit-Swift 中的 AASeriesElement 中的

```swift
 //The threshold, also called zero level or base level.
 //For line type series this is only used in conjunction with negativeColor. 
 //default：0.
    public var threshold: Float?          
```
