### ISSUE TITLE
怎么设置饼图的title位置？

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit-Swift#380]
大佬，我有两个问题：
1.怎么设置饼图的title位置呢？
2.怎么取消饼图的点击蒙版效果？
这个灰色的蒙版怎么去掉，我能试的都试了就去去不掉这个灰色蒙版，代码如下：
![IMG_4445](https://user-images.githubusercontent.com/11735014/183810815-4bc06ec8-461b-4b56-ac80-afc7f1f8f1f0.jpg)
![IMG_4446](https://user-images.githubusercontent.com/11735014/183810858-2f717875-7620-48f7-94db-6d30bf74cb4d.jpg)

```swift
let pieModel = AAChartModel()
               .chartType(.pie)
               .backgroundColor(AAColor.white)
               .title("睡眠比例")
               .titleStyle(AAStyle().fontSize(12).position("bottom"))
               .xAxisLabelsEnabled(false)
               .tooltipEnabled(false)
               .legendEnabled(false)
               .dataLabelsEnabled(false)//是否直接显示扇形图数据
               .series([
                   AASeriesElement()
                       .name("睡眠比例")
                       .innerSize("60%")//内部圆环半径大小占比(内部圆环半径/扇形图半径),
                       .allowPointSelect(false)
                       .states(AAStates()
                        .select(AASelect()
                           .enabled(false))
                           .hover(AAHover()
                               .enabled(false)//禁用点击区块之后出现的半透明遮罩层
                       ))
                       .data([
                           ["入睡"  ,awakeDuration],
                           ["浅度睡眠",lightDuration],
                           ["深度睡眠",deepDuration],
                           ["清醒"    ,awakeDuration],
                       ]).colors(colorArr)
               ])
```

**Comment by AAChartModel** [comment]
参考相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/949

**Comment by AAChartModel** [comment]
> 怎么设置饼图的title位置？

参考:

* https://github.com/AAChartModel/AAChartKit/issues/986

**Comment by Maxcucurbit** [comment]
> > 怎么设置饼图的title位置？
> 
> 参考:
> 
> * [请问把标题设置在扇形的中心点怎么适配啊 AAChartKit#986](https://github.com/AAChartModel/AAChartKit/issues/986)
pro版本貌似还没有支持标题位置属性
.textAlign
.verticalAlign
            .xSet
              .ySet

**Comment by AAChartModel** [comment]
> pro版本貌似还没有支持标题位置属性

这不是有吗?

```swift
public class AATitle: AAObject {
    public var text: String?
    public var style: AAStyle?
    public var align: String?
    public var verticalAlign: String?
    public var x: Float?
    public var y: Float?
    public var userHTML: Bool?
    
    @discardableResult
    public func text(_ prop: String?) -> AATitle {
        text = prop
        return self
    }
    
    @discardableResult
    public func style(_ prop: AAStyle?) -> AATitle {
        style = prop
        return self
    }
    
    @discardableResult
    public func align(_ prop: AAChartAlignType?) -> AATitle {
        align = prop?.rawValue
        return self
    }
    
    @discardableResult
    public func verticalAlign(_ prop: AAChartVerticalAlignType?) -> AATitle {
        verticalAlign = prop?.rawValue
        return self
    }
    
    @discardableResult
    public func x(_ prop: Float?) -> AATitle {
        x = prop
        return self
    }
    
    @discardableResult
    public func y(_ prop: Float?) -> AATitle {
        y = prop
        return self
    }
    
    @discardableResult
    public func userHTML(_ prop: Bool?) -> AATitle {
        userHTML = prop
        return self
    }
    
    public override init() {
        
    }
    
}
```

**Comment by Maxcucurbit** [comment]
> > pro版本貌似还没有支持标题位置属性
> 
> 这不是有吗?
> 
> ```swift
> public class AATitle: AAObject {
>     public var text: String?
>     public var style: AAStyle?
>     public var align: String?
>     public var verticalAlign: String?
>     public var x: Float?
>     public var y: Float?
>     public var userHTML: Bool?
>     
>     @discardableResult
>     public func text(_ prop: String?) -> AATitle {
>         text = prop
>         return self
>     }
>     
>     @discardableResult
>     public func style(_ prop: AAStyle?) -> AATitle {
>         style = prop
>         return self
>     }
>     
>     @discardableResult
>     public func align(_ prop: AAChartAlignType?) -> AATitle {
>         align = prop?.rawValue
>         return self
>     }
>     
>     @discardableResult
>     public func verticalAlign(_ prop: AAChartVerticalAlignType?) -> AATitle {
>         verticalAlign = prop?.rawValue
>         return self
>     }
>     
>     @discardableResult
>     public func x(_ prop: Float?) -> AATitle {
>         x = prop
>         return self
>     }
>     
>     @discardableResult
>     public func y(_ prop: Float?) -> AATitle {
>         y = prop
>         return self
>     }
>     
>     @discardableResult
>     public func userHTML(_ prop: Bool?) -> AATitle {
>         userHTML = prop
>         return self
>     }
>     
>     public override init() {
>         
>     }
>     
> }
> ```

完美解决多谢
