### ISSUE TITLE
折线图有三条线，想禁止其中两条线的点击和拖动

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#383]
当点击或者拖动图表时，无论手指在哪，均视为点击或者拖动了其中的一条线，另两条线仅做展示
AADataElement里没找到对应的属性
如下图
![image](https://user-images.githubusercontent.com/12290214/184093436-e66d5612-3945-4228-9526-4e4ee77e7def.png)
虽然手指停留在黄色线的十字线处的位置，但是希望十字线的位置在红色箭头处。

**Comment by AAChartModel** [comment]
参考相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/903

**Comment by AAChartModel** [comment]
关键属性:

```swift
    public var enableMouseTracking: Bool?

```
