### ISSUE TITLE
折线图有多条折线，点击任意位置，希望三条线都被同时选中

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#385]
如图
![image](https://user-images.githubusercontent.com/12290214/184307697-2a9f1ce1-35d6-4807-87a6-db6813ae8777.png)
三条线都显示高亮点

**Comment by AAChartModel** [comment]
```swift
public class AATooltip: AAObject {
...
...
    public var shared: Bool?
...
...
```

设置 AATooltip 的 shared 属性, 即可使得三条线都被同时选中.
