### ISSUE TITLE
折线图填充遮挡问题

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#386]
![image](https://user-images.githubusercontent.com/12290214/185296216-d1845903-9d29-49fb-966c-5363471c01de.png)
如图
为了避免填充遮挡黄线和黑线，我把红线设置在了最外层，但是这样红线本身又会被黄线和黑线遮挡。能不能单独给填充块设置zindex呢，也就是线条的zindex和填充块的zindex能不能分开。
还有就是填充部分遮挡住了与X轴水平的网格线，我在aaxaxis和aayaxix里都没有找到有对应的zindex.

**Comment by AAChartModel** [comment]
> 我在aaxaxis和aayaxix里都没有找到有对应的zindex.

```shell
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  AAInfographics (7.3.0) successfully published
 📅  August 18th, 00:09
 🌎  https://cocoapods.org/pods/AAInfographics
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

更新 `AAInfographics` 至最新版本 `7.3.0`, 即可使用

**Comment by AAChartModel** [comment]
> 能不能单独给填充块设置zindex呢，也就是线条的zindex和填充块的zindex能不能分开

红线和填充块, 属于同一个图层, 不支持单独设置 zIndex. 


参考:

* https://api.highcharts.com/highcharts/series.area.zIndex

可知, 一个 `area` 元素(对应 `AASeriesElement`) 只有一个 `zIndex` 属性.

**Comment by AAChartModel** [comment]
只能参考此方法

* https://github.com/AAChartModel/AAChartCore-Kotlin/issues/131

将同一个区域填充图, 进行非常规的拆分.

**Comment by AAChartModel** [comment]
![IMG_0935](https://user-images.githubusercontent.com/16357599/185312438-207c1c8c-6793-48d5-a39b-69bead7dc96f.jpg)

折线填充图支持设置**透明渐变色**填充, 你可以试试透明渐变效果, 应该就可以直接实现上图类似效果:

* 填充图的折线不被网格线遮挡
* 同时可以透过填充色区域看到网格线(填充色区域不遮挡网格线)

**Comment by AAChartModel** [comment]
多组数据折线填充图, 一般都会有透明效果, 很少是完全不透明的填充图. 你或许可以考虑下, 你的需求稿是否从设计上就有可改进的地方.
