### ISSUE TITLE
不想给折线图填充色效果该怎么设置

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#389]
设置成nsnull还是会默认填充颜色
![image](https://user-images.githubusercontent.com/12290214/185821226-3b376655-1ef4-4a60-9da4-5196df5c7eaf.png)
如果设置成透明色，它又会遮挡住水平网格线。

**Comment by AAChartModel** [comment]
可以直接设置图表类型为 `.line` 或者 `.spline`

**Comment by lhpkxywm** [comment]
> 可以直接设置图表类型为 `.line` 或者 `.spline`

我一共有三条线，棋钟有一条是需要填充的，另外两条不需要，这样设置似乎都没有填充色了。不行的

**Comment by AAChartModel** [comment]
> 我一共有三条线，棋钟有一条是需要填充的，另外两条不需要，这样设置似乎都没有填充色了。不行的


示例代码

```swift
  private func configurePolarChartMixedChart() -> AAChartModel {
        AAChartModel()
            .chartType(.column)
            .polar(true)
            .series([
                AASeriesElement()
                    .name("Column")
                    .type(.column)
                    .data([8, 7, 6, 5, 4, 3, 2, 1])
                ,
                AASeriesElement()
                    .name("Line")
                    .type(.line)
                    .data([1, 2, 3, 4, 5, 6, 7, 8])
                ,
                AASeriesElement()
                    .name("Area")
                    .type(.area)
                    .data([1, 8, 2, 7, 3, 6, 4, 5])
                ,
            ])
    }
```

由上可知, 每个 AASeriesElement 都支持单独设置图表类型, 具体查看 demo 中的混合图表示例.

**Comment by lhpkxywm** [comment]
> > 我一共有三条线，棋钟有一条是需要填充的，另外两条不需要，这样设置似乎都没有填充色了。不行的
> 
> 示例代码
> 
> ```swift
>   private func configurePolarChartMixedChart() -> AAChartModel {
>         AAChartModel()
>             .chartType(.column)
>             .polar(true)
>             .series([
>                 AASeriesElement()
>                     .name("Column")
>                     .type(.column)
>                     .data([8, 7, 6, 5, 4, 3, 2, 1])
>                 ,
>                 AASeriesElement()
>                     .name("Line")
>                     .type(.line)
>                     .data([1, 2, 3, 4, 5, 6, 7, 8])
>                 ,
>                 AASeriesElement()
>                     .name("Area")
>                     .type(.area)
>                     .data([1, 8, 2, 7, 3, 6, 4, 5])
>                 ,
>             ])
>     }
> ```
> 
> 由上可知, 每个 AASeriesElement 都支持单独设置图表类型, 具体查看 demo 中的混合图表示例.

不行，我将A(zIndex=4)B(zIndex=3)设置成了.line，C(zIndex=1)设置成了.areaspline，然后将aaYAxis的gridIndex设置成了2，但是水平网格线依然被C的填充区域挡住了，看不到
![image](https://user-images.githubusercontent.com/12290214/185845174-c96c735c-6e5d-4d28-816d-af1dab1fb9c8.png)

**Comment by AAChartModel** [comment]
>  水平网格线依然被C的填充区域挡住

有一点我不太明白, 你既然不希望网格线被挡住, 为什么渐变色不设置成这种透明渐变色?

* https://github.com/AAChartModel/AAChartKit/issues/921

是因为多组透明渐变色叠加起来, 导致透明度不够? 还是什么其他原因?

**Comment by AAChartModel** [comment]
* https://github.com/AAChartModel/AAChartKit/issues/921

对应的 Swift 版本代码如下:

```swift
    private func configureNegativeColorMixedAreasplineChart() -> AAChartModel {
        AAChartModel()
            .chartType(.areaspline)
            .legendEnabled(false)
            .dataLabelsEnabled(false)
            .markerRadius(5)
            .markerSymbolStyle(.innerBlank)
            .yAxisGridLineWidth(1)
            .series([
                AASeriesElement()
                    .name("Column")
                    .data([
                        +7.0, +6.9, +2.5, +14.5, +18.2, +21.5, +5.2, +26.5, +23.3, +45.3, +13.9, +9.6,
                        -7.0, -6.9, -2.5, -14.5, -18.2, -21.5, -5.2, -26.5, -23.3, -45.3, -13.9, -9.6,
                    ])
                    .lineWidth(5)
                    .color(AARgba(30, 144, 255, 1.0))
                    .negativeColor(AARgba(255, 0, 0, 1.0))
                    .fillColor(AAGradientColor.linearGradient(
                        direction: .toTop,
                        stops: [
                            [0.0, AARgba(30, 144, 255, 0.0)],//颜色字符串设置支持十六进制类型和 rgba 类型
                            [0.5, AARgba(30, 144, 255, 0.0)],
                            [1.0, AARgba(30, 144, 255, 0.6)]
                        ]
                    ))
                    .negativeFillColor(AAGradientColor.linearGradient(
                        direction: .toTop,
                        stops: [
                            [0.0, AARgba(255, 0, 0, 0.6)],//颜色字符串设置支持十六进制类型和 rgba 类型
                            [0.5, AARgba(255, 0, 0, 0.0)],
                            [1.0, AARgba(255, 0, 0, 0.0)]
                        ]
                    ))
                    .threshold(0)//default:0
            ])
    }
```

**Comment by lhpkxywm** [comment]
> > 水平网格线依然被C的填充区域挡住
> 
> 有一点我不太明白, 你既然不希望网格线被挡住, 为什么渐变色不设置成这种透明渐变色?
> 
> * [基准线以下异色混合曲线填充图 AAChartKit#921](https://github.com/AAChartModel/AAChartKit/issues/921)
> 
> 是因为多组透明渐变色叠加起来, 导致透明度不够? 还是什么其他原因?

设置了透明色，没有效果啊，还是被挡住啊。我最开始就是给ABC分别设置了透明度为0的白色，但是还是被挡住

**Comment by lhpkxywm** [comment]
> > 水平网格线依然被C的填充区域挡住
> 
> 有一点我不太明白, 你既然不希望网格线被挡住, 为什么渐变色不设置成这种透明渐变色?
> 
> * [基准线以下异色混合曲线填充图 AAChartKit#921](https://github.com/AAChartModel/AAChartKit/issues/921)
> 
> 是因为多组透明渐变色叠加起来, 导致透明度不够? 还是什么其他原因?

因为设置了透明度为0.还是会盖住水平网格线，并不会因为填充色变成透明，填充区域就变成透明的

**Comment by AAChartModel** [comment]
你有设计稿吗? 想知道你的设计稿是什么样子的

**Comment by AAChartModel** [comment]
![](https://user-images.githubusercontent.com/16357599/185312438-207c1c8c-6793-48d5-a39b-69bead7dc96f.jpg)


比如上图的支付宝基金截图, 想知道你的需求图表和支付宝的基金图表究竟有何差异.  因为单纯就支付宝的基金图表来看, 使用 AAChartKit 来绘制, 似乎并不需要做额外的许多工作.

**Comment by lhpkxywm** [comment]
对，和支付宝这个一样。问题在于，在填充区域内的水平网格虚线会被挡住显示不出来。如果把网格虚线的gridIndex提高，就会挡住数据折线。

**Comment by lhpkxywm** [comment]
> ![](https://user-images.githubusercontent.com/16357599/185312438-207c1c8c-6793-48d5-a39b-69bead7dc96f.jpg)
> 
> 比如上图的支付宝基金截图, 想知道你的需求图表和支付宝的基金图表究竟有何差异. 因为单纯就支付宝的基金图表来看, 使用 AAChartKit 来绘制, 似乎并不需要做额外的许多工作.

对，和支付宝这个一样。问题在于，在填充区域内的水平网格虚线会被挡住显示不出来。如果把网格虚线的gridIndex提高，就会挡住数据折线。

**Comment by lhpkxywm** [comment]
> > ![](https://user-images.githubusercontent.com/16357599/185312438-207c1c8c-6793-48d5-a39b-69bead7dc96f.jpg)
> > 比如上图的支付宝基金截图, 想知道你的需求图表和支付宝的基金图表究竟有何差异. 因为单纯就支付宝的基金图表来看, 使用 AAChartKit 来绘制, 似乎并不需要做额外的许多工作.
> 
> 对，和支付宝这个一样。问题在于，在填充区域内的水平网格虚线会被挡住显示不出来。如果把网格虚线的gridIndex提高，就会挡住数据折线。

已解决，但是必须多画一根专门设置填充色的线。

**Comment by AAChartModel** [comment]
> 已解决，但是必须多画一根专门设置填充色的线。

配置 AAChartModel

```swift
    private func configureMultiLevelStopsArrGradientColorMixedChart() -> AAChartModel {
        var randomNumArrA = [Any]()
        var randomNumArrB = [Any]()
        var y1 = 0.0
        var y2 = 0.0
        let Q = Int(arc4random() % 50)
        let range = 129
        for  x in 0 ..< range {
            y1 = sin(Double(Q) * (Double(x) * Double.pi / 180)) + Double(x) * 2.0 * 0.01
            y2 = cos(Double(Q) * (Double(x) * Double.pi / 180)) + Double(x) * 3.0 * 0.01
            randomNumArrA.append(y1)
            randomNumArrB.append(y2)
        }
        
        let redStopsArr = [
            [0.0, AARgba(255, 0, 0, 1.0)],//颜色字符串设置支持十六进制类型和 rgba 类型
            [0.2, AARgba(255, 0, 0, 0.2)],
            [0.4, AARgba(255, 0, 0, 0.1)],
            [0.6, AARgba(255, 0, 0, 0.05)],
            [0.8, AARgba(255, 0, 0, 0.01)],
            [1.0, AAColor.clear]
        ]
        
        
        let gradientRedColorDic = AAGradientColor.linearGradient(
            direction: .toBottom,
            stops: redStopsArr
        )

        return AAChartModel()
            .chartType(.areaspline)
            .stacking(.normal)
           // .backgroundColor(AAColor.black)
            .colorsTheme(["#1e90ff","#04d69f","#ef476f","#ffd066",])
            .dataLabelsEnabled(false)
            .markerSymbol(.circle)
            .markerRadius(5)
            .markerSymbolStyle(.innerBlank)
            .yAxisGridLineWidth(0.5)
            .xAxisGridLineWidth(0.5)
            .series([
                AASeriesElement()
                    .name("2017")
                    .type(.spline)
                    .lineWidth(6)
                    .data(randomNumArrA),
                AASeriesElement()
                    .name("2018")
                    .type(.spline)
                    .lineWidth(6)
                    .data(randomNumArrB),
                AASeriesElement()
                    .name("2020")
                    .fillColor(gradientRedColorDic)
                    .lineWidth(6)
                    .threshold(-4)
                    .data(randomNumArrA),
            ])
    }
```

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-23 at 10 46 01](https://user-images.githubusercontent.com/16357599/186061067-b8c9c0e3-abbc-4509-9255-7a5b4146eda7.png)

**Comment by AAChartModel** [comment]
修改背景色为黑色, 能更明显的看到透明渐变色底部的网格线, 图表效果如下图:
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-23 at 11 08 05](https://user-images.githubusercontent.com/16357599/186061340-e0125094-8608-4ba9-abe9-290524d97b2d.png)

**Comment by AAChartModel** [comment]
由上可知, 类似设置半透明渐变色:

```swift
let redStopsArr = [
            [0.0, AARgba(255, 0, 0, 1.0)],//颜色字符串设置支持十六进制类型和 rgba 类型
            [0.2, AARgba(255, 0, 0, 0.2)],
            [0.4, AARgba(255, 0, 0, 0.1)],
            [0.6, AARgba(255, 0, 0, 0.05)],
            [0.8, AARgba(255, 0, 0, 0.01)],
            [1.0, AAColor.clear]
        ]
        
        
        let gradientRedColorDic = AAGradientColor.linearGradient(
            direction: .toBottom,
            stops: redStopsArr
        )
```
可以实现类似支付宝的图表效果.并且不需要"多画一根专门设置填充色的线"。

**Comment by AAChartModel** [comment]
回到问题,

> 不想给折线图填充色效果该怎么设置

```swift
   AASeriesElement()
                    .name("2020")
                    .fillColor(AAColor.clear)
                    .lineWidth(6)
                    .threshold(-4)
                    .data(randomNumArrA),
```

如上设置 `fillColor` 为  `AAColor.clear` 即可. 

不过为了实现支付宝图表的类似效果, 这样设置的思路可能有点走偏了. 应该用不了非常规设置.   如上常规的配置半透明渐变色即可.
