### ISSUE TITLE
你好，请问饼图的图例文字如何自定义

### ISSUE THREAD

**Issue by DeraDream** [AAChartModel/AAChartKit-Swift#391]

**Comment by DeraDream** [comment]
![image](https://user-images.githubusercontent.com/42810994/186338209-223bdfa9-dc34-4b63-ac67-f56c95f11bd2.png)
我没有找到userHTML和formatter选项。还有饼图的点击事件通过下面方法不能关闭。
![image](https://user-images.githubusercontent.com/42810994/186338950-41657dd1-e4c4-4a88-b54c-6d461f79f7a4.png)

**Comment by DeraDream** [comment]
饼图的图例点击事件无法通过上述代码关闭
![IMG_1583](https://user-images.githubusercontent.com/42810994/186339523-af859e93-7ddd-4df2-ae68-b1cc7a791d72.jpg)

**Comment by DeraDream** [comment]
![IMG_1584](https://user-images.githubusercontent.com/42810994/186339646-3b7526ef-981c-4855-9a0c-7d8ead41de17.jpg)
没表述清楚，是饼图的图例点击事件无法通过上述代码关闭

**Comment by DeraDream** [comment]
图例自定义事件我是想做如下效果，百分比的文字我目前无法展示出来
![image](https://user-images.githubusercontent.com/42810994/186339771-3a1e3fdd-355e-4ee9-a545-b9a14502233c.png)

**Comment by AAChartModel** [comment]
配置 AAOptions

```swift
    private func configurePieChartWithSpecialStyleLegend() -> AAOptions {
         let aaChartModel = AAChartModel()
            .chartType(.pie)
            .backgroundColor(AAColor.white)
            .title("LANGUAGE MARKET SHARES JANUARY,2020 TO MAY")
            .subtitle("virtual data")
            .dataLabelsEnabled(true)//是否直接显示扇形图数据
            .yAxisTitle("℃")
            .series([
                AASeriesElement()
                    .name("Language market shares")
                    .innerSize("20%")//内部圆环半径大小占比(内部圆环半径/扇形图半径),
                    .allowPointSelect(true)
                    .states(AAStates()
                        .hover(AAHover()
                            .enabled(false)//禁用点击区块之后出现的半透明遮罩层
                    ))
                    .data([
                        ["Java"  ,67],
                        ["Swift",999],
                        ["Python",83],
                        ["OC"    ,11],
                        ["Go"    ,30],
                    ])
            ])
        
        let aaOptions = aaChartModel.aa_toAAOptions()
        aaOptions.legend?.labelFormat("{name} {percentage:.2f}%")
        
        return aaOptions
    }
```

最终图表
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-25 at 11 32 05](https://user-images.githubusercontent.com/16357599/186568488-70574464-425a-4cff-ab5e-7bf5c9a5c18f.png)

**Comment by DeraDream** [comment]
呃，我在h5上找到了这个属性，但swift版没有，我更新下pod看看。还有如下图的效果，一行固定显示三个，我需要用到H5里面的itemWidth属性去适配屏幕，目前的版本也没有，我更新pod先看看
![](https://user-images.githubusercontent.com/42810994/186339771-3a1e3fdd-355e-4ee9-a545-b9a14502233c.png)

**Comment by AAChartModel** [comment]
> 我需要用到H5里面的itemWidth属性去适配屏幕，目前的版本也没有

这个属性我还没加, 稍后加一下

**Comment by DeraDream** [comment]
好滴，辛苦了。还有图例的点击事件关闭功能我从其他问题里找到的如下代码，但没有生效。
![](https://user-images.githubusercontent.com/42810994/186338950-41657dd1-e4c4-4a88-b54c-6d461f79f7a4.png)

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/393

**Comment by AAChartModel** [comment]
> > 我需要用到H5里面的itemWidth属性去适配屏幕，目前的版本也没有
> 
> 这个属性我还没加, 稍后加一下

已在此次提交中添加 
* https://github.com/AAChartModel/AAChartKit-Swift/commit/8fa73019dbeec9d105a9b651986d07f3b8077d45

**Comment by DeraDream** [comment]
🐂🍺PLUS  我试试先
