### ISSUE TITLE
需求希望折线图最后一个有数据的数据点显示一个动态的小圆点

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#394]
如图，想要在最后一个有效的数据点上添加小圆点。
![image](https://user-images.githubusercontent.com/12290214/186587182-eb4e5e3e-8fb6-4fbc-bc38-b67274c6d3d7.png)

我尝试在最后一个有效的数据点上添加AADataLabel,但是当数据刷新，使用chartView.aa_updateChart(options: aaOptions, redraw: true)重绘图表后，小圆点也被重复的绘制了。如下图
![image](https://user-images.githubusercontent.com/12290214/186595148-6fa40b5f-4bcb-4023-a3cb-1fd155deb830.png)

并且最好希望小圆点每隔一秒显示or隐藏，或者可以用一个gif图片代替，有办法么？

**Comment by AAChartModel** [comment]
问题已解决, 参考此次的提交内容
* https://github.com/AAChartModel/AAChartKit-Swift/commit/71bea16d4910c98ec1dd6116afbbe9f0b1e52db9

**Comment by AAChartModel** [comment]
参考问题:
* https://www.highcharts.com/forum/viewtopic.php?t=44985

才考在线示例:
* https://jsfiddle.net/BlackLabel/f21bk0mc/

**Comment by lhpkxywm** [comment]
> 参考问题:
> 
> * https://www.highcharts.com/forum/viewtopic.php?t=44985
> 
> 参考在线示例:
> 
> * https://jsfiddle.net/BlackLabel/f21bk0mc/

十分感动！下载最新demo就能看到效果了是吧

**Comment by AAChartModel** [comment]
是的，使用示例在 AAChartKit-Swift 最新的demo中

**Comment by lhpkxywm** [comment]
> 是的，使用示例在 AAChartKit-Swift 最新的demo中

执行update语句后，出现多个圆点怎么破？
![image](https://user-images.githubusercontent.com/12290214/187621181-7e19534d-0c01-462d-b52d-e58e23d1bbc7.png)
