### ISSUE TITLE
大佬，看图，关于tooltip位置配置

### ISSUE THREAD

**Issue by DeraDream** [AAChartModel/AAChartKit-Swift#400]
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/42810994/187384772-2cf7be74-a50b-42db-a050-1b50446e7019.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/42810994/187384874-608253f7-3bf0-4621-9dfa-f7364ade136d.png">

**Comment by DeraDream** [comment]
` .positioner("""
                    function (labelWidth, labelHeight, point) {
                            let position = {};
                            position["x"] = point.plotX+20;
                            position["y"] = 50;
                            return position;
                        }

                    """)`

我使用该代码将tooltip固定在某个位置，但滑到最右边或者最左边时，tooltip会被隐藏，没法像之前那样自动判断。
![1801661847576_ pic](https://user-images.githubusercontent.com/42810994/187387058-11f17909-8b98-463d-9756-dfd412107dc8.jpg)

用滑动回调判断位置来重写tooltips的位置吗

**Comment by AAChartModel** [comment]
> 但滑到最右边或者最左边时，tooltip会被隐藏

参考:  
* https://github.com/AAChartModel/AAChartKit/issues/1033

查看此处的关键代码:

```objc
 CGFloat screenWidth = self.view.frame.size.width;
    
    NSString *positionerStr = [NSString stringWithFormat:@AAJSFunc(function (labelWidth, labelHeight, point) {
        let xPosition = point.plotX;
        let maxXPosition = %@ - 388;
        if (xPosition >= maxXPosition) {
            xPosition = maxXPosition
        }
        let position = {};
        position["x"] = xPosition;
        position["y"] = 50;
        return position;
    }), @(screenWidth)];
    
```

此处通过字符串拼接的方式, 将 screenWidth 传入了 JS 的函数中, 从而避免了tooltip 会超出边界.

**Comment by AAChartModel** [comment]
> 没法像之前那样自动判断

因为重写 positioner 会覆盖原有的内部逻辑.

**Comment by AAChartModel** [comment]
附言: 

粘贴代码块时, 请使用标准的 `Markdown` 语法, 使之高亮, 便于阅读. 目前你粘贴的代码块格式完全不对.

`Markdown` 代码块高亮语法, 参考GitHub 官方手册: 
* https://docs.github.com/cn/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by DeraDream** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/42810994/187393820-932b2d80-3670-4a74-9111-509467d08cf6.png">

**Comment by DeraDream** [comment]
上Markdown我不太熟练，我试试。。。
'''
     function (labelWidth, labelHeight, point) {
                                let position = {};
                              position["x"] = point.plotX;
                                position["y"] = 20;
                                return position;
         }
'''

**Comment by DeraDream** [comment]
Markdown我看看，上图的效果能做吗

**Comment by DeraDream** [comment]
默认好像是悬浮框根据手指触摸或者点击的位置去显示的，悬浮框在底部遮住了X轴是因为点击了蓝色区域底部

**Comment by DeraDream** [comment]
> > 但滑到最右边或者最右边的时候，提示会被隐藏
> 
> 参考：
> 
> * [支持绘图区外的复杂工具提示自定义 样式AAChartKit#1033](https://github.com/AAChartModel/AAChartKit/issues/1033)
> 
> 查看这里的关键代码：
> 
> ```objc
>  CGFloat screenWidth = self.view.frame.size.width;
>     
>     NSString *positionerStr = [NSString stringWithFormat:@AAJSFunc(function (labelWidth, labelHeight, point) {
>         let xPosition = point.plotX;
>         let maxXPosition = %@ - 388;
>         if (xPosition >= maxXPosition) {
>             xPosition = maxXPosition
>         }
>         let position = {};
>         position["x"] = xPosition;
>         position["y"] = 50;
>         return position;
>     }), @(screenWidth)];
>     
> ```
> 
> 在这里通过电影的肖像的方式，将屏幕宽度激发了 JS 的角色中，从而避免了工具提示会的某个地方。

这种是定死在一个位置了，我和产品商量了，要固定在一个水平面，跟随手指点击或者滑动去显示，滑动到边界也要自动判断显示到另一边。

**Comment by AAChartModel** [comment]
悬浮框支持分开显示, 参考在线示例:

* https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/split/

在 tooltip 是 shared 的情况下, 让 tooltip 紧跟某一个选中的点, 这个不好做, 因为没法获得手指的坐标, 进而无法判断和哪一个点离得更近

**Comment by AAChartModel** [comment]
分开显示的话, 默认是单独的 tooltip 紧跟对应的选中的点.

**Comment by DeraDream** [comment]
我用的是swift，运行我发现定死在左上角了。。。
<img width="495" alt="image" src="https://user-images.githubusercontent.com/42810994/187401816-15d3925e-5d06-4f49-a46c-6025881fde18.png">

![1811661851709_ pic](https://user-images.githubusercontent.com/42810994/187401935-eb59b350-17c7-4ffd-b6a2-eb96381de3bc.jpg)

实例代码的@AAJSFunc我没找到。

**Comment by AAChartModel** [comment]
```swift
private func customPlotAreaOutsideComlicatedTooltipStyle() -> AAOptions {
    let categoriesArr = [
        "11 月 01 日",
        "11 月 02 日",
        "11 月 03 日",
        "11 月 04 日",
        "11 月 05 日",
        "11 月 06 日",
        "11 月 07 日",
        "11 月 08 日",
        "11 月 09 日",
        
        "11 月 10 日",
        "11 月 11 日",
        "11 月 12 日",
        "11 月 13 日",
        "11 月 14 日",
        "11 月 15 日",
        "11 月 16 日",
        "11 月 17 日",
        "11 月 18 日",
        "11 月 19 日",

        "11 月 20 日",
        "11 月 21 日",
        "11 月 22 日",
        "11 月 23 日",
        "11 月 24 日",
        "11 月 25 日",
        "11 月 26 日",
        "11 月 27 日",
        "11 月 28 日",
        "11 月 29 日",
        "11 月 30 日",
        
        "12 月 01 日",
        "12 月 02 日",
        "12 月 03 日",
        "12 月 04 日",
        "12 月 05 日",
        "12 月 06 日",
        "12 月 07 日",
        "12 月 08 日",
        "12 月 09 日",
        
        "12 月 10 日",
        "12 月 11 日",
        "12 月 12 日",
        "12 月 13 日",
        "12 月 14 日",
        "12 月 15 日",
        "12 月 16 日",
        "12 月 17 日",
        "12 月 18 日",
        "12 月 19 日",

        "12 月 20 日",
        "12 月 21 日",
        "12 月 22 日",
        "12 月 23 日",
        "12 月 24 日",
        "12 月 25 日",
        "12 月 26 日",
        "12 月 27 日",
        "12 月 28 日",
        "12 月 29 日",
        "12 月 30 日",
        "12 月 31 日",
    ]
    
    let aaChartModel = AAChartModel.init()
    .chartType(AAChartType.column)
    .categories(categoriesArr)
    .series([
        AASeriesElement.init()
            .name("个人徒步数据统计")
            .color(AARgba(235, 88, 40, 1.0))
            .borderRadiusTopLeft(3)
            .borderRadiusTopRight(3)
            .data([
                1300.988, 900.699, 1000.089, 1100.965, 1000.534, 1400.523, 1800.254, 1900.377, 2100.523, 2500.256, 2600.555, 2800.366,
                1300.988, 900.699, 1000.089, 1100.965, 1000.534, 1400.523, 1800.254, 1900.377, 2100.523, 2500.256, 2600.555, 2800.366,
                1300.988, 900.699, 1000.089, 1100.965, 1000.534, 1400.523, 1800.254, 1900.377, 2100.523, 2500.256, 2600.555, 2800.366,
                1300.988, 900.699, 1000.089, 1100.965, 1000.534, 1400.523, 1800.254, 1900.377, 2100.523, 2500.256, 2600.555, 2800.366,
                1300.988, 900.699, 1000.089, 1100.965, 1000.534, 1400.523, 1800.254, 1900.377, 2100.523, 2500.256, 2600.555, 2800.366,
            ]),
    ])

    let aaOptions = aaChartModel.aa_toAAOptions()

    aaOptions.xAxis?
        .crosshair(AACrosshair.init()
            .color(AARgba(209, 209, 209, 1.0))
            .dashStyle(AAChartLineDashStyleType.longDash)
            .width(3))

//    aaOptions.yAxis
//        .top("30%")//https://api.highcharts.com/highcharts/yAxis.top
//        .height("70%")//https://api.highcharts.com/highcharts/yAxis.height

    let screenWidth = UIScreen.main.bounds.size.width

    let positionerStr = """
    function (labelWidth, labelHeight, point) {
            let xPosition = point.plotX;
            let maxXPosition = \(screenWidth) - 288;
            if (xPosition >= maxXPosition) {
                xPosition = maxXPosition
            }
            let position = {};
            position["x"] = xPosition;
            position["y"] = 50;
            return position;
        }
    """

    aaOptions.tooltip?
        .useHTML(true)
        .headerFormat("总计<br/>")
        .pointFormat(#"<span style=\"color:black;font-weight:bold;font-size:38px\">{point.y} </span> 步<br/>"#)
        .footerFormat("2020 年 {point.x} ")
        .valueDecimals(2)//设置取值精确到小数点后几位
        .backgroundColor(AARgba(242, 242, 242, 1.0))
        .borderWidth(0)
//        .shape("square")
        .style(AAStyle(color: AARgba(132, 132, 132, 1.0), fontSize: 28))
        .positioner(positionerStr)

    return aaOptions
}
```

如上配置 AAOptions , 在你的项目中试试效果.

**Comment by DeraDream** [comment]
例如我当前iphone 13 pro屏幕宽度是390,390-288 = 102，X值大于102就直接变更为102了  向右滑就卡死不动了，向左滑不进判断就能动，这个值不对

**Comment by DeraDream** [comment]
![image](https://user-images.githubusercontent.com/42810994/187465459-47676327-d9c2-4338-b8dd-3d88bb6a80f5.png)
我最终是这样写的，左滑右滑都写了个判断，到边界是可以自动转换到绿线另一边显示，但在中间滑不进判断时显示框在绿线右侧，压住了一点绿线，我给他加了20，目前在iphone 13 pro上是可以完美适配的，但不知道有没有更好的函数公式可以去代替。

![4061661870346_ pic](https://user-images.githubusercontent.com/42810994/187466313-48538a53-c651-4fb5-bd4a-67614ce6a58c.jpg)

![4071661870346_ pic](https://user-images.githubusercontent.com/42810994/187466336-5d3bc29b-a84a-4773-82aa-0a3117564cf6.jpg)
![4081661870346_ pic](https://user-images.githubusercontent.com/42810994/187466352-679f478a-fc5c-4150-80e6-50c134ef9fee.jpg)

**Comment by AAChartModel** [comment]
> 这个函数我能看懂，但这个 288和之前的350是表示什么值

`288 = tooltip宽度 + tooltip 右侧 margin`, 由于暂时没有获得 tooltip 精准宽度的方法, 所以这个值基本上是大概估测加实际测试, 最终试出来的.

**Comment by AAChartModel** [comment]
参考:

* https://api.highcharts.com/highcharts/tooltip.positioner
* https://stackoverflow.com/questions/16300026/highcharts-tooltip-get-position-and-change-class

**Comment by AAChartModel** [comment]
之前一直被官方文档

https://api.highcharts.com/highcharts/tooltip.positioner

中的 `labelWidth`, `labelHeight` , 这两个值, 其实应该就是 tooltip 的宽高, 也就是 `tooltipWidth`, `tooltipHeight`, 就算不是, 也是 tooltip 内部的文字视图的宽度, 基本上也就等同于 tooltip 的宽度

**Comment by DeraDream** [comment]
样式还是有点古怪，会压住线，我想和线拉开一点距离，20左右的样子。
![4111661873817_ pic](https://user-images.githubusercontent.com/42810994/187480094-d707d453-ef63-4c14-bf6a-d9f1013c91e6.jpg)
![4101661873817_ pic](https://user-images.githubusercontent.com/42810994/187480108-c25f2882-54eb-4c6e-8ce9-7c9819c44d12.jpg)
![4091661873817_ pic](https://user-images.githubusercontent.com/42810994/187480126-c185131a-b188-405a-bbb4-b4af940366b2.jpg)

**Comment by DeraDream** [comment]
文档是英文的，我英文不咋地，看的好累，我JS学过一点，但不怎么滴。。。。

**Comment by AAChartModel** [comment]
```js
$(function () {
	$('#container').highcharts({
		title: {
			text: 'Fixed tooltip'
		},
		tooltip: {
			positioner: function (labelWidth, labelHeight, point) {
				return { x: point.plotX + 80, y: 50 };
			},
		},
		xAxis: {
			crosshair:true,
		},
		series: [{
			data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
		}, {
			data: [194.1, 95.6, 54.4, 29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4]
		}]
	});
});
```
类似于这样设置就不会压线了.

> point包含plotX和 plotY的值，即参考点在绘图区上的位置，以及 chart.plotLeft和 chart.plotTop，即图表区距左边距和上边距的距离.

**Comment by DeraDream** [comment]
> > > 这个函数我能看懂，但这个 288和之前的350是表示什么值
> > 
> > 
> > `288 = tooltip宽度 + tooltip 右侧 margin`, 由于暂时没有获得 tooltip 精准宽度的方法, 所以这个值基本上是大概估测加实际测试, 最终试出来的.
> 
> 也就是说, 不用再试了, 直接如下配置 `tooltip` 的 `positioner` 函数即可
> 
> ```swift
>   let screenWidth = UIScreen.main.bounds.size.width
> 
>         //https://stackoverflow.com/questions/16300026/highcharts-tooltip-get-position-and-change-class
>         let positionerStr = """
>         function (tooltipWidth, tooltipHeight, point) {
>                 const xPosition = point.plotX;
>                 const tooltipRightMargin = 20;
>                 const maxXPosition = \(screenWidth) - (tooltipWidth + tooltipRightMargin);
>                 if (xPosition >= maxXPosition) {
>                     xPosition = maxXPosition
>                 }
>                 let position = {};
>                 position["x"] = xPosition;
>                 position["y"] = 50;
>                 return position;
>             }
>         """
> ```

呃  大佬，咱们昨晚不是在讨论悬浮框固定在一个水平面也就是固定Y轴，X轴到边界可以自动转换到另一边显示的问题吗，引用的这个代码我试过了，会压线，也离绿线太近，刚才你最新回复的是X轴写死了，没法到边界自动转换，引用的这份JS数值还需要调试一下

**Comment by AAChartModel** [comment]
>  刚才你最新回复的是X轴写死了，没法到边界自动转换，引用的这份JS数值还需要调试一下

我上面的只是 point 的使用示例, 不是说就完全这样复制粘贴过去就行了.

**Comment by DeraDream** [comment]
那我再调试一下那个js
