### ISSUE TITLE
图表加载问题（Chart loading problem）

### ISSUE THREAD

**Issue by zps18075713849** [AAChartModel/AAChartKit-Swift#405]
图表展示前，加载出来前会有白屏问题（There will be a white screen problem before the chart is displayed and loaded）

**Comment by AAChartModel** [comment]
因为 AAChartView 继承自 WKWebView, 这应该是 WKWebView 固有问题, 在最新的 Xcode  14 的模拟器中尤其明显(可能是模拟器有什么 bug).

不过在真机中测试是正常的.

**Comment by AAChartModel** [comment]
参考相关问题:
* https://github.com/AAChartModel/AAChartKit/issues/260
