### ISSUE TITLE
swifit 如何禁用曲线图的动画效果呢？

### ISSUE THREAD

**Issue by pangliang071** [AAChartModel/AAChartKit-Swift#408]
如题

**Comment by AAChartModel** [comment]
参考此次提交:
* https://github.com/AAChartModel/AAChartKit-Swift/commit/91d5468788ce750fe2a76389fdd2d29258242b44

如下配置:

```swift
        aaOptions.plotOptions?.series?.animation(false)
```

即可禁用图表渲染动画.

**Comment by AAChartModel** [comment]
更新 AAChartKit-Swift 至最新内容, 即可使用. 参考:
* #359
