### ISSUE TITLE
关于column柱状图点击效果

### ISSUE THREAD

**Issue by Xiaxiangjing** [AAChartModel/AAChartKit-Swift#410]
你好，柱状图点击时如何不让柱子的颜色的颜色有变化。
当现显示tip标签时，变化还不太明显，当把.tooltipEnabled设置为false不让标签显示后，点击图表column就有明显的色差，请问如何点击时不让column有颜色变化。
<img width="317" alt="WechatIMG11" src="https://user-images.githubusercontent.com/17426567/205494177-7c31df22-41aa-4191-aa62-9b933cd284c4.png">
<img width="309" alt="WechatIMG12" src="https://user-images.githubusercontent.com/17426567/205494224-87c441b0-1d03-454b-9e74-d72ed0a7e613.png">

下面的的正常颜色，上面的颜色就变了

**Comment by AAChartModel** [comment]
参考相同问题:
* https://github.com/AAChartModel/AAChartKit/issues/949
