### ISSUE TITLE
提示窗的内容如何格式化

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit-Swift#419]
![4B7A9031472D0E02792AC94241816DF7](https://user-images.githubusercontent.com/12290214/212252048-e1548b1c-3aa4-4bed-b26b-4bd2d5bc1b8b.jpg)
上面的数字3我需要显示成“第3题”
下面的数字我需要保留四位小数显示

**Comment by AAChartModel** [comment]
参考 OC 版本的相似问题:
* https://github.com/AAChartModel/AAChartKit/issues/524

**Comment by AAChartModel** [comment]
参考: 
* https://github.com/AAChartModel/AAChartKit-Swift/issues/384#issuecomment-1212863806

**Comment by AAChartModel** [comment]
中文文档: 
* https://api.hcharts.cn/legacy#tooltip.headerFormat
* https://api.hcharts.cn/legacy#tooltip.pointFormat
