### ISSUE TITLE
y轴上是否可以显示平均线

### ISSUE THREAD

**Issue by yangxysir** [AAChartModel/AAChartKit-Swift#426]
y轴上是否可以显示平均线
![image](https://user-images.githubusercontent.com/125718464/229428750-6869610f-595c-40ba-afb1-f9061d373a6b.png)

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit-Swift/issues/231

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/435
