### ISSUE TITLE
折线图使用AADataLabels有时候不显示

### ISSUE THREAD

**Issue by Ivia** [AAChartModel/AAChartKit-Swift#429]
> let series = AASeriesElement()
            .marker(AAMarker().radius(4).lineWidth(3))
            .dataLabels(AADataLabels()
                          .format("{y} \(unit)")
            )
var data: [Int] = []
        var maxY: Double = 0
        for info in infos {
            data.append(info.num)
        }
        series.data(data)
        aaChartModel.series([series])
        aaChartView.aa_refreshChartWholeContentWithChartModel(aaChartModel)

unit是我自己定义的一个变量
data是一组int
采用了AADataLabels有时候会缺少，缺少的点不一定是哪一个
![IMG_0168 2](https://github.com/AAChartModel/AAChartKit-Swift/assets/10719336/2d435eef-a046-4183-ab47-8c0edc31a757)
![IMG_0169 2](https://github.com/AAChartModel/AAChartKit-Swift/assets/10719336/7325465f-0869-4e50-b33e-5dc5142aa698)
![IMG_0170 2](https://github.com/AAChartModel/AAChartKit-Swift/assets/10719336/6630e08e-ec6c-4f5b-bba8-84eabb82fbf0)

如果删除.dataLabels(AADataLabels().format("{y} \(unit)"))则不会缺少

Swift5/iOS15.4.1/iPhone7

**Comment by AAChartModel** [comment]
参考 OC 版本中的相同问题:
* https://github.com/AAChartModel/AAChartKit/issues/707

**Comment by Ivia** [comment]
多谢，已解决
