### ISSUE TITLE
Xcode 15 compile error

### ISSUE THREAD

**Issue by EvanGregg** [AAChartModel/AAChartKit-Swift#433]
When building for Xcode 15 beta for iOS target, I see a number of 
"Stored properties cannot be marked unavailable with '@available'" in AAChartModel.swift:

    @available(*, unavailable, message: "please use titleStyle instead of it")
    public var titleFontColor: String?      //The chart title font color
    @available(*, unavailable, message: "please use titleStyle instead of it")
    public var titleFontSize: Float?        //The chart title font size
    @available(*, unavailable, message: "please use titleStyle instead of it")
    public var titleFontWeight: AAChartFontWeightType? //The chart font weight

    @available(*, unavailable, message: "please use subtitleStyle instead of it")
    public var subtitleFontColor: String?   //The chart subtitle font color
    @available(*, unavailable, message: "please use subtitleStyle instead of it")
    public var subtitleFontSize: Float?     //The chart subtitle font size
    @available(*, unavailable, message: "please use subtitleStyle instead of it")
    public var subtitleFontWeight: AAChartFontWeightType?   //The chart subtitle font weight

    @available(*, unavailable, message: "please use dataLabelsStyle instead of it")
    public var dataLabelsFontColor: String? //The data labels font color
    @available(*, unavailable, message: "please use dataLabelsStyle instead of it")
    public var dataLabelsFontSize: Float?   //The data labels font size
    @available(*, unavailable, message: "please use dataLabelsStyle instead of it")
    public var dataLabelsFontWeight: AAChartFontWeightType?//The data labels font weight
    
    @available(*, unavailable, message: "please use xAxisLabelsStyle or yAxisLabelsStyle instead of it")
    public var axesTextColor: String?       //The labels font color of chart x axis and y axis

    @available(*, unavailable, message: "This property is useless now, please remove it directly")
    public var touchEventEnabled: Bool?     //Support touch event call back or not

**Comment by philrosenthal** [comment]
Same issue here.

**Comment by EvanGregg** [comment]
I think that the code causing the problem can just be removed.  I've forked and I am currently testing with that.

**Comment by mehulparmar4ever** [comment]
Hello, I am also facing this issue in AAInfographics 7.3.0

Someone guide me how to resolve this?

**Comment by HughTsang** [comment]
Same issue here. How to fix it?

**Comment by AndyZZhz** [comment]
Same issue here.

**Comment by mehulparmar4ever** [comment]
Hello @AndyZZhz ,

Use **`master`** branch instead of version in SPM
Your issue will be resolved. 

Good luck!

**Comment by AAChartModel** [comment]
Refer to 
* https://github.com/AAChartModel/AAChartKit/issues/1501
