### ISSUE TITLE
双表数据联动怎么处理呢？

### ISSUE THREAD

**Issue by liuccchi** [AAChartModel/AAChartKit-Swift#434]
![IMG_526F65B9A8CB-1](https://github.com/AAChartModel/AAChartKit-Swift/assets/13333617/c4af31c5-b3c4-4050-8342-c8e8115a506b)
这样的一个View有2个表，现在想要滚动其中一个表另外一个表上选中的数据同步更新。
查了好多issues 找到的方案是下面这个
<img width="872" alt="image" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/13333617/6759e674-38bd-45e1-b1a0-65f5b782aef1">
 用了这个方案虽然最终结果可以做到同步，但是他每次更新都是刷新整个表的的所有数据，有动画，而且数据多了会卡顿、延迟。
 请问有不刷新所以数据只更改选择的item的方法吗

**Comment by AAChartModel** [comment]
AAChartView有只是单独刷新数据而不用刷新整个表的方法，readme文档中有写，你看一下

**Comment by liuccchi** [comment]
你好，你说的是“    aaChartView?.aa_onlyRefreshTheChartDataWithChartModelSeries(chartModelSeriesArray)”  这个方法吗？
如果是的话，可能是我问题没有描述清楚:
1.主要目的是实现图1的上下2个表的选中数据的联动(不知道你是否能看到我传上去图片),就是2个表任意一个表选中05:39这条数据，然后另外一个表也选中这条数据。
2.我问题里说的刷新全部数据是来自于我用了图二的方式(设置Options默认选择item，然后重新赋值给ChartView)来同步2个表格的选中状态，导致了我topChartView的显示内容会一直全部刷新。
3.问题里最后说的不刷新数据只修改选择的item是说想只修改tooltip显示内容和位置 还有选择的黄线的位置

**Comment by AAChartModel** [comment]
听起来你是只想要让两个图表的浮动提示框同步滑动显示，不知道我这样理解对不对？

**Comment by liuccchi** [comment]
对的,就是想同步显示数据，他们X轴都是时间 y轴是各种数据，想要他们显示的数据都是想同时间的的。让他们滑动的时候可以互相影响另外一个表格显示没有被手指滑动的表格

**Comment by AAChartModel** [comment]
是不是类似于这个在线示例效果  https://www.hcharts.cn/demo/highcharts/synchronized-charts ?

**Comment by liuccchi** [comment]
![image](https://github.com/AAChartModel/AAChartKit-Swift/assets/13333617/8fe5196a-6337-4193-8f14-3f7b5089e97c)
我现在自己理解的就是 框选的这段JS代码可以实现想要的功能，但是要想执行这个JS代码需要重新设置Options，而重新设置Options就会导致整个表格重新绘制刷新。
不知道我的思路有没有问题

**Comment by liuccchi** [comment]
> 是不是类似于这个在线示例效果 https://www.hcharts.cn/demo/highcharts/synchronized-charts ?

对对对 就是这个[呲牙]

**Comment by AAChartModel** [comment]
> 我现在自己理解的就是 框选的这段JS代码可以实现想要的功能

你这里所说的是完全正确的

**Comment by liuccchi** [comment]
> > 我现在自己理解的就是 框选的这段JS代码可以实现想要的功能
> 
> 你这里所说的是完全正确的

但是我目前没找到能解决这个问题的方式，  “但是要想执行这个JS代码需要重新设置Options，而重新设置Options就会导致整个表格重新绘制刷新。”

**Comment by AAChartModel** [comment]
> 但是要想执行这个JS代码需要重新设置Options

这里所说的却并非如此. 实际上 AAChartView 本身就是直接继承自 WKWebView 的, 而 WKWebView 本身是可以直接执行 JavaScript 函数的.

**Comment by AAChartModel** [comment]
AAChartKit-Swift 的 demo 中有这个示例:

```swift
    func aaChartViewDidFinishLoad (_ aaChartView: AAChartView) {
        print("🚀🚀🚀AAChartView did finished load")
                
        var jsFunctionStr:String
        if sampleChartTypeIndex == 0 {
            jsFunctionStr = configureMaxMiniDataLabelJSFunctionString()
        } else if sampleChartTypeIndex == 1 {
            jsFunctionStr = configureFirstSecondThirdDataLabelJSFunctionString()
        } else if sampleChartTypeIndex == 2 {
            jsFunctionStr = configureFirstSecondThirdStackLabelJSFunctionString()
        } else {
            //https://jshare.com.cn/jianshu/ZBrzXx
            aaChartView.aa_updateXAxisExtremes(min: 0, max: 3)
            return
        }
        //图表加载完成后调用,避免WebView还没有获得JavaScript上下文,致使调用失败
        aaChartView.aa_evaluateJavaScriptStringFunction(jsFunctionStr)
    }
```

比如这行代码:

```swift
aaChartView.aa_evaluateJavaScriptStringFunction(jsFunctionStr)
```

就是 AAChartView 的实例对象直接调用自定义的 JavaScript 方法.

**Comment by AAChartModel** [comment]
你试试把你的这段代码:

```swift
        aaOptions.chart?.events(
            AAChartEvents()
                .load("""
        function() {
            let points = [],
                chart = this,
                series = chart.series,
                length = series.length;
                        
            for (let i = 0; i < length; i++) {
              let pointElement = series[i].data[\(defaultSelectedIndex)];
              points.push(pointElement);
            }
            chart.xAxis[0].drawCrosshair(null, points[0]);
            chart.tooltip.refresh(points);
          }
"""))
        aaChartView?.aa_drawChartWithChartOptions(chartOptions)
        
```

改成下面👇🏻这段代码:

```swift
   let jsFunc = ("""
        function syncRefreshTooltip() {
            let points = [],
                chart = aaGlobalChart,
                series = chart.series,
                length = series.length;
                        
            for (let i = 0; i < length; i++) {
              let pointElement = series[i].data[\(defaultSelectedIndex)];
              points.push(pointElement);
            }
            chart.xAxis[0].drawCrosshair(null, points[0]);
            chart.tooltip.refresh(points);
          }

         syncRefreshTooltip();
""")
        
        //图表加载完成后调用,避免WebView还没有获得JavaScript上下文,致使调用失败
        aaChartView.aa_evaluateJavaScriptStringFunction(jsFunctionStr)
```
再运行看看效果.

**Comment by liuccchi** [comment]
> AAChartKit-Swift 的 demo 中有这个示例:
> 
> ```swift
>     func aaChartViewDidFinishLoad (_ aaChartView: AAChartView) {
>         print("🚀🚀🚀AAChartView did finished load")
>                 
>         var jsFunctionStr:String
>         if sampleChartTypeIndex == 0 {
>             jsFunctionStr = configureMaxMiniDataLabelJSFunctionString()
>         } else if sampleChartTypeIndex == 1 {
>             jsFunctionStr = configureFirstSecondThirdDataLabelJSFunctionString()
>         } else if sampleChartTypeIndex == 2 {
>             jsFunctionStr = configureFirstSecondThirdStackLabelJSFunctionString()
>         } else {
>             //https://jshare.com.cn/jianshu/ZBrzXx
>             aaChartView.aa_updateXAxisExtremes(min: 0, max: 3)
>             return
>         }
>         //图表加载完成后调用,避免WebView还没有获得JavaScript上下文,致使调用失败
>         aaChartView.aa_evaluateJavaScriptStringFunction(jsFunctionStr)
>     }
> ```
> 
> 比如这行代码:
> 
> ```swift
> aaChartView.aa_evaluateJavaScriptStringFunction(jsFunctionStr)
> ```
> 
> 就是 AAChartView 的实例对象直接调用自定义的 JavaScript 方法.

![image](https://github.com/AAChartModel/AAChartKit-Swift/assets/13333617/01773248-0a97-4222-8ea1-1af95a76d791)
调用红色的代码没反应，调用蓝色的代码报错找不到函数，我现在再试试你刚刚发的代码，谢谢

**Comment by liuccchi** [comment]
> 你试试把你的这段代码:
> 
> ```swift
>         aaOptions.chart?.events(
>             AAChartEvents()
>                 .load("""
>         function() {
>             let points = [],
>                 chart = this,
>                 series = chart.series,
>                 length = series.length;
>                         
>             for (let i = 0; i < length; i++) {
>               let pointElement = series[i].data[\(defaultSelectedIndex)];
>               points.push(pointElement);
>             }
>             chart.xAxis[0].drawCrosshair(null, points[0]);
>             chart.tooltip.refresh(points);
>           }
> """))
>         aaChartView?.aa_drawChartWithChartOptions(chartOptions)
>         
> ```
> 
> 改成下面👇🏻这段代码:
> 
> ```swift
>    let jsFunc = ("""
>         function syncRefreshTooltip() {
>             let points = [],
>                 chart = aaGlobalChart,
>                 series = chart.series,
>                 length = series.length;
>                         
>             for (let i = 0; i < length; i++) {
>               let pointElement = series[i].data[\(defaultSelectedIndex)];
>               points.push(pointElement);
>             }
>             chart.xAxis[0].drawCrosshair(null, points[0]);
>             chart.tooltip.refresh(points);
>           }
> 
>          syncRefreshTooltip();
> """)
>         
>         //图表加载完成后调用,避免WebView还没有获得JavaScript上下文,致使调用失败
>         aaChartView.aa_evaluateJavaScriptStringFunction(jsFunctionStr)
> ```
> 
> 再运行看看效果.

这段代码会报下面的这个错误，我没发现哪里少了 ')' 

> ☠️☠️💀☠️☠️WARNING!!!!!!!!!!!!!!!!!!!! FBI WARNING !!!!!!!!!!!!!!!!!!!!WARNING☠️☠️💀☠️☠️
==========================================================================================
------------------------------------------------------------------------------------------
code = 4;
domain = WKErrorDomain;
userInfo =     {
NSLocalizedDescription = "A JavaScript exception occurred";
WKJavaScriptExceptionColumnNumber = 17;
WKJavaScriptExceptionLineNumber = 191;
WKJavaScriptExceptionMessage = SyntaxError: Unexpected identifier 'syncRefreshTooltip'. Expected ')' to end a compound expression.;
WKJavaScriptExceptionSourceURL = file:///var/containers/Bundle/Application/D524EF95-A2BC-4019-B1EC-BD12859CAE46/CCRoestCoffee.app/Frameworks/AAInfographics.framework/AAJSFiles.bundle/AAChartView.html;

**Comment by liuccchi** [comment]
![image](https://github.com/AAChartModel/AAChartKit-Swift/assets/13333617/a2edf33c-b63f-457d-a1e8-57663251dcae)


你好 我试了下直接调用evaluateJavaScript可以实现，点击的时候延迟可以接受，但是拖动的时候会同步数据会有较大的延迟，甚至是几秒钟，如下面视频所示

https://github.com/AAChartModel/AAChartKit-Swift/assets/13333617/77d3e27d-50a3-418c-88e6-8078b9dd0f84

**Comment by liuccchi** [comment]
> ![image](https://user-images.githubusercontent.com/13333617/248197575-a2edf33c-b63f-457d-a1e8-57663251dcae.png)
> 
> 你好 我试了下直接调用evaluateJavaScript可以实现，点击的时候延迟可以接受，但是拖动的时候会同步数据会有较大的延迟，甚至是几秒钟，如下面视频所示
> 
>  RPReplay_Final1687503994.MP4

是因为注入了太多次的JS导致的吗

**Comment by AAChartModel** [comment]
> 是因为注入了太多次的JS导致的吗

有这个可能, 不过我觉得更大的可能是因为你的数据太多了, 单位之间内的刷新频率太高, 导致 Highcharts 的性能跟不上.

**Comment by liuccchi** [comment]
> > 是因为注入了太多次的JS导致的吗
> 
> 有这个可能, 不过我觉得更大的可能是因为你的数据太多了, 单位之间内的刷新频率太高, 导致 Highcharts 的性能跟不上.

我发现好像是我AASeriesElement 太多了，上面表格带动下面表格的时候 下面表格反应会很快甚至比上面的还快，而且当我把上面的表格AASeriesElement减少到2-3个的时候就都很快了，几乎没什么延迟了。
现在这种效果已经能够使用了，感谢你的帮助  谢谢！
