### ISSUE TITLE
折线图线宽会自动变细

### ISSUE THREAD

**Issue by Ivia** [AAChartModel/AAChartKit-Swift#437]
<img width="1004" alt="image" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/10719336/c498bd26-4003-4928-9dfb-194fa3d0a5dc">
如图，设置线宽为3，但是靠近x轴线宽会变很细，请问这个怎么处理？

**Comment by AAChartModel** [comment]
参考 **Objective-C** 版本的相同问题:
 * https://github.com/AAChartModel/AAChartKit/issues/1482
