### ISSUE TITLE
当最开始数据为0的时候，为了美观想给柱形图设置一个默认的高度，可以实现吗

### ISSUE THREAD

**Issue by szweee** [AAChartModel/AAChartKit-Swift#441]
图中是当数据为0时我设置为0.1的时候的显示效果，但是如果最后那个柱形图的数据过大，也还是显示不出来

<img width="450" alt="截屏2023-07-29 23 03 27" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/20777870/0f019c4a-6463-4578-8ce1-388d3d689648">

**Comment by AAChartModel** [comment]
参考相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/1295
