### ISSUE TITLE
horizontal scroll line graph

### ISSUE THREAD

**Issue by iOSdev-klimov** [AAChartModel/AAChartKit-Swift#443]
Hey, guys, please, help me to share implementation of single line, or 2 lines graphs with horizontal scroll. I would be grateful

**Comment by AAChartModel** [comment]
You can refer to the relevant configuration examples of AAScrollablePlotArea in the demo. However, be cautious when using this feature in Highcharts as it has some bugs. Please consult the issue of Highcharts for reference.

* https://github.com/highcharts/highcharts/issues/14541
