### ISSUE TITLE
Align xAxis labels with xAxis grid lines

### ISSUE THREAD

**Issue by iOSdev-klimov** [AAChartModel/AAChartKit-Swift#444]
Hey, guys. Could please help me to align xAxisLabels with xAxis grid lines to be exactly on the same line, line in the second picture below? 
<img width="369" alt="Screenshot 2023-08-03 at 09 14 26" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/88155930/8f2d7dad-08c2-4dd9-b97b-a3049d663735">
<img width="802" alt="Screenshot 2023-08-03 at 09 40 14" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/88155930/6eea5a1f-0e6c-4a9b-9526-f0e9e9fd6df2">
@AAChartModel, I would be thankful guys

**Comment by AAChartModel** [comment]
refer to the comment

* https://github.com/AAChartModel/AAChartKit-Swift/issues/299#issuecomment-838374988

**Comment by iOSdev-klimov** [comment]
> refer to the comment
> 
> * [Ticks does not match values #299 (comment)](https://github.com/AAChartModel/AAChartKit-Swift/issues/299#issuecomment-838374988)

thank you so much, appreciate
