### ISSUE TITLE
line chart color is not set as gradient color

### ISSUE THREAD

**Issue by iOSdev-klimov** [AAChartModel/AAChartKit-Swift#445]
Hey, guys last question. I'm setting here 2 lines plot and tried to apply gold gradient to one lines. However, only circles are filled. For lines it's not setting that gold gradient color. What am I doing wrong? Any ideas?
<img width="497" alt="Screenshot 2023-08-03 at 11 39 03" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/88155930/c86d9599-20da-4ac7-86f7-c0443572dc90">
<img width="366" alt="Screenshot 2023-08-03 at 11 43 38" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/88155930/a7fe01b5-627c-4ca5-99c0-cb292bc2f6de">

And 2nd last question. How can I create inverted lines, as input I receive positive values for Yaxis, however, I have to set them like below 0, in opposite, remaining positive values(maxY should be 0). How can I do that as well? Below I uploaded my implementation, and my result, and expected result as well, as an example. I would be grateful guys. Really thanks for creating awesome charts. 
@AAChartModel  
<img width="513" alt="Screenshot 2023-08-03 at 11 44 31" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/88155930/64f1ccda-9d29-4a85-9870-a5d24f4e2044">
<img width="365" alt="Screenshot 2023-08-03 at 11 47 56" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/88155930/7ce55905-3b3d-4276-bb80-33dd7e4b8d50">
<img width="444" alt="Screenshot 2023-08-03 at 11 49 52" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/88155930/697d386c-f2b0-4082-8865-f6f262b89698">

**Comment by AAChartModel** [comment]
> I'm setting here 2 lines plot and tried to apply gold gradient to one lines. However, only circles are filled. For lines it's not setting that gold gradient color. What am I doing wrong? Any ideas?

refer to the question:

* https://stackoverflow.com/questions/50037923/highcharts-line-chart-with-constant-series-not-plotting-when-using-linear-gradi

**Comment by AAChartModel** [comment]
>  How can I create inverted lines, as input I receive positive values for Yaxis, however, I have to set them like below 0, in opposite, remaining positive values(maxY should be 0). How can I do that as well? 

Refer to the `yAxisReversed` of `AAChartModel` 

```swift
    public var yAxisReversed: Bool?         //Whether to reverse the axis so that the highest number is closest to the origin. If the chart is inverted, the x axis is reversed by default. Defaults to false
```

or the `reversed` of `AAAxis(AAYAxis)`

```swift
    public var reversed: Bool? //Whether to reverse the axis so that the highest number is closest to the origin. If the chart is inverted, the XOrY-axis is reversed by default.
```

 Online API document:

* https://api.highcharts.com/highcharts/yAxis.reversed

**Comment by AAChartModel** [comment]
Set the `yAxisReversed` of `AAChartModel` be `true` for `areaspline` chart, you will get

<img width="627" alt="截屏2023-08-03 18 09 19" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/16357599/ef1fa770-3625-4350-931b-198dfedd0f06">

you can find the sample in the **AAChartKit-Swift** demo

**Comment by iOSdev-klimov** [comment]
appreciate you 🙌🏼.
