### ISSUE TITLE
如何移除图表上默认存在的数据点？

### ISSUE THREAD

**Issue by kami-kgu** [AAChartModel/AAChartKit-Swift#449]
作者您好，麻烦问下应该如何移除图表上默认生成的数据点呢？就是方形、圆形、倒三角形等的图形。

**Comment by AAChartModel** [comment]
设置 `AAMarker` 的半径大小为 `0` 即可.

**Comment by kami-kgu** [comment]
> ```swift
> public class AAMarker: AAObject {
>     public var enabled: Bool?
>     public var radius: Float?
>     public var symbol: String?
>     public var fillColor: String?
>     public var lineWidth: Float?
>     public var lineColor: Any?
>     public var states: AAMarkerStates?
>   ...
>   ...
> }
> ```
> 
> 设置 `AAMarker` 的 `enabled` 属性是最直接最彻底的方法.

我使用了下述代码，但并没有生效，我目前不确定自己的 api调用是否正确，您可以再协助看一下吗？谢谢了。
let marker = AAMarker()
            .enabled(false)

let options = AAOptions()
options.plotOptions?.series?.marker = marker

aaChartView.aa_drawChartWithChartOptions(options)
aaChartView.aa_drawChartWithChartModel(chartModel)
