### ISSUE TITLE
 希望能支持下xcode15 ,在xcode15上编译 会报错

### ISSUE THREAD

**Issue by TushningJJ** [AAChartModel/AAChartKit-Swift#458]

**Comment by telami** [comment]
同https://github.com/AAChartModel/AAChartKit/issues/1501

希望作者可以支持下，感谢🥹

**Comment by telami** [comment]
same https://github.com/AAChartModel/AAChartKit/issues/1501

**Comment by telami** [comment]
@TushningJJ 作者已修复

**Comment by AAChartModel** [comment]
问题已修复, 参考:

* https://github.com/AAChartModel/AAChartKit/issues/1501
