### ISSUE TITLE
Xcode 15 - Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by rroca1982** [AAChartModel/AAChartKit-Swift#462]
Hi, 

I'm trying to run the project on the new stable XCode 15 and iPhone 15 Pro Rosetta simulator but am getting a few instances of the of following error - "stored properties cannot be marked unavailable with '@available'"

These are showing on some properties of both AAChartModel and AAChartView.

Does anyone know how to fix or if an update can be provided? Thanks

**Comment by AAChartModel** [comment]
Refer To 

* #433
