### ISSUE TITLE
咱们是否支持自定义的Tooltip样式？如下图

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit-Swift#469]
咱们是否支持这个Tooltip样式？
![WX20231208-180006@2x](https://github.com/AAChartModel/AAChartKit-Swift/assets/18547353/8640d259-75f0-4fda-ba4a-a57d3bdab0ca)

**Comment by swordfk** [comment]
help me, can i see your code?

**Comment by tipshot** [comment]
> help me, can i see your code?

![IMG_9ABA44A68918-1](https://github.com/AAChartModel/AAChartKit-Swift/assets/18547353/d53efd39-b99c-4b28-9e4f-6bf19b1db983)

**Comment by tipshot** [comment]
But this has a garbage bug where the arrows below may disappear in cases where the text width is small, which is a bug with highCharts
eg:
![IMG_18C4DD29D801-1](https://github.com/AAChartModel/AAChartKit-Swift/assets/18547353/c93bace0-7398-4edf-b8d0-dee7e6cc0d9f)
