### ISSUE TITLE
toolTip 箭头动画出现bug

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit-Swift#475]
toolTip 箭头动画出现bug

https://github.com/AAChartModel/AAChartKit-Swift/assets/18547353/48749352-a9c7-416e-a0d9-c65fcd68fd42

**Comment by AAChartModel** [comment]
看起来像是和 tooltip 的宽度有关系, 偏窄的 tooltip 默认就没有箭头, 这估计是 Highcharts 的默认效果(就是不知道有没有提供配置选项). 

可以试试将宽度设置为较大一点的固定宽度.

**Comment by tipshot** [comment]
好的，我尝试一下看看是否可以加宽一下，。

**Comment by tipshot** [comment]
<img width="711" alt="62C9591F-E3B0-4DBE-8B6E-2BFDE04D0D1B" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/18547353/bfbf24fb-7fa8-4bb2-a8e1-24930198ca0a">
另外，我还有一个问题想请教一下，就是这个tooltip是否可以固定在指定高度？或者说始终在最高Y值上方那个高度左右 移动，而不是跟随高度移动？请教一下，非常感谢！

**Comment by AAChartModel** [comment]
> 另外，我还有一个问题想请教一下，就是这个tooltip是否可以固定在指定高度？或者说始终在最高Y值上方那个高度左右 移动，而不是跟随高度移动？

参考相同问题:

* https://github.com/AAChartModel/AAChartKit-Swift/issues/233
