### ISSUE TITLE
私有库导入，无法获取最新版本的代码

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit-Swift#477]
s.dependency 'AAInfographics'
pod install后，无论是终端日志还是podfile.lock 都是显示为当前最新版本7.3.0
但是实际上我进行固化或者编译的时候，提示报错（老版本代码，新版本已经不存在）。
![image](https://github.com/AAChartModel/AAChartKit-Swift/assets/18547353/66b11081-455d-422e-9456-929b4150d214)
![image](https://github.com/AAChartModel/AAChartKit-Swift/assets/18547353/582e2adb-cc3f-4c00-b979-fecf529526eb)

**Comment by tipshot** [comment]
但是如果我在 私有库的demo工程的podfile文件中添加AAInfographics为pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'，发现本地pod文件夹中的代码已经是最新的，但是依然无法对私有库进行固化，并且报错所是一样的。报错信息如下图：
![image](https://github.com/AAChartModel/AAChartKit-Swift/assets/18547353/b80572c8-2bad-4f32-89fc-789ea1ce1c25)

**Comment by tipshot** [comment]
尝试对 AAInfographics 注释并重新添加、删除本地pod 缓存、删除deviceData文件夹、删除.cocoapod文件夹、重启xcode\电脑等等方法，发现依然不行。

**Comment by AAChartModel** [comment]
```ruby
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  AAInfographics (9.0.0) successfully published
 📅  January 31st, 01:07
 🌎  https://cocoapods.org/pods/AAInfographics
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

在 **CocoaPods** 更新了 **AAChartKit-Swift** 最新版本为 `9.0.0`, 你再试试吧.

**Comment by AAChartModel** [comment]
相关问题, 参考:
* https://github.com/AAChartModel/AAChartKit/issues/1501

**Comment by tipshot** [comment]
好的，已经固化成功～～～～
