### ISSUE TITLE
Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by gizemturker** [AAChartModel/AAChartKit-Swift#478]
I'm encountering a persistent issue after transitioning my project from Xcode 14.3.1 to Xcode 15.0.1, with the iOS build target initially set at 13.0 and also tested on 14.0. The problem persists across both iOS targets. The specific error is: "Stored properties cannot be marked unavailable with '@available'" found in AAChartModel.swift at line 504. Despite attempting solutions suggested in similar GitHub issue threads, the error remains unresolved. This seems to be a compatibility issue with Xcode 15.0.1, particularly concerning the @available attribute usage on stored properties within the AAChartKit-Swift library.

<img width="1008" alt="Screenshot 2024-03-07 at 17 30 57" src="https://github.com/AAChartModel/AAChartKit-Swift/assets/17044304/e03cba2f-170d-4f2f-8cd2-925ff7c1dcae">

**Comment by AAChartModel** [comment]
Refer To 

* #433
