### ISSUE TITLE
第一个坐标怎么距离Y轴近一点

### ISSUE THREAD

**Issue by Toj-dev** [AAChartModel/AAChartKit-Swift#485]

**Comment by Toj-dev** [comment]
比如
X轴值是 category (name1, name2....)
Y轴值是                  (0.5, 0.8......)
name1点 尽量贴近Y轴

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/577
* https://github.com/AAChartModel/AAChartKit/issues/937

**Comment by Toj-dev** [comment]
好的谢谢
