### ISSUE TITLE
怎么改变X轴到底部category文字的距离

### ISSUE THREAD

**Issue by Toj-dev** [AAChartModel/AAChartKit-Swift#486]
![image](https://github.com/AAChartModel/AAChartKit-Swift/assets/43204431/5f45776c-d35c-4900-b3af-5bcd6612efb0)

**Comment by Toj-dev** [comment]
还有Y轴的距离

**Comment by AAChartModel** [comment]
`X` 轴:
* https://api.highcharts.com/highcharts/xAxis.labels.distance
* https://api.highcharts.com/highcharts/xAxis.labels.y

**Comment by AAChartModel** [comment]
> 还有Y轴的距离

`Y` 轴同理:
* https://api.highcharts.com/highcharts/yAxis.labels.distance
* https://api.highcharts.com/highcharts/yAxis.labels.y

**Comment by Toj-dev** [comment]
谢谢 帮帮哒
