### ISSUE TITLE
legend 能自定义布局内部布局吗？

### ISSUE THREAD

**Issue by andy90s** [AAChartModel/AAChartKit-Swift#488]
我的需求是 圆点在上，文案在下，有这样的布局api吗。 我试了labelformat 只是针对label文本的。 或者有其他折中方案？求大佬解惑

**Comment by AAChartModel** [comment]
Highcharts 默认的 API 没有直接提供这样的布局选项.  折衷的方案如下:
* 使用 `legend.useHTML` 自定义 HTML 布局: 你可以启用 `legend.useHTML` 选项，然后使用 HTML 和 CSS 来自定义图例项的结构，将圆点和文本放置在你想要的位置。

* 使用 `SVGRenderer` 绘制自定义图例: 使用 Highcharts 的 `SVGRenderer` API， 你可以完全自定义图例，包括圆点和文本的位置、样式等。 这需要更多的代码编写，但能实现最大的灵活性。

以上内容来自在线 AI 工具.

**Comment by AAChartModel** [comment]
我个人觉得没必要这么麻烦, 最好是直接禁用 HIghcharts 的默认 `legend`, 然后自己用原生的自由绘制.  毕竟 `legend` 是 Highcharts 图表当中相当简单且孤立的组成部分.

**Comment by andy90s** [comment]
> 我个人觉得没必要这么麻烦, 最简单的办法是:
> 
> * 直接禁用 Highcharts 的默认 `legend`, 然后自己用原生 `UIView` 或者是原生绘图 API 来自由绘制你想要的自定义内容.
> 
> 毕竟 `legend` 是 Highcharts 图表当中相当简单且孤立的组成部分.

是的，我打算原生结合来做了。还好没有什么交互，只是展示。
