### ISSUE TITLE
点击Y轴数据获取到的坐标不准确

### ISSUE THREAD

**Issue by liujieyuu** [AAChartModel/AAChartKit-Swift#489]
func aaChartView(_ aaChartView: AAChartView, clickEventMessage: AAClickEventMessageModel){

   if let dic = clickEventMessage.offset as? [String:Double]{
            var xP = 0.0
            var yP = 0.0
            if let x = dic["plotX"]{
                xP = x
            }
            if let y = dic["plotY"]{
                yP = y
            }
//这里的x和y有时候不准确，x的值偏小
}
![IMG_1761](https://github.com/user-attachments/assets/827063bc-e7d9-4401-aa16-d9b5d0d612d6)
![IMG_1762](https://github.com/user-attachments/assets/bb49f6a1-2394-412c-af22-e87424364043)
![IMG_1763](https://github.com/user-attachments/assets/f38ff8b2-e736-4ea9-a6e9-07dff842788a)
![IMG_1764](https://github.com/user-attachments/assets/1d9f50dd-6d7e-4170-a33f-b8cac021af87)

**Comment by AAChartModel** [comment]
看起来, 你似乎是要自定义选中的线, 参考:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/372

**Comment by AAChartModel** [comment]
另参考:
* https://stackoverflow.com/questions/16617129/what-are-the-plotx-ploty-values-of-a-point-in-highcharts
