### ISSUE TITLE
设置yAxisMax，yAxisMin后，图表的值为最大最小值时，顶部或者底部会被切割一部分，显示不全。

### ISSUE THREAD

**Issue by LoseRecall** [AAChartModel/AAChartKit-Swift#491]
<img width="425" alt="企业微信20240823-093254@2x" src="https://github.com/user-attachments/assets/e1f92608-ab75-4714-8740-8ddf65cdacde">
如图会缺少一部分像素，不太想在最大值、最小值的基础上再加减去解决显示问题。
大佬这种怎么解决啊？

**Comment by AAChartModel** [comment]
* https://api.highcharts.com/highcharts/yAxis.maxPadding
* https://api.highcharts.com/highcharts/yAxis.minPadding

从文档看起来, 这两个属性, 应该刚好适合你的这个场景, 但是我在线测试, 感觉就好像没啥效果一样.

**Comment by AAChartModel** [comment]
* https://api.highcharts.com/highcharts/yAxis.softMax
* https://api.highcharts.com/highcharts/yAxis.softMin

不知道你的最大值最小值改成这种软性的 max 和 min, 会不会好一点?

**Comment by LoseRecall** [comment]
用这两个属性好像不能设置yAxisMax,yAxisMin,我就是希望在Y轴最低、最高值的基础上，保证图表完整，如果设置maxPadding，会导致y坐标最大值更改

**Comment by AAChartModel** [comment]
> 不太想在最大值、最小值的基础上再加减去解决显示问题。 大佬这种怎么解决啊？

参考:
* https://stackoverflow.com/questions/64397169/highcharts-with-a-thick-line-at-0-values-the-line-is-half-hidden

此方法似乎也是通过轻微改变最大值和最小值, 才解决的问题.

**Comment by LoseRecall** [comment]
> > 不太想在最大值、最小值的基础上再加减去解决显示问题。 大佬这种怎么解决啊？
> 
> 参考:
> 
> * https://stackoverflow.com/questions/64397169/highcharts-with-a-thick-line-at-0-values-the-line-is-half-hidden
> 
> 此方法似乎也是通过轻微改变最大值和最小值, 才解决的问题.

好吧，谢谢，好像也没有别的办法了
