### ISSUE TITLE
自定义connectorShape

### ISSUE THREAD

**Issue by zhangjimjim** [AAChartModel/AAChartKit-Swift#492]
自定义connectorShape支持function在swift里面怎么实现？如图效果怎么实现
![image](https://github.com/user-attachments/assets/aab507de-3077-4030-9648-c51d7695d4cd)

**Comment by AAChartModel** [comment]
参考此次提交的内容:
* https://github.com/AAChartModel/AAChartKit-Swift/commit/614f3a3bfb73730355acafa787146351fbe3ba69

自定义 `labels` 文字颜色相关问题, 参考:
* #404
