### ISSUE TITLE
图表 `Y` 轴自定义显示

### ISSUE THREAD

**Issue by colaxp** [AAChartModel/AAChartKit-Swift#493]
怎么配置显示啊，我修改js也不行，不想显示K或者M，求助啊

**Comment by colaxp** [comment]
<img width="141" alt="image" src="https://github.com/user-attachments/assets/4b8c3c2b-1620-4ae1-abc4-b667bf62e47d">

**Comment by AAChartModel** [comment]
参考相关问题:
* https://github.com/AAChartModel/AAChartKit/issues/1324

**Comment by AAChartModel** [comment]
也可以直接向在线 AI 工具提问:
* https://www.highcharts.com/chat/gpt/

示例如下:
<img width="995" alt="截屏2024-09-18 17 29 08" src="https://github.com/user-attachments/assets/a415c84e-f3a8-4384-aec8-5d25de49acf4">

此工具的优势是: 能够实时创建可交互的最终图表, 结果直观, 简洁, 易懂.
