### ISSUE TITLE
Y轴的规律是如何的

### ISSUE THREAD

**Issue by colaxp** [AAChartModel/AAChartKit-Swift#495]
<img width="311" alt="image" src="https://github.com/user-attachments/assets/51735ff3-3616-4643-835f-ef9e1cc536bb">
如图y最大值为300不到294但是显示的刻度还有400

**Comment by AAChartModel** [comment]
据我观察, Highcharts 是有意为之的, 这样自动调整 Y 轴最大值, 能够使得图表有一定的空间留白, 使之看起来更美观.

**Comment by AAChartModel** [comment]
如果你想自定义 **Y** 轴的最大值 `max` 和最小值 `min`, 参考在线文档:

* https://api.highcharts.com/highcharts/yAxis.max
* https://api.highcharts.com/highcharts/yAxis.min

**Comment by zwp4210933** [comment]
我也有这样的问题，请问解决了吗
