### ISSUE TITLE
How can I detect if the tooltip is being shown? (I want to check for a deselect event)

### ISSUE THREAD

**Issue by meirinberg** [AAChartModel/AAChartKit-Swift#496]
I see that this was an old Highcharts question [here](https://stackoverflow.com/questions/34202979/highcharts-detect-if-tooltip-is-being-shown) with the answer leading to [this JSFiddle](http://jsfiddle.net/k2fus626/2/). However, I haven't found the way to check if the tooltip is hidden using AAChartKit-Swift. For my application, I use the basic and custom callbacks to pass data when the user selects points (using moveOverEventMessage in basic instances and .mouseOver(*js injection*) when I need to pass a custom object). This works great and it allows me to show chart details that are synchronized with the tooltip (awesome!). However, I'd like these details to disappear when the tooltip disappears so I need to know when the tooltip is showing or when the user deselects.

This is my initial attempt, but the callback doesn't fire when the tooltip is hidden:
```swift
            aaOptions.chart?.events(
                AAChartEvents()
                    .load("""
                    function() {
                        const tooltip = this.chart.tooltip;
                        let message = {
                        selectionID: ""
                        };
                        if (tooltip.isHidden && window.webkit && window.webkit.messageHandlers) {
                            window.webkit.messageHandlers.deselect.postMessage(message);
                        }
                    }
            """))
```
            
Any help is appreciated, thank you!

**Comment by AAChartModel** [comment]
Refer to this commit:

* https://github.com/AAChartModel/AAChartKit-Swift/commit/1f580606d4ea07cdbd0e5c871923b436cd5541db

**Comment by AAChartModel** [comment]
However, using a timer to get the `isHidden` status of the tooltip is a bad idea; it is both annoying and highly inefficient.

**Comment by AAChartModel** [comment]
With the help of online AI tools, I found a better solution.
Please refer to this commit for the improved approach:
* https://github.com/AAChartModel/AAChartKit-Swift/commit/1189f6c78751f8dc1e4d27bff8f7fe1f586707ee

**Comment by AAChartModel** [comment]
You need to update the demo to see the all new code.

**Comment by meirinberg** [comment]
That worked! The following code snippet is exactly what I wanted. 
`                    .load("""
                    function() {
                        Highcharts.wrap(Highcharts.Tooltip.prototype, 'hide', function (proceed, delay) {
                            proceed.apply(this, Array.prototype.slice.call(arguments, 1));
                            window.webkit.messageHandlers.deselect.postMessage('Tooltip is being hidden');
                        });
                    }
                    """))`
                    
Thanks so much for the fast and helpful response!
