### ISSUE TITLE
Programatically open tooltip

### ISSUE THREAD

**Issue by jfredsilva** [AAChartModel/AAChartKit-Swift#506]
Hi,

I would like to programatically open a specific point on the chart.
Is there a way to do it?

Thanks

**Comment by jfredsilva** [comment]
Tried calling the method "evaluateJavaScript" with the string ""aaGlobalChart.charts[0].tooltip.refresh(chart.series[0].points[0]);" "like shown in [this example](https://jsfiddle.net/94zfmest/).

But it's returning the error "WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'aaGlobalChart.charts[0]')"

**Comment by jfredsilva** [comment]
> Try this again:
> 
> ```swift
> aaGlobalChart.tooltip.refresh(chart.series[0].points[0]);
> ```

We're almost there, now the error is "WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: chart"

**Comment by AAChartModel** [comment]
Try this again:

```swift
aaGlobalChart.tooltip.refresh(aaGlobalChart.series[0].points[0]);
```

**Comment by jfredsilva** [comment]
I was able to open the tooltip with
`"aaGlobalChart.series[0].points[0].onMouseOver();"`
