### ISSUE TITLE
设置AAChartZoomType.none时，整体都会放大

### ISSUE THREAD

**Issue by FlyerYe** [AAChartModel/AAChartKit-Swift#56]
设置AAChartZoomType.none时，手势缩放会导致整体缩放 @AAChartModel

**Comment by AAChartModel** [comment]
是么?为什么我的 Demo 运行在真机上无法复现呢?

**Comment by FlyerYe** [comment]
Swift版，iOS 11， @AAChartModel 
![20cac8ed-0794-4b50-a5db-2f9e5c0e061d](https://user-images.githubusercontent.com/15828484/38465296-bf9b4390-3b4c-11e8-86e6-eb3c013ee002.png)
![qq20180408-165203-hd](https://user-images.githubusercontent.com/15828484/38465363-48288402-3b4d-11e8-87f1-1b141df115f2.gif)

**Comment by AAChartModel** [comment]
问题已修复
