### ISSUE TITLE
What means "Can't find variable: loadTheHighChartView"

### ISSUE THREAD

**Issue by invisible66** [AAChartModel/AAChartKit-Swift#59]
Hi everyone,

What means `Can't find variable: loadTheHighChartView` ? And how can i fix this?

Thats my code             
```Swift
            aaChartModel = AAChartModel()
                .chartType(AAChartType.Column)
                .colorsTheme(["#ffd066","#ef476f"])
                .title("")
                .subtitle("")
                .zoomType(.None)
                .legendAlign(.Left)
                .dataLabelEnabled(true)
                .tooltipValueSuffix("")
                .backgroundColor("#ffffff")
                .animationType(AAChartAnimationType.EaseInExpo)
                .series([
                    AASeriesElement()
                        .name("Answered")
                        .data(answeredArr)
                        .toDic()!,
                    AASeriesElement()
                        .name("No Answer")
                        .data(noAnsweredArr)
                        .toDic()!
                    ])

            aaChartModel = aaChartModel?
                .categories(categoryArr)
                .legendEnabled(true)
                .animationType(AAChartAnimationType.Bounce)
                .animationDuration(800)

            aaChartView?.aa_refreshChartWholeContentWithChartModel(aaChartModel!)

```
Full Error Output : 

`☠️☠☠\357☠\357\357\270️\360\237\222💀\360\237\222💀\342\230☠\357\270️\357\270️\342\357\270️\342\342\230☠\357\270️\342\342\230☠\357\270️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, WKJavaScriptExceptionColumnNumber=21, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=A JavaScript exception occurred}`

**Comment by AAChartModel** [comment]
why you did not do what I said in README? you should use the `aa_drawChartWithChartModel ` rather than `aa_refreshChartWholeContentWithChartModel `!!!

**Comment by invisible66** [comment]
I read README but did not realize, I am sorry. And thanks for answer.

**Comment by AAChartModel** [comment]
Okay
