### ISSUE TITLE
enums not public

### ISSUE THREAD

**Issue by ghost** [AAChartModel/AAChartKit-Swift#61]
Hi, although I'd really love to use your lib, I cannot do it due to non-public enums.
I installed AAInfographics as pod, so I have no access to those internals.

**Comment by seenoevo** [comment]
I concur!

Please change access modifiers for those using CocoaPods.

**Comment by AAChartModel** [comment]
AAChartKit-Swift do not support cocoapods yet

**Comment by AAChartModel** [comment]
this issue was fixed now!!!

https://github.com/AAChartModel/AAChartKit-Swift#installation
