### ISSUE TITLE
swift版本支持双y轴显示吗

### ISSUE THREAD

**Issue by Vutumn** [AAChartModel/AAChartKit-Swift#67]
如题

**Comment by AAChartModel** [comment]
暂未支持?额话说你为啥要用 Swift 版的啊?

**Comment by AAChartModel** [comment]
Swift 版本的目前只能够算作是完成了 OC 版本的80%的功能.

**Comment by Vutumn** [comment]
我的项目用的swift写的，所以想用swift版

**Comment by AAChartModel** [comment]
O__O "…

**Comment by AAChartModel** [comment]
所以你之前使用 AAChartKit 都是 OC 和 Swift 混编的?

**Comment by Vutumn** [comment]
没啊，之前项目用的oc版本，现在才整个项目用swift在写

**Comment by Vutumn** [comment]
现在只能混编了

**Comment by Vutumn** [comment]
混编这块还没弄过呢

**Comment by AAChartModel** [comment]
不过我可以对 AAChartKit-Swift 进行粗暴的修改,勉强应该能够满足自由设置双 Y 轴图表📈的功能.

**Comment by Vutumn** [comment]
粗暴会不会出现某些隐患，怕会导致其它的问题呢

**Comment by Vutumn** [comment]
今天采用了混编的写法，但是关于chartmodel的赋值这块不知道怎么用swift的语法调用，想请教一下这块该如何写

**Comment by AAChartModel** [comment]
混编我也没玩过,不知道耶

**Comment by AAChartModel** [comment]
问题已解决,参见 https://github.com/AAChartModel/AAChartKit-Swift/issues/170
