### ISSUE TITLE
运行crash, 定位在了 “toJSON”方法

### ISSUE THREAD

**Issue by rainedAllNight** [AAChartModel/AAChartKit-Swift#73]
![0a966122-eb9b-454a-a105-3f0da12457d2](https://user-images.githubusercontent.com/16357931/43124677-651b1ee2-8f5a-11e8-8641-fe442805a8e4.png)

**Comment by AAChartModel** [comment]
是 Demo 直接运行 crash 还是修改或者添加了什么代码之后 crash/

**Comment by rainedAllNight** [comment]
集成的时候, 代码如下

![image](https://user-images.githubusercontent.com/16357931/43174883-05b9777e-8fef-11e8-82e3-12f0f823f84e.png)

**Comment by AAChartModel** [comment]
颜色主题只支持
```objective-c
            .colorsTheme(["#1e90ff","#ef476f","#ffd066","#04d69f","#25547c",])//主题颜色数组
```
这种十六进制字符串数组,配置 AAChartModel 后来是为了能够转换成 json 字符串的,你的代码里的数组元素 UIColor.red到时候是无法转换成 json 的,所以你只要修改一下 colorTheme 里面对的数组元素为`""#ff00dd"`这种十六进制颜色字符串即可.


**另**:
* 下次附上代码的时候请直接粘贴代码文本,并使用 markdown 标签使代码高亮
* 像你这样直接贴图片我要复现问题的时候,还得一个个字符的敲完全能够把人累死
* 网速慢的时候你贴的图片半天时间死活加载不出来,能急死人

**Comment by rainedAllNight** [comment]
ok，很好的建议，thank you
