### ISSUE TITLE
how to detect touch event for each column for chartType(.Column)?

### ISSUE THREAD

**Issue by lawreyios** [AAChartModel/AAChartKit-Swift#81]
how to detect touch event for each column for chartType(.Column)?

**Comment by parthsit** [comment]
how to detect tooltip popup click event???

**Comment by AAkhandSingh** [comment]
how to detect touch event for each column for chartType(.Column)?

**Comment by AAChartModel** [comment]
## support-user-click-events-and-move-over-events

https://github.com/AAChartModel/AAChartKit-Swift#support-user-click-events-and-move-over-events

**Comment by cminero10** [comment]
> how to detect tooltip popup click event???

Did you figure it out?
