### ISSUE TITLE
Xcode10.0 Swift4.2 编译错误

### ISSUE THREAD

**Issue by ylqh** [AAChartModel/AAChartKit-Swift#88]
![image](https://user-images.githubusercontent.com/24707772/46062275-dd330480-c19b-11e8-98df-c2a824fc93c6.png)

AASerializable.toDic() 方法没权限访问

**Comment by AAChartModel** [comment]
你是运行 demo 报的错,还是使用 Cocoapods 集成时报的这个错?

**Comment by ylqh** [comment]
Cocoapods集成

**Comment by ylqh** [comment]
> 你是运行 demo 报的错,还是使用 Cocoapods 集成时报的这个错?

 Cocoapods 集成

**Comment by prasen-ftech** [comment]
> 方法没权限访问

I am facing same issue

**Comment by ylqh** [comment]
> I made use of source directly, instead of pods. It worked

That's what I'm doing right now

**Comment by RomuloVHSYS** [comment]
#91 has the same error. And it's solved on [that commit](https://github.com/AAChartKit/AAChartKit-Swift/commit/121b9820bb62c71b79c0910f34dfe6e2a8d6cc3a)

**Comment by AAChartModel** [comment]
```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
```

参见 #125
