### ISSUE TITLE
请问,在一个view中创建两个chartView时,为什么第二个添加的view 不展示!(两个chartView和chartModel都已单独创建)

### ISSUE THREAD

**Issue by Leesoon** [AAChartModel/AAChartKit-Swift#9]

**Comment by Leesoon** [comment]
swift 版本的也还是不能同时创建多个啊

**Comment by AAChartModel** [comment]
OC 版本已添加同时显示多个 AAChartView 的示例代码,更新项目运行查看效果即可, Swift 版本暂未解决此问题.容我作后续修改😲

**Comment by Leesoon** [comment]
好吧!!!!

**Comment by AAChartModel** [comment]
已添加显示同时显示多个`AAChartView`的示例代码,更新 ***AAChartKit-Swift*** 项目 `Demo`,运行查看效果即可.
