### ISSUE TITLE
titleColor subTitleColor and axisColor not working

### ISSUE THREAD

**Issue by RomuloVHSYS** [AAChartModel/AAChartKit-Swift#92]
Changing these properties don't change anything on the chart. Title, subtitle and axisColor continues with the default color.

Here is my code:

```swift
let aaChartView = AAChartView()
        aaChartView.frame = CGRect(x:8,y:8,width:chartViewWidth,height:chartViewHeight)
        aaChartView.isClearBackgroundColor = true
        
        self.vwGradient.addSubview(aaChartView)
        
        let aaChartModel = AAChartModel()
            .chartType(.column)
            .animationType(.bounce)
            .title("Financeiro")
            .subtitle("sample")
            .dataLabelEnabled(false)
            .tooltipEnabled(true)
            .tooltipValueSuffix("R$ ")
            .categories(["jan", "fev", "mar", "abr", "mai", "jun"])
            .colorsTheme(["#00FFEB","#705991"])
            .series([
                    AASeriesElement()
                        .name("Receitas")
                        .data([1056.52, 1456.99, 1456.45, 1458.68, 1678.64, 1876.98])
                        .toDic()!,
                
                    AASeriesElement()
                        .name("Despesas")
                        .data([1056.52, 1456.99, 1456.45, 1458.68, 1678.64, 1876.98].reversed())
                        .toDic()!,
                ])
            .yAxisGridLineWidth(0.0)
            .xAxisGridLineWidth(0.0)
            .backgroundColor("#00000000")
            .titleColor("#f4ab0e")
            .axisColor("#f4ab0e")
            .subTitleColor("#f4ab0e")
        
        aaChartView.aa_drawChartWithChartModel(aaChartModel)
```

**Comment by AAChartModel** [comment]
<img width="544" alt="32d01daa-4e9f-48c3-8842-3956c5d9f229" src="https://user-images.githubusercontent.com/16357599/47370254-ecb05980-d717-11e8-9d63-ffc999f7d8c7.png">


Are you sure about that? this is the chart that I draw it with you AAChartModel instance in AAInfographics demo. as you can see, the default color of title and axis  is gray, now it become a little bit of gold just like you configured  as "#f4ab0e"

**Comment by AAChartModel** [comment]
Change the `"#00000000"` to be `"#000000"`(there just six zero) you will get the black background color for chart
<img width="466" alt="1b5a3007-87b1-4977-b6f7-6385b963109f" src="https://user-images.githubusercontent.com/16357599/47371270-17031680-d71a-11e8-8ae2-fb28ddfda661.png">

**Comment by RomuloVHSYS** [comment]
In put eight zero to get a transparent background(plus two for alpha).

I'm sure, all these labels stay dark gray. Maybe that's occurring because i put the the chartView on a view with Gradient layer?

That's the result of my code: 
![image](https://user-images.githubusercontent.com/44377984/47375164-0759e280-d6c6-11e8-914b-7e67263ac057.png)

**Comment by RomuloVHSYS** [comment]
Ooh, my mistaken, sorry

I've update the pod recently, and i forgot to update the AAJSFiles.Bundle that i importe into my project. Replacing this to the updated file solved the problem. 

Thanks for attention.

**Comment by Hardiktspaceo** [comment]
@ RomuloVHSYS is avove x and y axis lable color related issue solve in latest pod download ? I'm facing same issue in latest version.

**Comment by RomuloVHSYS** [comment]
@Hardiktspaceo , with my experience using that library, that problem get solved a while ago.

But i think the cocoapod release has no update, by workaround try to use pod that way `pod 'AAInfographics', :git => 'https://github.com/AAChartKit/AAChartKit-Swift.git', :branch => 'master'` checkouting the master branch to get the latest updates.

**Comment by Hardiktspaceo** [comment]
Ok i will try using above and update you for the same.

**Comment by RomuloVHSYS** [comment]
I just found out that my project was this issue too.

I'v need to change branch and update my pods, when i update the labels become dark gray and the bottom line change and lost the small vertical separators.

I'm reopening the issue @AAChartModel

**Comment by RomuloVHSYS** [comment]
I think that's happening because of that commit 5770f0329f6676dd0033a71bc85d7904d706c41b
Maybe one property have changed the name when migrate from version 5.0.5 to version 7.1.1 of Highcharts

**Comment by RomuloVHSYS** [comment]
I can't found the `axisColor` that the library is using on AAOptionsConstructor.swift > configureAAoptions(aaChartModel:) > {line 104} `aaOptions.setValue(aaChartModel.axisColor, forKey: "axisColor")`

In the docs of Highcharts i'v found that now the axis label color is changed that way:

```
xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        labels: {
            style: {
                color: 'red'
            }
        }
    }
```

And the library is generating the axis like this:

```
xAxis : {    
        gridLineWidth : 0,    
        label : {      
                enabled : true    
        },    
        categories : [      "dez",      "jan",      "fev",      "mar",      "abr",      "mai"    ],    
        visible : true  
}
```

So, the library doesn't change the axis label color because before the property `axisColor` change that

**Comment by RomuloVHSYS** [comment]
@Hardiktspaceo and @AAChartModel 

I found the solution but i don't have enough time to make a MR now, so here it is the solution:

**Replace the `configureAAOptionsAxisContentAndStyle(aaOptions:aaChartModel:)` with the following**

```
private static func configureAAOptionsAxisContentAndStyle(aaOptions: NSMutableDictionary,
                                                              aaChartModel: AAChartModel) {
        let chartType = aaChartModel.chartType
        
        //x 轴和 Y 轴的相关配置,扇形图、金字塔图和漏斗图则不需要设置 X 轴和 Y 轴的相关内容
        if (   chartType != AAChartType.pie
            && chartType != AAChartType.pyramid
            && chartType != AAChartType.funnel) {
            
            let aaXAxis = NSMutableDictionary()
            aaXAxis.setValue(["enabled":aaChartModel.xAxisLabelsEnabled!], forKey: "label")// X 轴是否显示文字
            aaXAxis.setValue(aaChartModel.xAxisReversed, forKey: "reversed")//是否反转 X 轴
            aaXAxis.setValue(aaChartModel.xAxisGridLineWidth, forKey: "gridLineWidth")// X 轴网格线宽度
            aaXAxis.setValue(aaChartModel.categories, forKey: "categories")
            aaXAxis.setValue(aaChartModel.xAxisVisible, forKey: "visible")
            
            let aaXAxisLabels = NSMutableDictionary()
            aaXAxisLabels.setValue(["color":aaChartModel.axisColor!], forKey: "style")
            aaXAxis.setValue(aaXAxisLabels, forKey: "labels")
            
            let aaYAxis = NSMutableDictionary()
            aaYAxis.setValue(["enabled":aaChartModel.yAxisLabelsEnabled!] , forKey: "label")// Y 轴是否显示数字
            aaYAxis.setValue(aaChartModel.yAxisReversed, forKey: "reversed")//是否反转 Y 轴
            aaYAxis.setValue(aaChartModel.yAxisGridLineWidth, forKey: "gridLineWidth") // Y 轴网格线宽度
            aaYAxis.setValue(["text":aaChartModel.yAxisTitle], forKey: "title")//Y 轴标题
            aaYAxis.setValue(aaChartModel.yAxisLineWidth, forKey: "lineWidth")
            aaYAxis.setValue(aaChartModel.yAxisVisible, forKey: "visible")
            
            let aaYAxisLabels = NSMutableDictionary()
            aaYAxisLabels.setValue(["color":aaChartModel.axisColor!], forKey: "style")
            aaYAxis.setValue(aaXAxisLabels, forKey: "labels")
            
            aaOptions.setValue(aaXAxis, forKey: "xAxis")
            aaOptions.setValue(aaYAxis, forKey: "yAxis")
        }
    }
```

**Comment by RomuloVHSYS** [comment]
But i can't figure why the small vertical separators on the X axis have done, can you help me?

**Comment by AAChartModel** [comment]
@RomuloVHSYS  Thanks for your help,It's fixed now

**Comment by Hardiktspaceo** [comment]
@RomuloVHSYS and @AAChartModel Thank you so much for a quick reply and solution.
