### ISSUE TITLE
How to display yAxis at right side?

### ISSUE THREAD

**Issue by iOS-dev-avinash** [AAChartModel/AAChartKit-Swift#98]
How to display yAxis at right side?

**Comment by geekstars** [comment]
Hope to help you @iOS-dev-avinash 

let aaOptions = aaChartModel.aa_toAAOptions()
aaOptions.yAxis?.opposite(true)

aaChartView.aa_drawChartWithChartOptions(aaOptions)

**Comment by geekstars** [comment]
Duplicate of #95
