### ISSUE TITLE
引入 JavaScriptCore 框架,实现便捷式 Swift 和 JavaScript 交互

### ISSUE THREAD

**Issue by AAChartModel** [AAChartModel/AAChartKit-Swift#99]

**Comment by yejunyou** [comment]
Hi! when I run the code from README.m file, it throws an error at run time:
-----------------------------------
let path = Bundle.main.path(forResource: "AAChartView", ofType: "html", inDirectory: "AAJSFiles.bundle")
let urlStr = NSURL.fileURL(withPath: path!)
-----------------------------------
xcode tips the 'path' is nil:
```
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```
actually, the file is exist and the path is right, so what I'm suppose to do

**Comment by AAChartModel** [comment]
similar issue  #75

**Comment by mark644873613** [comment]
上述问题我也遇到了，解决办法如下：
你看你是不是在Pods  里面添加了use_frameworks!  1）如果是你可以试着把这个删除  就可以正常编译  2）如果不删除请在 BuildPhases -> copy Bundel Resources  中添加对应的AAJSFiles.bundle  （不要引用添加噢 ！）
